---
permalink: api-automation/concept_modify_workloads_workflow.html 
sidebar: sidebar 
keywords: modify, storage, workloads 
summary: Das Ändern von Speicher-Workloads besteht aus der Aktualisierung von LUNs oder Dateifreigaben mit fehlenden Parametern oder der Änderung der vorhandenen Parameter. 
---
= Ändern von Speicherworkloads mithilfe von APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Ändern von Speicher-Workloads besteht aus der Aktualisierung von LUNs oder Dateifreigaben mit fehlenden Parametern oder der Änderung der vorhandenen Parameter.

Dieser Workflow verwendet das Beispiel der Aktualisierung von Performance Service Levels für LUNs und Dateifreigaben.

[NOTE]
====
Der Workflow geht davon aus, dass die LUN oder Dateifreigabe mit Performance Service Levels bereitgestellt wurde.

====


[[modify-file-shares]]
== Ändern von Dateifreigaben

Beim Ändern einer Dateifreigabe können Sie die folgenden Parameter aktualisieren:

* Kapazität oder Größe.
* Online- oder Offline-Einstellung.
* Richtlinie zur Speichereffizienz.
* Leistungsservicelevel.
* Einstellungen der Zugriffskontrollliste (ACL).
* Richtlinieneinstellungen exportieren.  Sie können auch Exportrichtlinienparameter löschen und die standardmäßigen (leeren) Exportrichtlinienregeln für die Dateifreigabe wiederherstellen.


[NOTE]
====
Während eines einzelnen API-Laufs können Sie nur einen Parameter aktualisieren.

====
Dieses Verfahren beschreibt das Hinzufügen eines Performance-Servicelevels zu einer Dateifreigabe.  Sie können dasselbe Verfahren zum Aktualisieren aller anderen Dateifreigabeeigenschaften verwenden.

. Besorgen Sie sich den CIFS-Freigabe- oder NFS-Dateifreigabeschlüssel der Dateifreigabe, die Sie aktualisieren möchten.  Diese API fragt alle Dateifreigaben in Ihrem Rechenzentrum ab.  Überspringen Sie diesen Schritt, wenn Sie den Dateifreigabeschlüssel bereits kennen.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/file-shares`

|===
. Zeigen Sie die Details der Dateifreigabe an, indem Sie die folgende API mit dem erhaltenen Dateifreigabeschlüssel ausführen.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
Sehen Sie sich die Details der Dateifreigabe in der Ausgabe an.

+
[listing]
----
"assigned_performance_service_level": {
        "key": null,
        "name": "Unassigned",
        "peak_iops": null,
        "expected_iops": null,
        "_links": {}
      },
----
. Rufen Sie den Schlüssel für das Performance Service Level ab, das Sie dieser Dateifreigabe zuweisen möchten.  Derzeit ist ihm keine Richtlinie zugewiesen.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Leistungsservice-Levels
 a| 
ERHALTEN
 a| 
`/storage-provider/performance-service-levels`

|===
+
[NOTE]
====
Sie können die Details der systemdefinierten Performance Service Levels abrufen, indem Sie die `system_defined` Eingabeparameter zu `true` .  Rufen Sie aus der Ausgabe den Schlüssel des Performance Service Level ab, den Sie auf die Dateifreigabe anwenden möchten.

====
. Wenden Sie den Performance Service Level auf die Dateifreigabe an.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
PATCH
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
In der Eingabe müssen Sie nur den Parameter angeben, den Sie aktualisieren möchten, sowie den Dateifreigabeschlüssel.  In diesem Fall ist es der Schlüssel des Performance Service Levels.

+
*Beispiel-cURL*

+
[listing]
----
curl -X POST "https://<hostname>/api/storage-provider/file-shares"`-H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" -d
"{
\"performance_service_level\": { \"key\": \"1251e51b-069f-11ea-980d-fa163e82bbf2\" },
}"
----
+
Die JSON-Ausgabe zeigt ein Job-Objekt an, mit dem Sie überprüfen können, ob die Zugriffsendpunkte auf den Home- und Partnerknoten erfolgreich erstellt wurden.

. Überprüfen Sie mithilfe des in Ihrer Ausgabe angezeigten Jobobjektschlüssels, ob der Performance Service Level zur Dateifreigabe hinzugefügt wurde.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Verwaltungsserver
 a| 
ERHALTEN
 a| 
`/management-server/jobs/\{key}`

|===
+
Wenn Sie die ID des Job-Objekts abfragen, sehen Sie, ob die Dateifreigabe erfolgreich aktualisiert wurde.  Beheben Sie im Falle eines Fehlers den Fehler und führen Sie die API erneut aus.  Fragen Sie nach erfolgreicher Erstellung die Dateifreigabe ab, um das geänderte Objekt anzuzeigen:

+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
Sehen Sie sich die Details der Dateifreigabe in der Ausgabe an.

+
[listing]
----
"assigned_performance_service_level": {
        "key": "1251e51b-069f-11ea-980d-fa163e82bbf2",
        "name": "Value",
        "peak_iops": 75,
        "expected_iops": 75,
        "_links": {
            "self": {
                "href": "/api/storage-provider/performance-service-levels/1251e51b-069f-11ea-980d-fa163e82bbf2"
            }
        }
----




[[update-luns]]
== LUNs aktualisieren

Beim Aktualisieren einer LUN können Sie die folgenden Parameter ändern:

* Kapazität oder Größe
* Online- oder Offline-Einstellung
* Richtlinie zur Speichereffizienz
* Leistungsservicelevel
* LUN-Karte


[NOTE]
====
Während eines einzelnen API-Laufs können Sie nur einen Parameter aktualisieren.

====
Dieses Verfahren beschreibt das Hinzufügen eines Performance Service Levels zu einer LUN.  Sie können dasselbe Verfahren zum Aktualisieren jeder anderen LUN-Eigenschaft verwenden.

. Besorgen Sie sich den LUN-Schlüssel der LUN, die Sie aktualisieren möchten.  Diese API gibt Details zu allen LUNs in Ihrem Rechenzentrum zurück.  Überspringen Sie diesen Schritt, wenn Sie den LUN-Schlüssel bereits kennen.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/luns`

|===
. Zeigen Sie die Details der LUN an, indem Sie die folgende API mit dem LUN-Schlüssel ausführen, den Sie erhalten haben.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/luns/\{key}`

|===
+
Sehen Sie sich die Details der LUN in der Ausgabe an.  Sie können sehen, dass dieser LUN kein Performance-Service-Level zugewiesen ist.

+
*Beispiel für JSON-Ausgabe*

+
[listing]
----

  "assigned_performance_service_level": {
        "key": null,
        "name": "Unassigned",
        "peak_iops": null,
        "expected_iops": null,
        "_links": {}
      },
----
. Besorgen Sie sich den Schlüssel für das Performance Service Level, das Sie der LUN zuweisen möchten.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Leistungsservice-Levels
 a| 
ERHALTEN
 a| 
`/storage-provider/performance-service-levels`

|===
+
[NOTE]
====
Sie können die Details der systemdefinierten Performance Service Levels abrufen, indem Sie die `system_defined` Eingabeparameter zu `true` .  Ermitteln Sie aus der Ausgabe den Schlüssel des Performance Service Levels, den Sie auf die LUN anwenden möchten.

====
. Wenden Sie den Performance Service Level auf die LUN an.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
PATCH
 a| 
`/storage-provider/lun/\{key}`

|===
+
In der Eingabe müssen Sie nur den Parameter angeben, den Sie aktualisieren möchten, zusammen mit dem LUN-Schlüssel.  In diesem Fall ist es der Schlüssel des Performance Service Levels.

+
*Beispiel-cURL*

+
[listing]
----
curl -X PATCH "https://<hostname>/api/storage-provider/luns/7d5a59b3-953a-11e8-8857-00a098dcc959" -H "accept: application/json" -H "Content-Type: application/json" H "Authorization: Basic <Base64EncodedCredentials>" -d
"{ \"performance_service_level\": { \"key\": \"1251e51b-069f-11ea-980d-fa163e82bbf2\" }"
----
+
Die JSON-Ausgabe zeigt einen Job-Objektschlüssel an, mit dem Sie die von Ihnen aktualisierte LUN überprüfen können.

. Zeigen Sie die Details der LUN an, indem Sie die folgende API mit dem LUN-Schlüssel ausführen, den Sie erhalten haben.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/luns/\{key}`

|===
+
Sehen Sie sich die Details der LUN in der Ausgabe an.  Sie können sehen, dass dieser LUN das Performance Service Level zugewiesen ist.

+
*Beispiel für JSON-Ausgabe*

+
[listing]
----

     "assigned_performance_service_level": {
        "key": "1251e51b-069f-11ea-980d-fa163e82bbf2",
        "name": "Value",
        "peak_iops": 75,
        "expected_iops": 75,
        "_links": {
            "self": {
                "href": "/api/storage-provider/performance-service-levels/1251e51b-069f-11ea-980d-fa163e82bbf2"
            }
----

