---
permalink: api-automation/concept_manage_active_directory.html 
sidebar: sidebar 
keywords: manage, active, directory, mapping 
summary: Mit den hier aufgeführten APIs können Sie Active Directory-Zuordnungen auf der SVM verwalten, die für die Bereitstellung von CIFS-Freigaben auf den SVMs erforderlich sind.  Für die Zuordnung der SVMs zu ONTAP müssen Active Directory-Zuordnungen konfiguriert werden. 
---
= Verwalten der Active Directory-Zuordnung mithilfe von APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den hier aufgeführten APIs können Sie Active Directory-Zuordnungen auf der SVM verwalten, die für die Bereitstellung von CIFS-Freigaben auf den SVMs erforderlich sind.  Für die Zuordnung der SVMs zu ONTAP müssen Active Directory-Zuordnungen konfiguriert werden.



[[view-active-directory-mappings]]
== Anzeigen von Active Directory-Zuordnungen

Sie können die Konfigurationsdetails der Active Directory-Zuordnungen für eine SVM mithilfe der folgenden Methode anzeigen.  Um die Active Directory-Zuordnungen auf einer SVM anzuzeigen, müssen Sie den SVM-Schlüssel eingeben.  Um die Details einer bestimmten Zuordnung abzufragen, müssen Sie den Zuordnungsschlüssel eingeben.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/active-directories-mappings`

`/storage-provider/active-directories-mappings/\{key}`

|===


[[add-active-directory-mapping]]
== Active Directory-Zuordnung hinzufügen

Sie können Active Directory-Zuordnungen auf einer SVM mithilfe der folgenden Methode erstellen.  Sie müssen die Zuordnungsdetails als Eingabeparameter eingeben.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
POST
 a| 
`/storage-provider/active-directories-mappings`

|===