---
permalink: api-automation/concept_view_workloads.html 
sidebar: sidebar 
keywords: view, storage, workloads 
summary: 'Mit den hier aufgeführten APIs können Sie eine konsolidierte Liste der Speicher-Workloads für alle ONTAP Cluster in Ihrem Rechenzentrum anzeigen.  Die APIs bieten außerdem eine Übersicht über die Anzahl der in Ihrer Active IQ Unified Manager Umgebung bereitgestellten Speicher-Workloads sowie deren Kapazitäts- und Leistungsstatistiken (IOPS).' 
---
= Anzeigen von Speicherworkloads mithilfe von APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit den hier aufgeführten APIs können Sie eine konsolidierte Liste der Speicher-Workloads für alle ONTAP Cluster in Ihrem Rechenzentrum anzeigen.  Die APIs bieten außerdem eine Übersicht über die Anzahl der in Ihrer Active IQ Unified Manager Umgebung bereitgestellten Speicher-Workloads sowie deren Kapazitäts- und Leistungsstatistiken (IOPS).



[[view-storage-workloads]]
== Speicher-Workloads anzeigen

Mit der folgenden Methode können Sie alle Speicher-Workloads in allen Clustern Ihres Rechenzentrums anzeigen.  Informationen zum Filtern der Antwort basierend auf bestimmten Spalten finden Sie in der API-Referenzdokumentation, die in Ihrer Unified Manager-Instanz verfügbar ist.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/workloads`

|===


[[view-storage-workloads-summary]]
== Zusammenfassung der Speicherarbeitslasten anzeigen

Mit der folgenden Methode können Sie die genutzte Kapazität, die verfügbare Kapazität, die genutzten IOPS, die verfügbaren IOPS und die Anzahl der von jedem Performance Service Level verwalteten Speicher-Workloads ermitteln.  Die angezeigten Speicherarbeitslasten können für jede LUN, NFS-Dateifreigabe oder CIFS-Freigabe gelten.  Die API bietet eine Übersicht über Speicher-Workloads, eine Übersicht über die vom Unified Manager bereitgestellten Speicher-Workloads, eine Übersicht über das Rechenzentrum, eine Übersicht über den gesamten, genutzten und verfügbaren Speicherplatz und die IOPS im Rechenzentrum im Hinblick auf die zugewiesenen Performance Service Levels.  Die als Antwort auf diese API empfangenen Informationen werden verwendet, um das Dashboard in der Unified Manager-Benutzeroberfläche zu füllen.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Weg 


 a| 
Speicheranbieter
 a| 
ERHALTEN
 a| 
`/storage-provider/workloads-summary`

|===