---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: Die allgemeinen Arbeitsabläufe bieten Entwicklern von Clientanwendungen Beispiele dafür, wie Active IQ Unified Manager -APIs von einer Clientanwendung aufgerufen werden können, um allgemeine Speicherverwaltungsfunktionen auszuführen.  Dieser Abschnitt enthält einige dieser Beispiel-Workflows. 
---
= Gängige API-Workflows für die Speicherverwaltung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die allgemeinen Arbeitsabläufe bieten Entwicklern von Clientanwendungen Beispiele dafür, wie Active IQ Unified Manager -APIs von einer Clientanwendung aufgerufen werden können, um allgemeine Speicherverwaltungsfunktionen auszuführen.  Dieser Abschnitt enthält einige dieser Beispiel-Workflows.

Die Arbeitsabläufe beschreiben einige der häufig verwendeten Anwendungsfälle der Speicherverwaltung zusammen mit Beispielcodes, die Sie verwenden können.  Jede der Aufgaben wird mithilfe eines Workflow-Prozesses beschrieben, der aus einem oder mehreren API-Aufrufen besteht.



[[understand-the-api-calls-used-in-the-workflows]]
== Verstehen Sie die in den Workflows verwendeten API-Aufrufe

Sie können die Online-Dokumentationsseite Ihrer Unified Manager-Instanz anzeigen, die die Details jedes REST-API-Aufrufs enthält.  Dieses Dokument wiederholt nicht die Details der Online-Dokumentation.  Jeder in den Workflow-Beispielen in diesem Dokument verwendete API-Aufruf enthält nur die Informationen, die Sie benötigen, um den Aufruf auf der Dokumentationsseite zu finden. Nachdem Sie einen bestimmten API-Aufruf gefunden haben, können Sie die vollständigen Details des Aufrufs überprüfen, einschließlich der Eingabeparameter, Ausgabeformate, HTTP-Statuscodes und des Anfrageverarbeitungstyps.

Die folgenden Informationen sind für jeden API-Aufruf innerhalb eines Workflows enthalten, um das Auffinden des Aufrufs auf der Dokumentationsseite zu erleichtern:

* Kategorie: Die API-Aufrufe sind auf der Dokumentationsseite in funktional verwandte Bereiche oder Kategorien unterteilt. Um einen bestimmten API-Aufruf zu finden, scrollen Sie zum Ende der Seite und klicken Sie auf die entsprechende API-Kategorie.
* HTTP-Verb (Aufruf): Das HTTP-Verb identifiziert die an einer Ressource ausgeführte Aktion. Jeder API-Aufruf wird über ein einzelnes HTTP-Verb ausgeführt.
* Pfad: Der Pfad bestimmt die spezifische Ressource, auf die die Aktion im Rahmen der Ausführung eines Aufrufs angewendet wird. Die Pfadzeichenfolge wird an die Kern-URL angehängt, um die vollständige URL zur Identifizierung der Ressource zu bilden.

