---
permalink: api-automation/concept_job_api.html 
sidebar: sidebar 
keywords: jobs, view 
summary: Sie können die Jobs-API unter der Kategorie „Management-Server“ verwenden, um die Ausführungsdetails asynchroner Vorgänge anzuzeigen. 
---
= Anzeigen von Jobs und Systemdetails
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `jobs` API unter der `management-server` Kategorie, um die Ausführungsdetails asynchroner Vorgänge anzuzeigen.  Der `system` API unter der `management-server` Mit der Kategorie können Sie die Instanzdetails in Ihrer Active IQ Unified Manager Umgebung anzeigen.



[[view-jobs]]
== Jobs anzeigen

In Active IQ Unified Manager werden Vorgänge wie das Hinzufügen und Ändern von Ressourcen durch synchrone und asynchrone API-Aufrufe ausgeführt.  Aufrufe, die für die asynchrone Ausführung geplant sind, können durch ein für diesen Aufruf erstelltes Job-Objekt verfolgt werden.  Jedes Job-Objekt verfügt über einen eindeutigen Schlüssel zur Identifizierung.  Jedes Job-Objekt gibt die Job-Objekt-URI zurück, damit Sie auf den Job zugreifen und seinen Fortschritt verfolgen können.  Sie können diese API verwenden, um die Details jeder Ausführung abzurufen.

Mithilfe dieser API können Sie alle Jobobjekte für Ihr Rechenzentrum abfragen, einschließlich historischer Daten.  Wenn Sie alle Jobs abfragen, werden standardmäßig die Details der letzten 20 Jobs zurückgegeben, die über die Web-Benutzeroberfläche und die API-Schnittstelle ausgelöst wurden.  Verwenden Sie die integrierten Filter, um bestimmte Jobs anzuzeigen.  Sie können den Job-Schlüssel auch verwenden, um die Details eines bestimmten Jobs abzufragen und die nächsten Operationen für die Ressourcen auszuführen.

[cols="4*"]
|===
| Kategorie | HTTP-Verb | Weg | Beschreibung 


 a| 
Management-Server
 a| 
ERHALTEN
 a| 
`/management-server/jobs`
 a| 
Gibt die Auftragsdetails aller Aufträge zurück.  Ohne Sortierreihenfolge wird das zuletzt übermittelte Job-Objekt oben zurückgegeben.



 a| 
Management-Server
 a| 
ERHALTEN
 a| 
`/management-server/jobs/\{key}`

Geben Sie den Jobschlüssel des Jobobjekts ein, um die spezifischen Details dieses Jobs anzuzeigen.
 a| 
Gibt die Details des spezifischen Jobobjekts zurück.

|===


[[view-system-details]]
== Systemdetails anzeigen

Mithilfe der `/management-server/system` API können Sie die instanzspezifischen Details Ihrer Unified Manager-Umgebung abfragen.  Die API gibt Informationen zu den Produkten und Diensten zurück, beispielsweise die auf Ihrem System installierte Version von Unified Manager, UUID, Herstellername, Host-Betriebssystem sowie Name, Beschreibung und Status der auf der Unified Manager-Instanz ausgeführten Dienste.

[cols="4*"]
|===
| Kategorie | HTTP-Verb | Weg | Beschreibung 


 a| 
Management-Server
 a| 
ERHALTEN
 a| 
`/management-server/system`
 a| 
Zum Ausführen dieser API sind keine Eingabeparameter erforderlich.  Standardmäßig werden die Systemdetails der aktuellen Unified Manager-Instanz zurückgegeben.

|===