---
permalink: api-automation/reference_intended_audience_for_this_guide.html 
sidebar: sidebar 
keywords: audience, api, rest 
summary: Dieser Abschnitt richtet sich an Entwickler, die Anwendungen erstellen, die über REST-APIs mit der Active IQ Unified Manager -Software interagieren. 
---
= Zielgruppe für diesen Inhalt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die hier behandelten Themen richten sich an Entwickler, die Anwendungen erstellen, die über REST-APIs mit der Active IQ Unified Manager -Software interagieren.

Speicheradministratoren und -architekten können diese Informationen zu Rate ziehen, um ein grundlegendes Verständnis dafür zu erlangen, wie die Unified Manager REST-APIs zum Erstellen von Clientanwendungen zum Verwalten und Überwachen von NetApp -Speichersystemen verwendet werden können.

Sie sollten diese Informationen verwenden, wenn Sie den Speicheranbieter, den ONTAP Cluster und die Verwaltungs-APIs zur Verwaltung Ihres Speichers verwenden möchten.

[NOTE]
====
Sie müssen eine der folgenden Rollen innehaben: Operator, Speicheradministrator oder Anwendungsadministrator.  Sie müssen die IP-Adresse oder den vollqualifizierten Domänennamen des Unified Manager-Servers kennen, auf dem Sie die REST-APIs ausführen möchten.

====