---
permalink: reporting/task_search_for_scheduled_report.html 
sidebar: sidebar 
keywords: search, schedule, report 
summary: Sie können nach geplanten Berichten nach Name, Ansichtsname, Objekttyp oder Empfänger suchen. 
---
= Suchen nach einem geplanten Bericht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können nach geplanten Berichten nach Name, Ansichtsname, Objekttyp oder Empfänger suchen.

. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Berichtszeitpläne*.
. Verwenden Sie das Textfeld *Geplante Berichte suchen*.
+
[cols="2*"]
|===
| So finden Sie Berichte von ... | Versuchen ... 


 a| 
Zeitplanname
 a| 
Geben Sie einen Teil des Berichtszeitplannamens ein.



 a| 
Ansichtsname
 a| 
Geben Sie einen Teil des Berichtsansichtsnamens ein.  Standardansichten und benutzerdefinierte Ansichten werden in der Ansichtsliste angezeigt.



 a| 
Empfänger
 a| 
Geben Sie einen Teil der E-Mail-Adresse ein.



 a| 
Dateityp
 a| 
Geben Sie „PDF“, „CSV“ oder „XLSX“ ein.

|===
. Sie können auf eine Spaltenüberschrift klicken, um Berichte in aufsteigender oder absteigender Reihenfolge nach dieser Spalte zu sortieren, beispielsweise nach Zeitplanname oder Format.

