---
permalink: reporting/task_download_reports.html 
sidebar: sidebar 
keywords: download, reports 
summary: 'Sie können Berichte herunterladen und die Daten als CSV-Datei (Comma-Separated Values), Microsoft Excel-Datei (.XLSX) oder PDF-Datei auf einem lokalen Laufwerk oder einem Netzwerklaufwerk speichern.  Sie können CSV- und XLSX-Dateien mit Tabellenkalkulationsprogrammen wie Microsoft Excel und PDF-Dateien mit Leseprogrammen wie Adobe Acrobat öffnen.' 
---
= Berichte herunterladen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Berichte herunterladen und die Daten als CSV-Datei (Comma-Separated Values), Microsoft Excel-Datei (.XLSX) oder PDF-Datei auf einem lokalen Laufwerk oder einem Netzwerklaufwerk speichern.  Sie können CSV- und XLSX-Dateien mit Tabellenkalkulationsprogrammen wie Microsoft Excel und PDF-Dateien mit Leseprogrammen wie Adobe Acrobat öffnen.

.Schritte
. Klicken Sie auf die Schaltfläche *Berichte*, um den Bericht auf eine der folgenden Arten herunterzuladen:
+
[cols="2*"]
|===
| Wählen | Zu... 


 a| 
CSV herunterladen
 a| 
Speichern Sie den Bericht als CSV-Datei (Comma-Separated Values).



 a| 
PDF herunterladen
 a| 
Speichern Sie den Bericht als PDF-Datei.



 a| 
Excel herunterladen
 a| 
Speichern Sie den Bericht als Microsoft Excel-Datei (XLSX).

|===

