---
permalink: performance-checker/concept_understand_counter_charts.html 
sidebar: sidebar 
keywords: understand, counter, charts 
summary: Mithilfe der Diagramme im Bereich „Zählerdiagramme“ können Sie Leistungsdaten für das Stammobjekt und für Objekte anzeigen und vergleichen, die Sie aus dem Raster „Korrelierte Objekte“ hinzugefügt haben.  Dies kann Ihnen dabei helfen, Leistungstrends zu verstehen und Leistungsprobleme zu isolieren und zu beheben. 
---
= Zählerdiagramme verstehen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der Diagramme im Bereich „Zählerdiagramme“ können Sie Leistungsdaten für das Stammobjekt und für Objekte anzeigen und vergleichen, die Sie aus dem Raster „Korrelierte Objekte“ hinzugefügt haben.  Dies kann Ihnen dabei helfen, Leistungstrends zu verstehen und Leistungsprobleme zu isolieren und zu beheben.

Standardmäßig werden die Zählerdiagramme Ereignisse, Latenz, IOPS und MBps angezeigt.  Optionale Diagramme, die Sie anzeigen können, sind Auslastung, genutzte Leistungskapazität, verfügbare IOPS, IOPS/TB und Cache-Fehlerquote.  Darüber hinaus können Sie Gesamtwerte oder aufgeschlüsselte Werte für die Diagramme „Latenz“, „IOPS“, „MBps“ und „Verwendete Leistungskapazität“ anzeigen.

Der Performance Explorer zeigt standardmäßig bestimmte Zählerdiagramme an, unabhängig davon, ob das Speicherobjekt sie alle unterstützt oder nicht.  Wenn ein Zähler nicht unterstützt wird, ist das Zählerdiagramm leer und die Meldung `Not applicable for <object>` wird angezeigt.

Die Diagramme zeigen Leistungstrends für das Stammobjekt und für alle Objekte an, die Sie im Vergleichsbereich ausgewählt haben.  Die Daten in jedem Diagramm sind wie folgt angeordnet:

* *X-Achse*
+
Zeigt den angegebenen Zeitraum an.  Wenn Sie keinen Zeitraum angegeben haben, wird standardmäßig der vorangegangene 72-Stunden-Zeitraum verwendet.

* *Y-Achse*
+
Zeigt Zählereinheiten an, die für das bzw. die ausgewählte(n) Objekt(e) eindeutig sind.



Die Farben der Trendlinien entsprechen der Farbe des Objektnamens, wie er im Vergleichsbereich angezeigt wird.  Sie können Ihren Cursor über einen Punkt auf einer beliebigen Trendlinie positionieren, um Details zu Zeit und Wert für diesen Punkt anzuzeigen.

Wenn Sie einen bestimmten Zeitraum innerhalb eines Diagramms untersuchen möchten, können Sie eine der folgenden Methoden verwenden:

* Verwenden Sie die Schaltfläche *<*, um den Bereich „Zählerdiagramme“ auf die gesamte Seitenbreite zu erweitern.
* Verwenden Sie den Cursor (wenn er sich in eine Lupe verwandelt), um einen Teil des Zeitrahmens im Diagramm auszuwählen, um diesen Bereich zu fokussieren und zu vergrößern.  Sie können auf „Diagrammzoom zurücksetzen“ klicken, um das Diagramm auf den Standardzeitrahmen zurückzusetzen.
* Verwenden Sie die Schaltfläche *Zoom-Ansicht*, um ein großes Einzelzählerdiagramm anzuzeigen, das erweiterte Details und Schwellenwertindikatoren enthält.


[NOTE]
====
Gelegentlich treten Lücken in den Trendlinien auf.  Lücken bedeuten, dass Unified Manager entweder keine Leistungsdaten vom Speichersystem erfassen konnte oder dass Unified Manager möglicherweise ausgefallen war.

====