---
permalink: performance-checker/concept_understand_um_recommendations_to_tier_data_to_cloud.html 
sidebar: sidebar 
keywords: understand, unified manager, recommendations, tier, data, cloud 
summary: 'In der Ansicht „Leistung: Alle Volumes“ werden Informationen zur Größe der Benutzerdaten angezeigt, die auf dem inaktiven (kalten) Volume gespeichert sind.  In einigen Fällen identifiziert Unified Manager bestimmte Volumes, die von einer Auslagerung der inaktiven Daten in die Cloud-Ebene (Cloud-Anbieter oder StorageGRID) eines FabricPool-fähigen Aggregats profitieren würden.' 
---
= Informieren Sie sich über die Empfehlungen des Unified Managers zur Datenschichtung in der Cloud.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In der Ansicht „Leistung: Alle Volumes“ werden Informationen zur Größe der Benutzerdaten angezeigt, die auf dem inaktiven (kalten) Volume gespeichert sind.  In einigen Fällen identifiziert Unified Manager bestimmte Volumes, die von einer Auslagerung der inaktiven Daten in die Cloud-Ebene (Cloud-Anbieter oder StorageGRID) eines FabricPool-fähigen Aggregats profitieren würden.

[NOTE]
====
FabricPool wurde in ONTAP 9.2 eingeführt. Wenn Sie also eine Version der ONTAP -Software vor 9.2 verwenden, erfordert die Empfehlung von Unified Manager zum Tiering von Daten ein Upgrade Ihrer ONTAP -Software.  Darüber hinaus `*auto*` Die Tiering-Richtlinie wurde in ONTAP 9.4 eingeführt, und die `*all*` Die Tiering-Richtlinie wurde in ONTAP 9.6 eingeführt. Wenn also die Verwendung der Auto-Tiering-Richtlinie empfohlen wird, müssen Sie auf ONTAP 9.4 oder höher aktualisieren.

====
Die folgenden drei Felder in der Ansicht „Leistung: Alle Volumes“ bieten Informationen darüber, ob Sie die Festplattenauslastung Ihres Speichersystems verbessern und Speicherplatz auf der Leistungsebene sparen können, indem Sie inaktive Daten in die Cloudebene verschieben.

* *Stufenrichtlinie*
+
Die Tiering-Richtlinie bestimmt, ob die Daten auf dem Volume auf der Leistungsebene verbleiben oder ob einige der Daten von der Leistungsebene in die Cloudebene verschoben werden.

+
Der Wert in diesem Feld gibt die für das Volume festgelegte Tiering-Richtlinie an, auch wenn sich das Volume derzeit nicht auf einem FabricPool -Aggregat befindet.  Die Tiering-Richtlinie wird nur wirksam, wenn sich das Volume auf einem FabricPool -Aggregat befindet.

* *Kalte Daten*
+
Die kalten Daten zeigen die Größe der auf dem inaktiven (kalten) Volume gespeicherten Benutzerdaten an.

+
Ein Wert wird hier nur angezeigt, wenn Sie ONTAP 9.4 oder eine höhere Software verwenden, da dies erfordert, dass das Aggregat, auf dem das Volume bereitgestellt wird, über die `*inactive data reporting parameter*` eingestellt auf `*enabled*` und dass die Mindestanzahl an Kühltagen erreicht wurde (für Mengen, die die `*snapshot-only*` oder `*auto*` Tiering-Richtlinie).  Andernfalls wird der Wert als „N/A“ aufgeführt.

* *Cloud-Empfehlung*
+
Nachdem genügend Informationen zur Datenaktivität auf dem Datenträger erfasst wurden, kann Unified Manager feststellen, dass keine Aktion erforderlich ist oder dass Sie Speicherplatz auf der Leistungsebene sparen können, indem Sie inaktive Daten auf die Cloudebene verschieben.



[NOTE]
====
Das Feld „Cold Data“ wird alle 15 Minuten aktualisiert, das Feld „Cloud Recommendation“ jedoch alle 7 Tage, wenn die Cold Data-Analyse auf dem Datenträger durchgeführt wird.  Daher kann die genaue Menge kalter Daten zwischen den Feldern unterschiedlich sein.  Im Feld „Cloud-Empfehlung“ wird das Datum angezeigt, an dem die Analyse ausgeführt wurde.

====
Wenn die Berichterstattung über inaktive Daten aktiviert ist, zeigt das Feld „Kalte Daten“ die genaue Menge inaktiver Daten an.  Ohne die Funktion zur Meldung inaktiver Daten verwendet Unified Manager Leistungsstatistiken, um zu ermitteln, ob Daten auf einem Volume inaktiv sind.  Die Menge der inaktiven Daten wird in diesem Fall nicht im Feld „Cold Data“ angezeigt, sie wird jedoch angezeigt, wenn Sie mit dem Cursor über das Wort „Tier“ fahren, um die Cloud-Empfehlung anzuzeigen.

Die Cloud-Empfehlungen, die Sie sehen werden, sind:

* *Lernen*.  Es wurden nicht genügend Daten gesammelt, um eine Empfehlung abzugeben.
* *Stufe*.  Die Analyse hat ergeben, dass das Volume inaktive (kalte) Daten enthält und dass Sie das Volume so konfigurieren sollten, dass diese Daten in die Cloud-Ebene verschoben werden.  In einigen Fällen kann es erforderlich sein, dass Sie das Volume zuerst in ein FabricPool-fähiges Aggregat verschieben.  In anderen Fällen, in denen sich das Volume bereits auf einem FabricPool Aggregat befindet, müssen Sie lediglich die Tiering-Richtlinie ändern.
* *Keine Aktion*.  Entweder verfügt das Volume über sehr wenige inaktive Daten, das Volume ist bereits auf die Tiering-Richtlinie „auto“ auf einem FabricPool -Aggregat eingestellt oder das Volume ist ein Datenschutzvolume.  Dieser Wert wird auch angezeigt, wenn das Volume offline ist oder in einer MetroCluster -Konfiguration verwendet wird.


Um ein Volume zu verschieben oder die Volume-Tiering-Richtlinie oder die Einstellungen für die aggregierte Berichterstattung inaktiver Daten zu ändern, verwenden Sie ONTAP System Manager, die ONTAP CLI-Befehle oder eine Kombination dieser Tools.

Wenn Sie bei Unified Manager mit der Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ angemeldet sind, ist der Link „Volume konfigurieren“ in der Cloud-Empfehlung verfügbar, wenn Sie mit dem Cursor über das Wort „Tier“ fahren.  Klicken Sie auf diese Schaltfläche, um die Seite „Volumes“ im System Manager zu öffnen und die empfohlene Änderung vorzunehmen.
