---
permalink: performance-checker/concept_remove_inactive_volumes_and_luns.html 
sidebar: sidebar 
keywords: remove, inactive, volumes, luns 
summary: Wenn der aggregierte freie Speicherplatz als Problem identifiziert wurde, können Sie nach nicht verwendeten Volumes und LUNs suchen und diese aus dem Aggregat löschen.  Dies kann dazu beitragen, das Problem des geringen Speicherplatzes zu beheben. 
---
= Entfernen inaktiver Volumes und LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der aggregierte freie Speicherplatz als Problem identifiziert wurde, können Sie nach nicht verwendeten Volumes und LUNs suchen und diese aus dem Aggregat löschen.  Dies kann dazu beitragen, das Problem des geringen Speicherplatzes zu beheben.

Wenn ein Leistungsereignis auf einem Aggregat durch geringen Speicherplatz verursacht wird, gibt es einige Möglichkeiten, um festzustellen, welche Volumes und LUNs nicht mehr verwendet werden.

So identifizieren Sie nicht verwendete Volumes:

* Auf der Seite mit den Ereignisdetails enthält das Feld *Anzahl betroffener Objekte* einen Link, der die Liste der betroffenen Volumes anzeigt.
+
Klicken Sie auf den Link, um die Volumes in der Ansicht „Leistung: Alle Volumes“ anzuzeigen.  Von dort aus können Sie die betroffenen Volumes nach *IOPS* sortieren, um zu sehen, welche Volumes nicht aktiv waren.



So identifizieren Sie nicht verwendete LUNs:

. Notieren Sie auf der Seite „Ereignisdetails“ den Namen des Aggregats, auf dem das Ereignis aufgetreten ist.
. Klicken Sie im linken Navigationsbereich auf *Speicher* > *LUNs* und wählen Sie im Menü „Ansicht“ die Option *Leistung* > *Alle LUNs* aus.
. Klicken Sie auf *Filtern*, wählen Sie *Aggregat* aus dem linken Dropdown-Menü aus, geben Sie den Namen des Aggregats in das Textfeld ein und klicken Sie dann auf *Filter anwenden*.
. Sortieren Sie die resultierende Liste der betroffenen LUNs nach *IOPS*, um die LUNs anzuzeigen, die nicht aktiv sind.


Nachdem Sie die nicht verwendeten Volumes und LUNs identifiziert haben, können Sie diese Objekte mit dem ONTAP System Manager oder den ONTAP -Befehlen löschen.
