---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: Sie können Leistungsprobleme bei gespiegelten Workloads in einer MetroCluster -Konfiguration verhindern, indem Sie sicherstellen, dass die MetroCluster Konfiguration richtig eingerichtet ist.  Sie können die Workload-Leistung auch verbessern, indem Sie die Konfiguration ändern oder Software- oder Hardwarekomponenten aktualisieren. 
---
= Überprüfung der MetroCluster -Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Leistungsprobleme bei gespiegelten Workloads in einem MetroCluster über FC- und IP-Konfigurationen verhindern, indem Sie sicherstellen, dass die MetroCluster Konfiguration richtig eingerichtet ist.  Sie können die Workload-Leistung auch verbessern, indem Sie die Konfiguration ändern oder Software- oder Hardwarekomponenten aktualisieren.

Siehe https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster Dokumentation"] Anweisungen zum Einrichten der Cluster in der MetroCluster -Konfiguration, einschließlich der Fibre Channel (FC)-Switches, Kabel und Inter-Switch-Links (ISLs).  Es hilft Ihnen auch dabei, die MetroCluster -Software so zu konfigurieren, dass die lokalen und Remote-Cluster mit Spiegelvolumendaten kommunizieren können.  Spezifische Informationen zu Ihrem MetroCluster over IP-Setup finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installieren einer MetroCluster IP-Konfiguration"] .

Sie können Ihre MetroCluster Konfiguration mit den Anforderungen in vergleichen https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster Dokumentation"] um festzustellen, ob das Ändern oder Aktualisieren von Komponenten in Ihrer MetroCluster -Konfiguration die Workload-Leistung verbessern könnte.  Dieser Vergleich kann Ihnen bei der Beantwortung der folgenden Fragen helfen:

* Sind die Controller für Ihre Arbeitslasten geeignet?
* Müssen Sie Ihre ISL-Pakete auf eine größere Bandbreite aktualisieren, um einen höheren Durchsatz zu bewältigen?
* Können Sie die Buffer-to-Buffer-Credits (BBC) auf Ihren Switches anpassen, um die Bandbreite zu erhöhen?
* Wenn Ihre Workloads einen hohen Schreibdurchsatz auf Solid-State-Drive-Speicher (SSD) aufweisen, müssen Sie Ihre FC-zu-SAS-Brücken aktualisieren, um den Durchsatz zu bewältigen?


*Verwandte Informationen*

* Informationen zum Ersetzen oder Aktualisieren von MetroCluster Komponenten finden Sie im https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster Dokumentation"] .
* Informationen zum Upgrade von Controllern finden Sie unter https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Aktualisieren von Controllern in einer MetroCluster FC-Konfiguration mithilfe von Switchover und Switchback"] Und https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["Aktualisieren von Controllern in einer MetroCluster -IP-Konfiguration mithilfe von Switchover und Switchback"]

