---
permalink: performance-checker/concept_analyze_events_from_system_defined_performance_thresholds.html 
sidebar: sidebar 
keywords: analyze, events, system-defined, performance, thresholds 
summary: Aus systemdefinierten Leistungsschwellenwerten generierte Ereignisse weisen darauf hin, dass ein Leistungsindikator oder eine Reihe von Leistungsindikatoren für ein bestimmtes Speicherobjekt den Schwellenwert einer systemdefinierten Richtlinie überschritten hat.  Dies weist darauf hin, dass beim Speicherobjekt, beispielsweise einem Aggregat oder Knoten, ein Leistungsproblem vorliegt. 
---
= Analysieren Sie Ereignisse anhand systemdefinierter Leistungsschwellenwerte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aus systemdefinierten Leistungsschwellenwerten generierte Ereignisse weisen darauf hin, dass ein Leistungsindikator oder eine Reihe von Leistungsindikatoren für ein bestimmtes Speicherobjekt den Schwellenwert einer systemdefinierten Richtlinie überschritten hat.  Dies weist darauf hin, dass beim Speicherobjekt, beispielsweise einem Aggregat oder Knoten, ein Leistungsproblem vorliegt.

Auf der Seite „Ereignisdetails“ können Sie das Leistungsereignis analysieren und gegebenenfalls Korrekturmaßnahmen ergreifen, um die Leistung wieder auf den Normalwert zu bringen.

[NOTE]
====
Systemdefinierte Schwellenwertrichtlinien sind auf Cloud Volumes ONTAP, ONTAP Edge- oder ONTAP Select Systemen nicht aktiviert.

====