---
permalink: performance-checker/concept_add_disks_and_reallocate_data.html 
sidebar: sidebar 
keywords: add, disks, reallocate, data 
summary: Sie können einem Aggregat Festplatten hinzufügen, um die Speicherkapazität und die Leistung dieses Aggregats zu erhöhen.  Nach dem Hinzufügen der Datenträger werden Sie eine Verbesserung der Leseleistung erst feststellen, wenn Sie die Daten auf die hinzugefügten Datenträger neu verteilen. 
---
= Hinzufügen von Datenträgern und Neuzuweisung von Daten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einem Aggregat Festplatten hinzufügen, um die Speicherkapazität und die Leistung dieses Aggregats zu erhöhen.  Nach dem Hinzufügen der Datenträger werden Sie eine Verbesserung der Leseleistung erst feststellen, wenn Sie die Daten auf die hinzugefügten Datenträger neu verteilen.

Sie können diese Anweisungen verwenden, wenn Unified Manager aggregierte Ereignisse empfangen hat, die durch dynamische Schwellenwerte oder systemdefinierte Leistungsschwellenwerte ausgelöst wurden:

* Wenn Sie ein dynamisches Schwellenwertereignis erhalten haben, wird auf der Seite „Ereignisdetails“ das Clusterkomponentensymbol, das das konkurrierende Aggregat darstellt, rot hervorgehoben.
+
Unter dem Symbol steht in Klammern der Name des Aggregats, der das Aggregat identifiziert, zu dem Sie Festplatten hinzufügen können.

* Wenn Sie ein systemdefiniertes Schwellenwertereignis erhalten haben, wird auf der Seite „Ereignisdetails“ im Ereignisbeschreibungstext der Name des Aggregats aufgeführt, bei dem das Problem auftritt.
+
Sie können Festplatten hinzufügen und Daten auf diesem Aggregat neu zuweisen.



Die Festplatten, die Sie dem Aggregat hinzufügen, müssen bereits im Cluster vorhanden sein.  Wenn für den Cluster keine zusätzlichen Festplatten verfügbar sind, müssen Sie sich möglicherweise an Ihren Administrator wenden oder weitere Festplatten kaufen.  Sie können ONTAP System Manager oder die ONTAP -Befehle verwenden, um einem Aggregat Festplatten hinzuzufügen.

[NOTE]
====
Sie sollten Daten nur neu zuweisen, wenn Sie HDD- und Flash Pool-Aggregate verwenden.  Weisen Sie Daten auf SSD- oder FabricPool -Aggregaten nicht neu zu.

====