---
permalink: performance-checker/concept_understand_performance_events_and_alerts.html 
sidebar: sidebar 
keywords: understand, performance, events, alerts 
summary: Leistungsereignisse sind Benachrichtigungen, die Unified Manager automatisch generiert, wenn eine vordefinierte Bedingung eintritt oder wenn ein Leistungsindikatorwert einen Schwellenwert überschreitet.  Ereignisse helfen Ihnen, Leistungsprobleme in den überwachten Clustern zu erkennen. 
---
= Leistungsereignisse und Warnungen verstehen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Leistungsereignisse sind Vorfälle im Zusammenhang mit der Arbeitslastleistung auf einem Cluster.  Sie helfen Ihnen, Arbeitslasten mit langsamen Reaktionszeiten zu identifizieren.  Zusammen mit den gleichzeitig aufgetretenen Integritätsereignissen können Sie die Probleme ermitteln, die möglicherweise die langsamen Reaktionszeiten verursacht oder dazu beigetragen haben.

Wenn Unified Manager mehrere Vorkommen derselben Ereignisbedingung für dieselbe Clusterkomponente erkennt, behandelt er alle Vorkommen als ein einzelnes Ereignis und nicht als separate Ereignisse.

Sie können Warnmeldungen so konfigurieren, dass automatisch E-Mail-Benachrichtigungen gesendet werden, wenn Leistungsereignisse bestimmter Schweregrade auftreten.
