---
permalink: performance-checker/concept_performance_incident_analysis_for_metrocluster_configuration.html 
sidebar: sidebar 
keywords: performance, event, analysis, metrocluster, configuration 
summary: Sie können Unified Manager verwenden, um ein Leistungsereignis für eine MetroCluster -Konfiguration zu analysieren.  Sie können die mit dem Ereignis verbundenen Arbeitslasten ermitteln und die vorgeschlagenen Maßnahmen zur Lösung des Problems prüfen. 
---
= Leistungsereignisanalyse für eine MetroCluster -Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager verwenden, um ein Leistungsereignis für eine MetroCluster -Konfiguration zu analysieren.  Sie können die mit dem Ereignis verbundenen Arbeitslasten ermitteln und die vorgeschlagenen Maßnahmen zur Lösung des Problems prüfen.

Leistungsereignisse bei MetroCluster können auf übermäßige Arbeitslasten zurückzuführen sein, die die Interswitch-Links (ISLs) zwischen den Clustern überbeanspruchen, oder auf Probleme mit der Verbindungsintegrität.  Unified Manager überwacht jeden Cluster in einer MetroCluster -Konfiguration unabhängig, ohne Leistungsereignisse auf einem Partnercluster zu berücksichtigen.

Leistungsereignisse aus beiden Clustern in der MetroCluster -Konfiguration werden auch auf der Dashboard-Seite des Unified Managers angezeigt.  Sie können auch die Integritätsseiten von Unified Manager anzeigen, um die Integrität jedes Clusters zu überprüfen und ihre Beziehung anzuzeigen.
