---
permalink: performance-checker/concept_add_disks_and_perform_aggregate_layout_reconstruction.html 
sidebar: sidebar 
keywords: add, disks, perform, aggregate, layout, reconstruction 
summary: Sie können einem Aggregat Festplatten hinzufügen, um die Speicherkapazität und die Leistung dieses Aggregats zu erhöhen.  Nach dem Hinzufügen der Festplatten sehen Sie erst nach dem Neuaufbau des Aggregats eine Leistungsverbesserung. 
---
= Fügen Sie Datenträger hinzu und führen Sie eine Rekonstruktion des Gesamtlayouts durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einem Aggregat Festplatten hinzufügen, um die Speicherkapazität und die Leistung dieses Aggregats zu erhöhen.  Nach dem Hinzufügen der Festplatten sehen Sie erst nach dem Neuaufbau des Aggregats eine Leistungsverbesserung.

Wenn Sie auf der Seite „Ereignisdetails“ ein systemdefiniertes Schwellenwertereignis erhalten, wird im Ereignisbeschreibungstext der Name des Aggregats aufgeführt, bei dem das Problem auftritt.  Sie können Datenträger hinzufügen und Daten auf diesem Aggregat rekonstruieren.

Die Festplatten, die Sie dem Aggregat hinzufügen, müssen bereits im Cluster vorhanden sein.  Wenn für den Cluster keine zusätzlichen Festplatten verfügbar sind, müssen Sie sich möglicherweise an Ihren Administrator wenden oder weitere Festplatten kaufen.  Sie können ONTAP System Manager oder die ONTAP -Befehle verwenden, um einem Aggregat Festplatten hinzuzufügen.

https://www.netapp.com/pdf.html?item=/media/19675-tr-3838.pdf["Technischer Bericht 3838: Konfigurationshandbuch für Speichersubsysteme"^]
