---
permalink: performance-checker/reference_managed_objects_pane.html 
sidebar: sidebar 
keywords: managed, objects, pane 
summary: Der Bereich „Verwaltete Objekte“ auf der Registerkarte „Leistungsübersicht“ bietet eine Übersicht auf oberster Ebene über die Speicherobjekttypen und -anzahl für den Cluster.  In diesem Bereich können Sie den Status der Objekte in jedem Cluster verfolgen. 
---
= Bereich „Verwaltete Objekte“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Bereich „Verwaltete Objekte“ auf der Registerkarte „Leistungsübersicht“ bietet eine Übersicht auf oberster Ebene über die Speicherobjekttypen und -anzahl für den Cluster.  In diesem Bereich können Sie den Status der Objekte in jedem Cluster verfolgen.

Bei der Anzahl der verwalteten Objekte handelt es sich um Zeitpunktdaten aus dem letzten Erfassungszeitraum.  Im 15-Minuten-Takt werden neue Objekte entdeckt.

Wenn Sie auf die verknüpfte Nummer für einen beliebigen Objekttyp klicken, wird die Seite mit dem Objektleistungsinventar für diesen Objekttyp angezeigt.  Die Objektbestandsseite wird gefiltert, um nur die Objekte in diesem Cluster anzuzeigen.

Die verwalteten Objekte sind:

* *Knoten*
+
Ein physisches System in einem Cluster.

* *Aggregate*
+
Ein Satz mehrerer RAID-Gruppen (Redundant Array of Independent Disks), die zum Schutz und zur Bereitstellung als einzelne Einheit verwaltet werden können.

* *Anschlüsse*
+
Ein physischer Verbindungspunkt auf Knoten, der zum Verbinden mit anderen Geräten in einem Netzwerk verwendet wird.

* *Speicher-VMs*
+
Eine virtuelle Maschine, die Netzwerkzugriff über eindeutige Netzwerkadressen bereitstellt.  Ein SVM kann Daten aus einem anderen Namespace bereitstellen und ist getrennt vom Rest des Clusters verwaltbar.

* *Bände*
+
Eine logische Entität, die über eines oder mehrere der unterstützten Zugriffsprotokolle zugängliche Benutzerdaten enthält.  Die Zählung umfasst sowohl FlexVol Volumes als auch FlexGroup -Volumes; sie umfasst keine FlexGroup Bestandteile.

* *LUNs*
+
Die Kennung einer logischen Fibre Channel (FC)-Einheit oder einer logischen iSCSI-Einheit.  Eine logische Einheit entspricht normalerweise einem Speichervolumen und wird innerhalb eines Computerbetriebssystems als Gerät dargestellt.

* *Netzwerkschnittstellen*
+
Eine logische Netzwerkschnittstelle, die einen Netzwerkzugriffspunkt zu einem Knoten darstellt.  Die Zählung umfasst alle Schnittstellentypen.


