---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager bietet einige Standard-Schwellenwertrichtlinien, die die Clusterleistung überwachen und automatisch Ereignisse generieren.  Diese Richtlinien sind standardmäßig aktiviert und generieren Warn- oder Informationsereignisse, wenn die überwachten Leistungsschwellenwerte überschritten werden. 
---
= Arten systemdefinierter Richtlinien für Leistungsschwellenwerte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager bietet einige Standard-Schwellenwertrichtlinien, die die Clusterleistung überwachen und automatisch Ereignisse generieren.  Diese Richtlinien sind standardmäßig aktiviert und generieren Warn- oder Informationsereignisse, wenn die überwachten Leistungsschwellenwerte überschritten werden.

[NOTE]
====
Systemdefinierte Richtlinien für Leistungsschwellenwerte sind auf Cloud Volumes ONTAP, ONTAP Edge- oder ONTAP Select Systemen nicht aktiviert.

====
Wenn Sie unnötige Ereignisse von systemdefinierten Richtlinien für Leistungsschwellenwerte erhalten, können Sie die Ereignisse für einzelne Richtlinien auf der Seite „Ereigniseinrichtung“ deaktivieren.



[[cluster-threshold-policies]]
== Cluster-Schwellenwertrichtlinien

Die systemdefinierten Richtlinien für Cluster-Leistungsschwellenwerte werden standardmäßig jedem Cluster zugewiesen, der von Unified Manager überwacht wird:

* *Ungleichgewicht der Clusterlast*
+
Identifiziert Situationen, in denen ein Knoten mit einer viel höheren Last arbeitet als andere Knoten im Cluster und daher möglicherweise die Arbeitslastlatenzen beeinflusst.

+
Dies geschieht durch Vergleichen des Werts der genutzten Leistungskapazität für alle Knoten in einem Cluster, um festzustellen, ob ein Knoten den Schwellenwert von 30 % länger als 24 Stunden überschritten hat.  Dies ist ein Warnereignis.

* *Ungleichgewicht der Clusterkapazität*
+
Identifiziert Situationen, in denen ein Aggregat eine viel höhere genutzte Kapazität aufweist als andere Aggregate im Cluster und daher möglicherweise den für Vorgänge erforderlichen Speicherplatz beeinträchtigt.

+
Dies geschieht durch Vergleichen des verwendeten Kapazitätswerts für alle Aggregate im Cluster, um festzustellen, ob zwischen den Aggregaten ein Unterschied von 70 % besteht.  Dies ist ein Warnereignis.





[[node-threshold-policies]]
== Knotenschwellenwertrichtlinien

Die systemdefinierten Richtlinien für Knotenleistungsschwellenwerte werden standardmäßig jedem Knoten in den Clustern zugewiesen, die von Unified Manager überwacht werden:

* *Schwellenwert für genutzte Leistungskapazität überschritten*
+
Identifiziert Situationen, in denen ein einzelner Knoten über die Grenzen seiner Betriebseffizienz hinaus arbeitet und daher möglicherweise die Arbeitslastlatenzen beeinträchtigt.

+
Dies geschieht durch die Suche nach Knoten, die länger als 12 Stunden mehr als 100 % ihrer Leistungskapazität nutzen.  Dies ist ein Warnereignis.

* *Knoten-HA-Paar überbeansprucht*
+
Identifiziert Situationen, in denen Knoten in einem HA-Paar über die Grenzen der Betriebseffizienz des HA-Paares hinaus arbeiten.

+
Dies geschieht durch Betrachtung des Werts der genutzten Leistungskapazität für die beiden Knoten im HA-Paar.  Wenn die kombinierte Leistungskapazität der beiden Knoten länger als 12 Stunden 200 % übersteigt, wirkt sich ein Controller-Failover auf die Arbeitslastlatenzen aus.  Dies ist eine Informationsveranstaltung.

* *Knoten-Festplattenfragmentierung*
+
Identifiziert Situationen, in denen eine oder mehrere Festplatten in einem Aggregat fragmentiert sind, wodurch wichtige Systemdienste verlangsamt werden und möglicherweise die Arbeitslastlatenzen auf einem Knoten beeinträchtigt werden.

+
Dies geschieht durch die Betrachtung bestimmter Lese- und Schreibvorgangsverhältnisse über alle Aggregate auf einem Knoten hinweg.  Diese Richtlinie kann auch während der SyncMirror Neusynchronisierung ausgelöst werden oder wenn bei Festplattenbereinigungsvorgängen Fehler gefunden werden.  Dies ist ein Warnereignis.

+
[NOTE]
====
Die Richtlinie „Knoten-Festplattenfragmentierung“ analysiert nur HDD-Aggregate; Flash Pool-, SSD- und FabricPool -Aggregate werden nicht analysiert.

====




[[aggregate-threshold-policies]]
== Richtlinien für aggregierte Schwellenwerte

Die systemdefinierte Richtlinie für aggregierte Leistungsschwellenwerte wird standardmäßig jedem Aggregat in den von Unified Manager überwachten Clustern zugewiesen:

* *Aggregate-Festplatten überlastet*
+
Identifiziert Situationen, in denen ein Aggregat über den Grenzen seiner Betriebseffizienz arbeitet und dadurch möglicherweise die Arbeitslastlatenzen beeinträchtigt.  Diese Situationen werden dadurch identifiziert, dass nach Aggregaten gesucht wird, bei denen die Festplatten im Aggregat länger als 30 Minuten zu mehr als 95 % ausgelastet sind.  Diese Multicondition-Richtlinie führt dann die folgende Analyse durch, um die Ursache des Problems zu ermitteln:

+
** Wird auf einer Festplatte im Aggregat derzeit im Hintergrund eine Wartungsaktivität ausgeführt?
+
Zu den im Hintergrund ausgeführten Wartungsaktivitäten einer Festplatte zählen unter anderem die Festplattenrekonstruktion, die Festplattenbereinigung, die SyncMirror Neusynchronisierung und die Reparatur.

** Gibt es einen Kommunikationsengpass bei der Fibre-Channel-Verbindung des Festplattenregals?
** Ist im Aggregat zu wenig freier Speicherplatz vorhanden?  Ein Warnereignis wird für diese Richtlinie nur dann ausgegeben, wenn eine (oder mehrere) der drei untergeordneten Richtlinien ebenfalls als verletzt gelten.  Ein Leistungsereignis wird nicht ausgelöst, wenn nur die Festplatten im Aggregat zu mehr als 95 % ausgelastet sind.




[NOTE]
====
Die Richtlinie „Aggregate disks over-utilized“ analysiert reine HDD-Aggregate und Flash Pool-Aggregate (Hybrid); SSD- und FabricPool -Aggregate werden nicht analysiert.

====


[[workload-latency-threshold-policies]]
== Richtlinien für Workload-Latenzschwellenwerte

Die systemdefinierten Richtlinien für die Schwellenwerte für die Arbeitslastlatenz werden jeder Arbeitslast zugewiesen, für die eine konfigurierte Leistungsservicelevelrichtlinie mit einem definierten Wert für die „erwartete Latenz“ vorliegt:

* *Workload-Volumen/LUN-Latenzschwelle überschritten, wie durch Leistungs-Servicelevel definiert*
+
Identifiziert Volumes (Dateifreigaben) und LUNs, die ihr Limit für die „erwartete Latenz“ überschritten haben und die die Workload-Leistung beeinträchtigen.  Dies ist ein Warnereignis.

+
Dies geschieht durch die Suche nach Arbeitslasten, die in der letzten Stunde 30 % der Zeit den erwarteten Latenzwert überschritten haben.





[[qos-threshold-policies]]
== QoS-Schwellenwertrichtlinien

Die systemdefinierten QoS-Leistungsschwellenwertrichtlinien werden allen Workloads zugewiesen, für die eine ONTAP QoS-Richtlinie für den maximalen Durchsatz (IOPS, IOPS/TB oder MB/s) konfiguriert ist.  Unified Manager löst ein Ereignis aus, wenn der Workload-Durchsatzwert 15 % unter dem konfigurierten QoS-Wert liegt:

* *QoS Max IOPS oder MB/s-Schwellenwert*
+
Identifiziert Volumes und LUNs, die ihr QoS-Maximum an IOPS oder MB/s-Durchsatzlimit überschritten haben und die die Arbeitslastlatenz beeinträchtigen.  Dies ist ein Warnereignis.

+
Wenn einer Richtliniengruppe eine einzelne Arbeitslast zugewiesen wird, wird nach Arbeitslasten gesucht, die den in der zugewiesenen QoS-Richtliniengruppe definierten maximalen Durchsatzschwellenwert während jedes Erfassungszeitraums der vorherigen Stunde überschritten haben.

+
Wenn mehrere Workloads eine einzige QoS-Richtlinie gemeinsam nutzen, geschieht dies, indem die IOPS oder MB/s aller Workloads in der Richtlinie addiert und diese Summe mit dem Schwellenwert verglichen wird.

* *QoS Peak IOPS/TB oder IOPS/TB mit Blockgrößenschwelle*
+
Identifiziert Volumes, die ihr adaptives QoS-Spitzen-IOPS/TB-Durchsatzlimit (oder IOPS/TB mit Blockgrößenlimit) überschritten haben und die die Arbeitslastlatenz beeinträchtigen.  Dies ist ein Warnereignis.

+
Dies geschieht durch die Umwandlung des in der adaptiven QoS-Richtlinie definierten IOPS/TB-Spitzenschwellenwerts in einen QoS-Maximal-IOPS-Wert basierend auf der Größe jedes Volumes. Anschließend wird nach Volumes gesucht, die den QoS-Maximal-IOPS-Wert während jedes Leistungserfassungszeitraums der vorherigen Stunde überschritten haben.

+
[NOTE]
====
Diese Richtlinie wird nur auf Volumes angewendet, wenn der Cluster mit ONTAP 9.3 oder einer späteren Software installiert ist.

====
+
Wenn das Element „Blockgröße“ in der adaptiven QoS-Richtlinie definiert wurde, wird der Schwellenwert basierend auf der Größe jedes Volumes in einen maximalen QoS-MB/s-Wert umgewandelt.  Anschließend wird nach Volumes gesucht, die während jedes Leistungserfassungszeitraums der vorherigen Stunde den QoS-Maximum-MB/s-Wert überschritten haben.

+
[NOTE]
====
Diese Richtlinie wird nur auf Volumes angewendet, wenn der Cluster mit ONTAP 9.5 oder einer späteren Software installiert ist.

====

