---
permalink: performance-checker/task_view_performance_threshold_policies.html 
sidebar: sidebar 
keywords: view, performance, threshold, policies 
summary: Sie können alle derzeit definierten Richtlinien für Leistungsschwellenwerte auf der Seite „Leistungsschwellenwerte“ anzeigen. 
---
= Richtlinien für Leistungsschwellenwerte anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können alle derzeit definierten Richtlinien für Leistungsschwellenwerte auf der Seite „Leistungsschwellenwerte“ anzeigen.

Die Liste der Schwellenwertrichtlinien ist alphabetisch nach Richtliniennamen sortiert und enthält Richtlinien für alle Arten von Speicherobjekten.  Sie können auf eine Spaltenüberschrift klicken, um die Richtlinien nach dieser Spalte zu sortieren.  Wenn Sie nach einer bestimmten Richtlinie suchen, verwenden Sie die Filter- und Suchmechanismen, um die Liste der Schwellenwertrichtlinien zu verfeinern, die in der Inventarliste angezeigt werden.

Sie können den Cursor über den Richtliniennamen und den Bedingungsnamen bewegen, um die Konfigurationsdetails der Richtlinie anzuzeigen.  Darüber hinaus können Sie die bereitgestellten Schaltflächen verwenden, um benutzerdefinierte Schwellenwertrichtlinien zu erstellen, zu klonen, zu bearbeiten und zu löschen.

.Schritt
. Wählen Sie im linken Navigationsbereich *Ereignisschwellenwerte* > *Leistung* aus.
+
Die Seite „Leistungsschwellenwerte“ wird angezeigt.


