---
permalink: performance-checker/task_identify_bully_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, bully workloads, dynamic, performance, event 
summary: 'In Unified Manager können Sie ermitteln, welche Workloads die höchste Abweichung bei der Nutzung einer konkurrierenden Clusterkomponente aufweisen.  Durch die Identifizierung dieser Workloads können Sie besser verstehen, warum bestimmte Volumes im Cluster langsame Reaktionszeiten (Latenz) aufweisen.' 
---
= Identifizieren Sie die Arbeitsbelastung, die bei einem dynamischen Leistungsereignis auftritt.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager können Sie ermitteln, welche Workloads die höchste Abweichung bei der Nutzung einer konkurrierenden Clusterkomponente aufweisen.  Durch die Identifizierung dieser Workloads können Sie besser verstehen, warum bestimmte Volumes im Cluster langsame Reaktionszeiten (Latenz) aufweisen.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Es müssen neue, bestätigte oder veraltete dynamische Leistungsereignisse vorliegen.


Auf der Seite „Ereignisdetails“ wird eine Liste der benutzerdefinierten und systemdefinierten Arbeitslasten angezeigt, sortiert nach der höchsten Nutzung der Komponente oder der stärksten Auswirkung des Ereignisses.  Die Werte basieren auf den Spitzen, die Unified Manager bei der Erkennung und letzten Analyse des Ereignisses ermittelt hat.

.Schritte
. Zeigen Sie die Seite mit den Ereignisdetails an, um Informationen zum Ereignis anzuzeigen.
. Wählen Sie in den Diagrammen „Workload-Latenz“ und „Workload-Aktivität“ *Bully Workloads* aus.
. Bewegen Sie den Cursor über die Diagramme, um die wichtigsten benutzerdefinierten Bully-Arbeitslasten anzuzeigen, die sich auf die Komponente auswirken.

