---
permalink: performance-checker/task_identify_victim_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, victim workloads, dynamic, performance, event 
summary: 'In Unified Manager können Sie ermitteln, welche Volume-Workloads die höchste Abweichung in der Antwortzeit (Latenz) aufweisen, die durch eine konkurrierende Speicherkomponente verursacht wird.  Durch die Identifizierung dieser Workloads können Sie besser verstehen, warum die Clientanwendungen, die auf sie zugreifen, langsamer als gewöhnlich arbeiten.' 
---
= Identifizieren Sie die Arbeitslasten der Opfer, die an einem dynamischen Leistungsereignis beteiligt sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager können Sie ermitteln, welche Volume-Workloads die höchste Abweichung in der Antwortzeit (Latenz) aufweisen, die durch eine konkurrierende Speicherkomponente verursacht wird.  Durch die Identifizierung dieser Workloads können Sie besser verstehen, warum die Clientanwendungen, die auf sie zugreifen, langsamer als gewöhnlich arbeiten.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Es müssen neue, bestätigte oder veraltete dynamische Leistungsereignisse vorliegen.


Auf der Seite „Ereignisdetails“ wird eine Liste der benutzerdefinierten und systemdefinierten Workloads angezeigt, sortiert nach der größten Abweichung bei der Aktivität oder Nutzung der Komponente oder der am stärksten vom Ereignis betroffenen Komponente.  Die Werte basieren auf den Spitzen, die Unified Manager bei der Erkennung und letzten Analyse des Ereignisses ermittelt hat.

.Schritte
. Zeigen Sie die Seite *Ereignisdetails* an, um Informationen zum Ereignis anzuzeigen.
. Wählen Sie in den Diagrammen „Workload-Latenz“ und „Workload-Aktivität“ die Option „Opfer-Workloads“ aus.
. Bewegen Sie den Cursor über die Diagramme, um die wichtigsten benutzerdefinierten Workloads anzuzeigen, die sich auf die Komponente auswirken, sowie den Namen des betroffenen Workloads.

