---
permalink: performance-checker/task_move_workloads_to_different_aggregate.html 
sidebar: sidebar 
keywords: move, workloads, different, aggregate 
summary: Sie können Unified Manager verwenden, um ein Aggregat zu identifizieren, das weniger ausgelastet ist als das Aggregat, in dem sich Ihre Workloads derzeit befinden. Anschließend können Sie ausgewählte Volumes oder LUNs in dieses Aggregat verschieben.  Durch die Verschiebung leistungsstarker Workloads auf ein weniger ausgelastetes Aggregat oder ein Aggregat mit aktiviertem Flash-Speicher kann die Workload effizienter ausgeführt werden. 
---
= Verschieben von Workloads in ein anderes Aggregat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager verwenden, um ein Aggregat zu identifizieren, das weniger ausgelastet ist als das Aggregat, in dem sich Ihre Workloads derzeit befinden. Anschließend können Sie ausgewählte Volumes oder LUNs in dieses Aggregat verschieben.  Durch die Verschiebung leistungsstarker Workloads auf ein weniger ausgelastetes Aggregat oder ein Aggregat mit aktiviertem Flash-Speicher kann die Workload effizienter ausgeführt werden.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen den Namen des Aggregats aufgezeichnet haben, bei dem derzeit ein Leistungsproblem auftritt.
* Sie müssen das Datum und die Uhrzeit aufgezeichnet haben, zu der das Aggregat das Ereignis empfangen hat.
* Unified Manager muss mindestens einen Monat lang Leistungsdaten gesammelt und analysiert haben.


Mithilfe dieser Schritte können Sie die folgenden Ressourcen identifizieren, sodass Sie leistungsstarke Workloads auf ein weniger ausgelastetes Aggregat verschieben können:

* Die Aggregate auf demselben Cluster, die weniger genutzt werden
* Die leistungsstärksten Volumina auf der aktuellen Gesamtsumme


.Schritte
. Identifizieren Sie das Aggregat im Cluster, das am wenigsten genutzt wird:
+
.. Klicken Sie auf der Detailseite *Ereignis* auf den Namen des Clusters, auf dem sich das Aggregat befindet.
+
Die Clusterdetails werden auf der Leistungs-/Cluster-Startseite angezeigt.

.. Klicken Sie auf der Seite *Zusammenfassung* im Bereich *Verwaltete Objekte* auf *Aggregate*.
+
Die Liste der Aggregate in diesem Cluster wird angezeigt.

.. Klicken Sie auf die Spalte *Auslastung*, um die Aggregate nach der geringsten Auslastung zu sortieren.
+
Sie können auch die Aggregate identifizieren, die die größte *freie Kapazität* haben.  Dadurch wird eine Liste potenzieller Aggregate bereitgestellt, auf die Sie möglicherweise Arbeitslasten verschieben möchten.

.. Notieren Sie den Namen des Aggregats, in das Sie die Workloads verschieben möchten.


. Identifizieren Sie die leistungsstarken Volumes aus dem Aggregat, die das Ereignis empfangen haben:
+
.. Klicken Sie auf das Aggregat, bei dem das Leistungsproblem auftritt.
+
Die aggregierten Details werden auf der Seite „Performance/Aggregate Explorer“ angezeigt.

.. Wählen Sie im Auswahlfeld *Zeitbereich* die Option *Letzte 30 Tage* aus und klicken Sie dann auf *Bereich anwenden*.
+
Dadurch können Sie einen längeren Leistungsverlaufszeitraum als die standardmäßigen 72 Stunden anzeigen.  Sie möchten ein Volume verschieben, das regelmäßig viele Ressourcen nutzt, nicht nur in den letzten 72 Stunden.

.. Wählen Sie im Steuerelement *Anzeigen und Vergleichen* die Option *Volumes auf diesem Aggregat* aus.
+
Es wird eine Liste der FlexVol Volumes und FlexGroup Bestandteilvolumes in diesem Aggregat angezeigt.

.. Sortieren Sie die Volumes nach den höchsten MB/s und dann nach den höchsten IOPS, um die Volumes mit der höchsten Leistung anzuzeigen.
.. Notieren Sie die Namen der Volumes, die Sie in ein anderes Aggregat verschieben möchten.


. Verschieben Sie die Volumes mit hoher Leistung in das Aggregat, das Sie als Volume mit geringer Auslastung identifiziert haben.
+
Sie können den Verschiebevorgang mithilfe von ONTAP System Manager, OnCommand Workflow Automation, ONTAP -Befehlen oder einer Kombination dieser Tools durchführen.



Überprüfen Sie nach einigen Tagen, ob Sie von diesem Knoten oder Aggregat denselben Ereignistyp erhalten.
