---
permalink: performance-checker/task_configure_connection_between_um_server_and_external_data_provider.html 
sidebar: sidebar 
keywords: configuring, connection, unified manager, server, external, data, provider 
summary: Unified Manager kann Cluster-Leistungsdaten an einen externen Server senden.  Sie können den Typ der zu sendenden statistischen Daten und das Intervall angeben, in dem die Daten gesendet werden. 
---
= Konfigurieren einer Verbindung von einem Unified Manager-Server zu einem externen Datenanbieter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager kann Cluster-Leistungsdaten an einen externen Server senden.  Sie können den Typ der zu sendenden statistischen Daten und das Intervall angeben, in dem die Daten gesendet werden.

.Bevor Sie beginnen
* Sie müssen über eine Benutzer-ID verfügen, die zum Anmelden bei der Wartungskonsole des Unified Manager-Servers berechtigt ist.
* Sie benötigen folgende Informationen zum externen Datenanbieter:
+
** Servername oder IP-Adresse (IPv4 oder IPv6)
** Standardport des Servers (wenn nicht der Standardport 2003 verwendet wird)


* Sie müssen den Remote-Server und die Drittanbietersoftware so konfiguriert haben, dass sie statistische Daten vom Unified Manager-Server empfangen können.
* Sie müssen wissen, welche Statistikgruppe Sie senden möchten:
+
** PERFORMANCE_INDICATOR: Leistungsüberwachungsstatistiken
** RESOURCE_UTILIZATION: Ressourcennutzung und Leistungsüberwachungsstatistiken
** DRILL_DOWN: Alle Statistiken


* Sie müssen das Zeitintervall kennen, in dem Sie Statistiken übertragen möchten: 5, 10 oder 15 Minuten
+
Standardmäßig sammelt Unified Manager Statistiken in 5-Minuten-Intervallen.  Wenn Sie das Übertragungsintervall auf 10 (oder 15) Minuten einstellen, ist die Datenmenge, die bei jeder Übertragung gesendet wird, zwei- (oder dreimal) größer als bei Verwendung des Standardintervalls von 5 Minuten.

+
[NOTE]
====
Wenn Sie das Leistungserfassungsintervall des Unified Managers auf 10 oder 15 Minuten ändern, müssen Sie das Übertragungsintervall so ändern, dass es gleich oder größer als das Erfassungsintervall des Unified Managers ist.

====


Sie können eine Verbindung zwischen einem Unified Manager-Server und einem externen Datenanbieterserver konfigurieren.

.Schritte
. Melden Sie sich als Wartungsbenutzer bei der Wartungskonsole des Unified Manager-Servers an.
+
Die Eingabeaufforderungen der Unified Manager-Wartungskonsole werden angezeigt.

. Geben Sie in der Wartungskonsole die Nummer der Menüoption *Externer Datenanbieter* ein.
+
Das Menü „Externe Serververbindung“ wird angezeigt.

. Geben Sie die Nummer der Menüoption *Serververbindung hinzufügen/ändern* ein.
+
Die aktuellen Serververbindungsinformationen werden angezeigt.

. Wenn Sie dazu aufgefordert werden, geben Sie `*y*` , um fortzufahren.
. Geben Sie bei entsprechender Aufforderung die IP-Adresse oder den Namen des Zielservers und die Server-Port-Informationen ein (falls diese vom Standardport 2003 abweichen).
. Wenn Sie dazu aufgefordert werden, geben Sie `*y*` um zu überprüfen, ob die von Ihnen eingegebenen Informationen korrekt sind.
. Drücken Sie eine beliebige Taste, um zum Menü „Externe Serververbindung“ zurückzukehren.
. Geben Sie die Nummer der Menüoption *Serverkonfiguration ändern* ein.
+
Die aktuellen Serverkonfigurationsinformationen werden angezeigt.

. Wenn Sie dazu aufgefordert werden, geben Sie `*y*` , um fortzufahren.
. Geben Sie bei der entsprechenden Aufforderung den Typ der zu sendenden Statistiken sowie das Zeitintervall ein, in dem die Statistiken gesendet werden, und ob Sie die Übertragung der Statistiken jetzt aktivieren möchten:
+
|===
| Für.. | Eingeben... 


 a| 
Statistikgruppen-ID
 a| 
`*0*`- PERFORMANCE_INDICATOR (Standard)

`*1*`- RESSOURCENUTLIZATION

`*2*`- DRILL_DOWN



 a| 
Lieferanten-Tag
 a| 
Ein beschreibender Name für den Ordner, in dem die Statistiken auf dem externen Server gespeichert werden.  „`netapp-performance`“ ist der Standardname, Sie können jedoch einen anderen Wert eingeben.

Durch die Verwendung der Punktnotation können Sie eine hierarchische Ordnerstruktur definieren.  Zum Beispiel durch die Eingabe `*stats.performance.netapp*` Die Statistiken befinden sich unter *Statistiken* > *Leistung* > *NetApp*.



 a| 
Sendeintervall
 a| 
`*5*`(Standard), `*10*` , oder `*15*` Minuten



 a| 
Aktivieren/Deaktivieren
 a| 
`*0*`- Deaktivieren

`*1*`- Aktivieren (Standard)

|===
. Wenn Sie dazu aufgefordert werden, geben Sie `*y*` um zu überprüfen, ob die von Ihnen eingegebenen Informationen korrekt sind.
. Drücken Sie eine beliebige Taste, um zum Menü „Externe Serververbindung“ zurückzukehren.
. Typ `*x*` , um die Wartungskonsole zu verlassen.


Nachdem Sie die Verbindung konfiguriert haben, werden die ausgewählten Leistungsdaten im von Ihnen angegebenen Zeitintervall an den Zielserver gesendet.  Es dauert einige Minuten, bis die Messwerte im externen Tool angezeigt werden.  Möglicherweise müssen Sie Ihren Browser aktualisieren, um die neuen Metriken in der Metrikhierarchie anzuzeigen.
