---
permalink: performance-checker/task_identify_shark_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, shark workloads, involved, dynamic, performance, event 
summary: In Unified Manager können Sie ermitteln, welche Workloads die größte Abweichung bei der Nutzung einer umstrittenen Speicherkomponente aufweisen.  Durch die Identifizierung dieser Workloads können Sie feststellen, ob diese Workloads in einen weniger ausgelasteten Cluster verschoben werden sollten. 
---
= Identifizieren Sie die an einem dynamischen Leistungsereignis beteiligten Shark-Workloads
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager können Sie ermitteln, welche Workloads die größte Abweichung bei der Nutzung einer umstrittenen Speicherkomponente aufweisen.  Durch die Identifizierung dieser Workloads können Sie feststellen, ob diese Workloads in einen weniger ausgelasteten Cluster verschoben werden sollten.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Es gibt neue, anerkannte oder veraltete leistungsdynamische Ereignisse.


Auf der Seite „Ereignisdetails“ wird eine Liste der benutzerdefinierten und systemdefinierten Arbeitslasten angezeigt, sortiert nach der höchsten Nutzung der Komponente oder der stärksten Auswirkung des Ereignisses.  Die Werte basieren auf den Spitzen, die Unified Manager bei der Erkennung und letzten Analyse des Ereignisses ermittelt hat.

.Schritte
. Zeigen Sie die Seite *Ereignisdetails* an, um Informationen zum Ereignis anzuzeigen.
. Wählen Sie in den Diagrammen „Workload-Latenz“ und „Workload-Aktivität“ *Shark Workloads* aus.
. Bewegen Sie den Cursor über die Diagramme, um die wichtigsten benutzerdefinierten Workloads anzuzeigen, die sich auf die Komponente auswirken, sowie den Namen des Shark-Workloads.

