---
permalink: performance-checker/task_move_workloads_to_another_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, another, node, different, ha pair 
summary: Sie können Unified Manager verwenden, um ein Aggregat auf einem Knoten in einem anderen HA-Paar zu identifizieren, das weniger ausgelastet ist als das HA-Paar, auf dem Ihre Workloads derzeit ausgeführt werden.  Anschließend können Sie ausgewählte Volumes in Aggregate auf dem neuen HA-Paar verschieben.  Durch die Verschiebung leistungsstarker Workloads auf ein Aggregat auf einem weniger ausgelasteten Knoten können die Workloads auf beiden Knoten effizienter ausgeführt werden. 
---
= Verschieben Sie Workloads auf einen anderen Knoten in einem anderen HA-Paar
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager verwenden, um ein Aggregat auf einem Knoten in einem anderen HA-Paar zu identifizieren, das weniger ausgelastet ist als das HA-Paar, auf dem Ihre Workloads derzeit ausgeführt werden.  Anschließend können Sie ausgewählte Volumes in Aggregate auf dem neuen HA-Paar verschieben.  Durch die Verschiebung leistungsstarker Workloads auf ein Aggregat auf einem weniger ausgelasteten Knoten können die Workloads auf beiden Knoten effizienter ausgeführt werden.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Ihr Cluster muss aus mindestens zwei HA-Paaren bestehen. Sie können diesen Korrekturprozess nicht verwenden, wenn Ihr Cluster nur über ein HA-Paar verfügt.
* Sie müssen die Namen der beiden Knoten im HA-Paar aufgezeichnet haben, bei denen derzeit das Leistungsproblem auftritt.
* Sie müssen das Datum und die Uhrzeit aufgezeichnet haben, zu der die Knoten das Leistungsereignis empfangen haben.
* Unified Manager muss mindestens einen Monat lang Leistungsdaten gesammelt und analysiert haben.


Mithilfe dieser Schritte können Sie die folgenden Ressourcen identifizieren, sodass Sie leistungsstarke Workloads auf einen weniger ausgelasteten Knoten auf einem anderen HA-Paar verschieben können:

* Die Knoten in einem anderen HA-Paar im selben Cluster, die weniger genutzt werden
* Die Aggregate auf den neuen Knoten, die am wenigsten genutzt werden
* Die leistungsstärksten Volumes auf den aktuellen Knoten


.Schritte
. Identifizieren Sie die Knoten, die Teil eines anderen HA-Paares im selben Cluster sind:
+
.. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Cluster* und wählen Sie im Menü „Ansicht“ die Option *Leistung* > *Alle Cluster* aus.
+
Die Ansicht „Leistung: Alle Cluster“ wird angezeigt.

.. Klicken Sie auf die Zahl im Feld *Knotenanzahl* für den aktuellen Cluster.
+
Die Ansicht „Leistung: Alle Knoten“ wird angezeigt.

.. Notieren Sie die Namen der Knoten, die sich in anderen HA-Paaren befinden als das HA-Paar, bei dem derzeit das Leistungsproblem auftritt.


. Identifizieren Sie einen Knoten im neuen HA-Paar, der am wenigsten genutzt wird:
+
.. Klicken Sie auf die Spalte *Auslastung*, um die Knoten nach der geringsten Auslastung zu sortieren.
+
Sie können auch die Knoten identifizieren, die über die größte *freie Kapazität* verfügen.  Dadurch wird eine Liste potenzieller Knoten bereitgestellt, auf die Sie möglicherweise Arbeitslasten verschieben möchten.

.. Notieren Sie den Namen des Knotens, auf den Sie die Workloads verschieben möchten.


. Identifizieren Sie ein Aggregat auf dem neuen Knoten, das am wenigsten genutzt wird:
+
.. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Aggregate* und wählen Sie im Menü „Ansicht“ die Option *Leistung* > *Alle Aggregate* aus.
+
Die Ansicht „Leistung: Alle Aggregate“ wird angezeigt.

.. Klicken Sie auf *Filtern*, wählen Sie *Knoten* aus dem linken Dropdown-Menü, geben Sie den Namen des Knotens in das Textfeld ein und klicken Sie dann auf *Filter anwenden*.
+
Die Ansicht „Leistung: Alle Aggregate“ wird erneut mit der Liste der auf diesem Knoten verfügbaren Aggregate angezeigt.

.. Klicken Sie auf die Spalte *Auslastung*, um die Aggregate nach der geringsten Auslastung zu sortieren.
+
Sie können auch die Aggregate identifizieren, die die größte *freie Kapazität* haben.  Dadurch wird eine Liste potenzieller Aggregate bereitgestellt, auf die Sie möglicherweise Arbeitslasten verschieben möchten.

.. Notieren Sie den Namen des Aggregats, in das Sie die Workloads verschieben möchten.


. Identifizieren Sie die leistungsstarken Workloads der Knoten, die das Ereignis empfangen haben:
+
.. Kehren Sie zur Detailseite *Event* für das Event zurück.
.. Klicken Sie im Feld *Betroffene Volumes* auf den Link für die Anzahl der Volumes für den ersten Knoten.
+
Die Ansicht „Leistung: Alle Volumes“ wird mit einer gefilterten Liste der Volumes auf diesem Knoten angezeigt.

.. Klicken Sie auf die Spalte *Gesamtkapazität*, um die Volumes nach dem größten zugewiesenen Speicherplatz zu sortieren.
+
Dadurch wird eine Liste potenzieller Datenträger bereitgestellt, die Sie möglicherweise verschieben möchten.

.. Notieren Sie die Namen der Volumes, die Sie verschieben möchten, und die Namen der aktuellen Aggregate, auf denen sie sich befinden.
.. Führen Sie die Schritte 4c und 4d für den zweiten Knoten aus, der Teil dieses Ereignisses war, um mögliche Volumes zu identifizieren, die Sie ebenfalls von diesem Knoten verschieben möchten.


. Verschieben Sie die Volumes auf die Aggregate, die Ihrer Meinung nach auf dem neuen Knoten eine geringe Auslastung aufweisen.
+
Sie können den Verschiebevorgang mithilfe von ONTAP System Manager, OnCommand Workflow Automation, ONTAP -Befehlen oder einer Kombination dieser Tools durchführen.



Überprüfen Sie nach einigen Tagen, ob Sie von diesem Knoten oder Aggregat denselben Ereignistyp erhalten.
