---
permalink: performance-checker/task_create_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: create, user-defined, performance, threshold, policies 
summary: Sie erstellen Leistungsschwellenwertrichtlinien für Speicherobjekte, sodass Benachrichtigungen gesendet werden, wenn ein Leistungsindikator einen bestimmten Wert überschreitet.  Die Ereignisbenachrichtigung weist darauf hin, dass im Cluster ein Leistungsproblem vorliegt. 
---
= Erstellen Sie benutzerdefinierte Richtlinien für Leistungsschwellenwerte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie erstellen Leistungsschwellenwertrichtlinien für Speicherobjekte, sodass Benachrichtigungen gesendet werden, wenn ein Leistungsindikator einen bestimmten Wert überschreitet.  Die Ereignisbenachrichtigung weist darauf hin, dass im Cluster ein Leistungsproblem vorliegt.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ verfügen.

Sie erstellen Richtlinien für Leistungsschwellenwerte, indem Sie die Schwellenwerte auf der Seite „Richtlinie für Leistungsschwellenwerte erstellen“ eingeben.  Sie können neue Richtlinien erstellen, indem Sie alle Richtlinienwerte auf dieser Seite definieren, oder Sie können eine Kopie einer vorhandenen Richtlinie erstellen und die Werte in der Kopie ändern (dies wird als _Klonen_ bezeichnet).

Gültige Schwellenwerte sind 0,001 bis 10.000.000 für Zahlen, 0,001–100 für Prozentsätze und 0,001–200 für Prozentsätze der genutzten Leistungskapazität.

[NOTE]
====
Die aktuelle Version bietet Schwellenwerte, die Ereignisse senden, wenn ein Zählerwert die Schwellenwerteinstellung überschreitet.  Sie können keine Schwellenwerte festlegen, die Ereignisse senden, wenn ein Zählerwert unter eine Schwellenwerteinstellung fällt.

====
.Schritte
. Wählen Sie im linken Navigationsbereich *Ereignisschwellenwerte* > *Leistung* aus.
+
Die Seite „Leistungsschwellenwerte“ wird angezeigt.

. Klicken Sie auf die entsprechende Schaltfläche, je nachdem, ob Sie eine neue Richtlinie erstellen oder eine ähnliche Richtlinie klonen und die geklonte Version ändern möchten.
+
|===
| Zu... | Klicken... 


 a| 
Erstellen einer neuen Richtlinie
 a| 
*Erstellen*



 a| 
Klonen einer vorhandenen Richtlinie
 a| 
Wählen Sie eine vorhandene Richtlinie aus und klicken Sie auf *Klonen*

|===
+
Die Seite „Richtlinie für Leistungsschwellenwerte erstellen“ oder „Richtlinie für Leistungsschwellenwerte klonen“ wird angezeigt.

. Definieren Sie die Schwellenwertrichtlinie, indem Sie die Schwellenwerte für den Leistungsindikator angeben, die Sie für bestimmte Speicherobjekte festlegen möchten:
+
.. Wählen Sie den Speicherobjekttyp aus und geben Sie einen Namen und eine Beschreibung für die Richtlinie an.
.. Wählen Sie den zu verfolgenden Leistungsindikator aus und geben Sie die Grenzwerte an, die Warn- und kritische Ereignisse definieren.
+
Sie müssen mindestens eine Warnung oder einen kritischen Grenzwert definieren.  Sie müssen nicht beide Arten von Grenzwerten definieren.

.. Wählen Sie bei Bedarf einen sekundären Leistungsindikator aus und legen Sie die Grenzwerte für Warn- und kritische Ereignisse fest.
+
Die Einbeziehung eines sekundären Zählers erfordert, dass beide Zähler die Grenzwerte überschreiten, bevor der Schwellenwert überschritten und ein Ereignis gemeldet wird.  Mithilfe einer Kombinationsrichtlinie können nur bestimmte Objekte und Zähler konfiguriert werden.

.. Wählen Sie die Zeitdauer aus, für die die Grenzwerte überschritten werden müssen, damit ein Ereignis gesendet wird.


+
Wenn Sie eine vorhandene Richtlinie klonen, müssen Sie einen neuen Namen für die Richtlinie eingeben.

. Klicken Sie auf *Speichern*, um die Richtlinie zu speichern.
+
Sie werden zur Seite „Leistungsschwellenwerte“ zurückgeleitet.  Eine Erfolgsmeldung oben auf der Seite bestätigt, dass die Schwellenwertrichtlinie erstellt wurde, und bietet einen Link zur Inventarseite für diesen Objekttyp, sodass Sie die neue Richtlinie sofort auf Speicherobjekte anwenden können.



Wenn Sie die neue Schwellenwertrichtlinie jetzt auf Speicherobjekte anwenden möchten, können Sie auf den Link *Jetzt zu Objekttyp wechseln* klicken, um zur Inventarseite zu gelangen.
