---
permalink: storage-mgmt/task_create_and_edit_seps.html 
sidebar: sidebar 
keywords: create, edit, storage, efficiency, policies 
summary: Wenn die systemdefinierten Speichereffizienzrichtlinien nicht Ihren Workload-Anforderungen entsprechen, können Sie Ihre eigenen Speichereffizienzrichtlinien erstellen, die für Ihre Workloads optimiert sind. 
---
= Erstellen und Bearbeiten von Speichereffizienzrichtlinien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die systemdefinierten Speichereffizienzrichtlinien nicht Ihren Workload-Anforderungen entsprechen, können Sie Ihre eigenen Speichereffizienzrichtlinien erstellen, die für Ihre Workloads optimiert sind.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ verfügen.
* Der Name der Speichereffizienzrichtlinie muss eindeutig sein und Sie können die folgenden reservierten Schlüsselwörter nicht verwenden:
+
`High`, `Low` , `Unassigned` , `Learning` , `Idle` , `Default` , Und `None` .



Sie erstellen und bearbeiten benutzerdefinierte Speichereffizienzrichtlinien auf der Seite „Speichereffizienzrichtlinien“, indem Sie die Speichereffizienzmerkmale definieren, die Sie für die Anwendungen benötigen, die auf den Speicher zugreifen.

[NOTE]
====
Sie können eine Speichereffizienzrichtlinie nicht ändern, wenn sie derzeit einer Arbeitslast zugewiesen ist.

====
.Schritte
. Wählen Sie im linken Navigationsbereich unter *Einstellungen* *Richtlinien* > *Speichereffizienz* aus.
. Klicken Sie auf der Seite *Speichereffizienzrichtlinien* auf die entsprechende Schaltfläche, je nachdem, ob Sie eine neue Speichereffizienzrichtlinie erstellen oder eine vorhandene Speichereffizienzrichtlinie bearbeiten möchten.
+
|===
| Zu... | Befolgen Sie diese Schritte... 


 a| 
Erstellen einer neuen Speichereffizienzrichtlinie
 a| 
Klicken Sie auf *Hinzufügen*



 a| 
Bearbeiten einer vorhandenen Speichereffizienzrichtlinie
 a| 
Wählen Sie eine vorhandene Speichereffizienzrichtlinie aus und klicken Sie auf *Bearbeiten*

|===
+
Die Seite zum Hinzufügen oder Bearbeiten einer Speichereffizienzrichtlinie wird angezeigt.

. Passen Sie die Speichereffizienzrichtlinie an, indem Sie die Speichereffizienzmerkmale angeben, und klicken Sie dann auf *Senden*, um die Speichereffizienzrichtlinie zu speichern.


Sie können die neue oder geänderte Speichereffizienzrichtlinie auf Workloads (LUNs, NFS-Dateifreigaben, CIFS-Freigaben) von der Seite „Workloads“ oder beim Bereitstellen eines neuen Workloads anwenden.
