---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: 'Sie können auf der Seite „Workload bereitstellen“ LUNs erstellen, die CIFS/SMB- und NFS-Protokolle auf einem vorhandenen Cluster und einer Storage Virtual Machine (Storage-VM) unterstützen.' 
---
= Bereitstellen von LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können auf der Seite „Workload bereitstellen“ LUNs erstellen, die CIFS/SMB- und NFS-Protokolle auf einem vorhandenen Cluster und einer Storage Virtual Machine (Storage-VM) unterstützen.

.Bevor Sie beginnen
* Die Speicher-VM muss über Speicherplatz für die Bereitstellung der LUN verfügen.
* Sowohl iSCSI als auch FCP müssen auf der Speicher-VM aktiviert sein, auf der Sie die LUN erstellen.
* Um den Performance Service Level (PSL) und die Storage Efficiency Policy (SEP) für die Arbeitslast auszuwählen und zuzuweisen, müssen die Richtlinien erstellt worden sein, bevor Sie mit der Erstellung der Arbeitslast beginnen.


.Schritte
. Fügen Sie auf der Seite *Workload bereitstellen* den Namen der Workload hinzu, die Sie erstellen möchten, und wählen Sie dann den Cluster aus der verfügbaren Liste aus.
+
Basierend auf dem von Ihnen ausgewählten Cluster filtert das Feld *STORAGE VM* die verfügbaren Speicher-VMs für diesen Cluster.

. Wählen Sie aus der Liste die Speicher-VM aus, die die iSCSI- und FCP-Dienste unterstützt.
+
Basierend auf Ihrer Auswahl wird die SAN-Option im Abschnitt „Hostinformationen“ aktiviert.

. Weisen Sie im Abschnitt *Speicher und Optimierung* die Speicherkapazität und PSL sowie optional den SEP für die Arbeitslast zu.
+
Die Spezifikationen für das SEP werden der LUN zugewiesen und die Definitionen für das PSL werden beim Erstellen auf die Arbeitslast angewendet.

. Aktivieren Sie das Kontrollkästchen *Leistungsgrenzen erzwingen*, wenn Sie die zugewiesene PSL für die Arbeitslast erzwingen möchten.
+
Durch die Zuweisung einer PSL zu einer Arbeitslast wird sichergestellt, dass das Aggregat, auf dem die Arbeitslast erstellt wird, die in der jeweiligen Richtlinie definierten Leistungs- und Kapazitätsziele unterstützen kann.  Wenn beispielsweise einer Arbeitslast die PSL „Extreme Leistung“ zugewiesen wird, sollte das Aggregat, auf dem die Arbeitslast bereitgestellt werden soll, in der Lage sein, die Leistungs- und Kapazitätsziele der Richtlinie „Extreme Leistung“ zu unterstützen, beispielsweise SSD-Speicher.

+
[NOTE]
====
Wenn Sie dieses Kontrollkästchen nicht aktivieren, wird die PSL nicht auf die Arbeitslast angewendet und der Status der Arbeitslast wird auf dem Dashboard als `unassigned` .

====
. Wählen Sie die Option *SAN*.  Wenn die Option *SAN* nicht aktiviert ist, überprüfen Sie, ob die von Ihnen ausgewählte Speicher-VM iSCSI und FCP unterstützt.
. Wählen Sie das Host-Betriebssystem aus.
. Geben Sie die Hostzuordnung an, um den Zugriff der Initiatoren auf die LUN zu steuern.  Sie können vorhandene Initiatorgruppen (igroups) zuweisen oder neue igroups definieren und zuordnen.
+
[NOTE]
====
Wenn Sie beim Bereitstellen der LUN eine neue igroup erstellen, müssen Sie bis zum nächsten Erkennungszyklus (bis zu 15 Minuten) warten, bevor Sie sie verwenden können.  Es wird daher empfohlen, eine vorhandene Igroup aus der Liste der verfügbaren Igroups zu verwenden.

====
+
Wenn Sie eine neue Igroup erstellen möchten, wählen Sie die Schaltfläche *Neue Initiatorgruppe erstellen* und geben Sie die Informationen für die Igroup ein.

. Klicken Sie auf *Speichern*.
+
Die LUN wird der Liste der Speicher-Workloads hinzugefügt.


