---
permalink: storage-mgmt/task_edit_clusters.html 
sidebar: sidebar 
keywords: edit, clusters 
summary: Sie können die Einstellungen eines vorhandenen Clusters, wie etwa Hostname oder IP-Adresse, Benutzername, Kennwort und Port, mithilfe des Dialogfelds „Cluster bearbeiten“ ändern. 
---
= Cluster bearbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen eines vorhandenen Clusters, wie etwa Hostname oder IP-Adresse, Benutzername, Kennwort und Port, mithilfe des Dialogfelds „Cluster bearbeiten“ ändern.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

[NOTE]
====
Ab Unified Manager 9.7 können Cluster nur noch über HTTPS hinzugefügt werden.

====
.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Cluster-Setup*.
. Wählen Sie auf der Seite *Cluster-Setup* den Cluster aus, den Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Ändern Sie im Dialogfeld *Cluster bearbeiten* die Werte nach Bedarf.  + Wenn Sie die Details für einen zu Unified Manager hinzugefügten Cluster geändert haben, können Sie die Zertifikatsdetails für die gegenseitige TLS-Kommunikation basierend auf der ONTAP Version anzeigen.  Weitere Informationen zur ONTAP -Version finden Sie unterlink:../storage-mgmt/task_add_clusters.html["Zertifikate für die gegenseitige TLS-Kommunikation"] .  + Sie können die Zertifikatsdetails anzeigen, indem Sie auf *Zertifikatsdetails* klicken.  Wenn das Zertifikat abgelaufen ist, klicken Sie auf die Schaltfläche *Neu generieren*, um das neue Zertifikat einzubinden.
. Klicken Sie auf *Senden*.
. Klicken Sie im Dialogfeld „Host autorisieren“ auf *Zertifikat anzeigen*, um die Zertifikatsinformationen zum Cluster anzuzeigen.
. Klicken Sie auf *Ja*.


*Verwandte Informationen*

link:../config/task_add_users.html["Benutzer hinzufügen"]

link:../health-checker/task_view_cluster_list_and_details.html["Anzeigen der Clusterliste und Details"]
