---
permalink: storage-mgmt/task_view_and_add_vcenter_servers.html 
sidebar: sidebar 
keywords: view, add, vcenter, server 
summary: 'Um die Leistung der virtuellen Maschinen (VMs) anzuzeigen und Fehler zu beheben, müssen die zugehörigen vCenter-Server zu Ihrer Active IQ Unified Manager Instanz hinzugefügt werden.' 
---
= Anzeigen und Hinzufügen von vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Leistung der virtuellen Maschinen (VMs) anzuzeigen und Fehler zu beheben, müssen die zugehörigen vCenter-Server zu Ihrer Active IQ Unified Manager Instanz hinzugefügt werden.

.Bevor Sie beginnen
Stellen Sie vor dem Hinzufügen oder Anzeigen von vCenter-Servern Folgendes sicher:

* Sie kennen die Namen der vCenter-Server.
* Sie kennen die IP-Adresse des vCenter Servers und verfügen über die erforderlichen Anmeldeinformationen.  Die Anmeldeinformationen müssen von einem vCenter Server-Administrator oder einem Root-Benutzer mit schreibgeschütztem Zugriff auf vCenter Server stammen.
* Auf dem vCenter Server, den Sie hinzufügen möchten, wird vSphere 6.5 oder höher ausgeführt.
+

NOTE: Der Support von Unified Manager für VMware ESXi und vCenter Server ist in englischer und japanischer Sprache verfügbar.

* Die Datenerfassungseinstellung in vCenter Server ist auf die Statistikebene von `_Level 3_` , wodurch das erforderliche Maß an Metrikerfassung für alle überwachten Objekte sichergestellt wird.  Die Intervalldauer sollte `_5 minutes_` und der Speicherzeitraum sollte `_1 day_` .
+
Weitere Informationen finden Sie im Abschnitt „Datenerfassungsebenen“ des vSphere-Überwachungs- und Leistungshandbuchs in der VMware-Dokumentation.

* Für eine erfolgreiche Berechnung der Latenzwerte werden die Latenzwerte im vCenter Server in Millisekunden und nicht in Mikrosekunden konfiguriert.
* Beim Hinzufügen des Datenspeichers zu vCenter Server können Sie sowohl die IP-Adresse des Hosts als auch den vollqualifizierten Domänennamen (FQDN) verwenden.  Wenn Sie FQDN hinzufügen, stellen Sie sicher, dass der Domänenname vom Unified Manager-Server aufgelöst werden kann.  Stellen Sie beispielsweise bei einer Linux-Installation sicher, dass der Domänenname in der `/etc/resolv.conf` Datei.
* Die aktuelle Uhrzeit des vCenter Servers ist mit der Zeitzone des vCenter Servers synchronisiert.
* vCenter Server ist für eine erfolgreiche Erkennung erreichbar.
* Sie haben Lesezugriff auf das VMware SDK, wenn Sie den vCenter Server zu Unified Manager hinzufügen.  Dies ist für die Konfigurationsabfrage erforderlich.


Für jeden hinzugefügten und erkannten vCenter Server sammelt Unified Manager die Konfigurationsdaten, z. B. die vCenter Server- und ESXi-Serverdetails, die ONTAP Zuordnung, Datenspeicherdetails und die Anzahl der gehosteten VMs.  Darüber hinaus werden die Leistungskennzahlen der Komponenten erfasst.

.Schritte
. Gehen Sie zu *VMWARE* > *vCenter* und prüfen Sie, ob Ihr vCenter Server in der Liste verfügbar ist.
+
[NOTE]
====
Wenn Ihr vCenter Server nicht verfügbar ist, müssen Sie vCenter Server hinzufügen.

====
+
.. Klicken Sie auf *Hinzufügen*.
.. Fügen Sie die richtige IP-Adresse für vCenter Server hinzu und stellen Sie sicher, dass das Gerät erreichbar ist.
.. Fügen Sie den Benutzernamen und das Kennwort des Administrators oder Root-Benutzers mit schreibgeschütztem Zugriff auf vCenter Server hinzu.
.. Fügen Sie die benutzerdefinierte Portnummer hinzu, wenn Sie einen anderen Port als den Standardport 443 verwenden.
.. Klicken Sie auf *Speichern*.
+
Nach erfolgreicher Erkennung wird Ihnen ein Serverzertifikat angezeigt, das Sie akzeptieren müssen.

+
Wenn Sie das Zertifikat akzeptieren, wird vCenter Server zur Liste der verfügbaren vCenter Server hinzugefügt.  Das Hinzufügen des Geräts führt nicht zur Datenerfassung für die zugehörigen VMs und die Erfassung erfolgt in den geplanten Intervallen.



. Wenn Ihr vCenter Server auf der Seite *vCenters* verfügbar ist, überprüfen Sie seinen Status, indem Sie mit der Maus über das Feld *Status* fahren, um anzuzeigen, ob Ihr vCenter Server wie erwartet funktioniert oder ob eine Warnung oder ein Fehler vorliegt.
+
[NOTE]
====
Durch das Hinzufügen von vCenter Server können Sie die folgenden Status anzeigen.  Es kann jedoch bis zu einer Stunde dauern, bis die Leistungs- und Latenzdaten der entsprechenden VMs nach dem Hinzufügen von vCenter Server korrekt wiedergegeben werden.

====
+
** Grün: „Normal“, was bedeutet, dass vCenter Server erkannt wurde und Leistungsmetriken erfolgreich erfasst wurden
** Gelb: „Warnung“ (z. B. wenn die Statistikebene für vCenter Server nicht auf 3 oder höher eingestellt wurde, um Statistiken für jedes Objekt zu erhalten)
** Orange: „Fehler“ (weist auf interne Fehler hin, z. B. Ausnahme, Fehler bei der Konfigurationsdatenerfassung oder Nichterreichbarkeit des vCenter-Servers). Sie können auf das Spaltenanzeigesymbol (*Einblenden/Ausblenden*) klicken, um die Statusmeldung für einen vCenter-Server-Status anzuzeigen und das Problem zu beheben.


. Falls der vCenter-Server nicht erreichbar ist oder sich die Anmeldeinformationen geändert haben, bearbeiten Sie die vCenter-Serverdetails, indem Sie *vCenter* > *Bearbeiten* auswählen.
. Nehmen Sie die erforderlichen Änderungen auf der Seite *VMware vCenter Server bearbeiten* vor.
. Klicken Sie auf *Speichern*.


*Die Datenerfassung auf vCenter Server beginnt*

vCenter Server sammelt in Echtzeit 20-sekündige Leistungsdatenproben und fasst sie zu 5-Minuten-Proben zusammen.  Der Zeitplan für die Leistungsdatenerfassung von Unified Manager basiert auf den Standardeinstellungen von vCenter Server.  Unified Manager verarbeitet die vom vCenter Server erhaltenen 5-Minuten-Beispiele und berechnet einen stündlichen Durchschnitt der IOPS und Latenz für die virtuellen Festplatten, VMs und Hosts.  Für Datenspeicher berechnet Unified Manager einen stündlichen Durchschnitt der IOPS und Latenz aus von ONTAP erhaltenen Beispielen.  Diese Werte stehen zu jeder vollen Stunde zur Verfügung.  Die Leistungsmetriken sind nicht sofort nach dem Hinzufügen von vCenter Server verfügbar, sondern erst zu Beginn der nächsten Stunde.  Die Abfrage der Leistungsdaten beginnt nach Abschluss eines Zyklus der Konfigurationsdatenerfassung.

Zum Abfragen von vCenter Server-Konfigurationsdaten folgt Unified Manager demselben Zeitplan wie zum Erfassen von Cluster-Konfigurationsdaten.  Informationen zur Konfiguration von vCenter Server und zum Zeitplan für die Leistungsdatenerfassung finden Sie unter „Clusterkonfiguration und Aktivität zur Leistungsdatenerfassung“.

*Verwandte Informationen*

link:../performance-checker/concept_cluster_configuration_and_performance_data_collection_activity.html["Clusterkonfiguration und Leistungsdatenerfassungsaktivität"]
