---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: Active IQ Unified Manager unterstützt die Sicherung und Wiederherstellung mithilfe von NetApp Snapshots auf dem Windows-Betriebssystem mithilfe von LUN unter Verwendung des iSCSI-Protokolls. 
---
= Konfigurieren der Sicherung unter Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager unterstützt die Sicherung und Wiederherstellung mithilfe von NetApp Snapshots auf dem Windows-Betriebssystem mithilfe von LUN unter Verwendung des iSCSI-Protokolls.

Snapshot-basierte Sicherungen können durchgeführt werden, während alle Unified Manager-Dienste ausgeführt werden.  Ein konsistenter Status der Datenbank wird als Teil des Snapshots erfasst, da das Backup eine globale Lesesperre auf die gesamte Datenbank setzt, die alle gleichzeitigen Schreibvorgänge verhindert.  Damit Ihr unter Windows installiertes Unified Manager-System mithilfe von NetApp Snapshots Sicherungen und Wiederherstellungen durchführen kann, sollten Sie zunächst mithilfe der Wartungskonsole die Unified Manager-Sicherung auf Snapshot-Basis konfigurieren.

Bevor Sie Unified Manager zum Erstellen von Snapshot-Kopien konfigurieren, sollten Sie die folgenden Konfigurationsaufgaben durchführen.

* ONTAP Cluster konfigurieren
* Konfigurieren des Windows-Hostcomputers

