---
permalink: health-checker/concept_what_annotations_are.html 
sidebar: sidebar 
keywords: annotations 
summary: 'Eine Anmerkung ist eine Textzeichenfolge (der Name), die einer anderen Textzeichenfolge (dem Wert) zugewiesen wird.  Jedes Annotation-Name-Wert-Paar kann mithilfe von Annotationsregeln dynamisch mit Speicherobjekten verknüpft werden.  Wenn Sie Speicherobjekte mit vordefinierten Anmerkungen verknüpfen, können Sie die damit verbundenen Ereignisse filtern und anzeigen.  Sie können Anmerkungen auf Cluster, Volumes und virtuelle Speichermaschinen (SVMs) anwenden.' 
---
= Was sind Anmerkungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Anmerkung ist eine Textzeichenfolge (der Name), die einer anderen Textzeichenfolge (dem Wert) zugewiesen wird.  Jedes Annotation-Name-Wert-Paar kann mithilfe von Annotationsregeln dynamisch mit Speicherobjekten verknüpft werden.  Wenn Sie Speicherobjekte mit vordefinierten Anmerkungen verknüpfen, können Sie die damit verbundenen Ereignisse filtern und anzeigen.  Sie können Anmerkungen auf Cluster, Volumes und virtuelle Speichermaschinen (SVMs) anwenden.

Jeder Annotationsname kann mehrere Werte haben; jedes Name-Wert-Paar kann über Regeln mit einem Speicherobjekt verknüpft werden.

Sie können beispielsweise eine Annotation mit dem Namen „data-center“ mit den Werten „Boston“ und „Canada“ erstellen.  Anschließend können Sie die Annotation „`data-center`“ mit dem Wert „`Boston`“ auf Volume v1 anwenden.  Wenn für ein beliebiges Ereignis auf einem Volume v1, das mit „data-center“ gekennzeichnet ist, eine Warnung generiert wird, gibt die generierte E-Mail den Speicherort des Volumes, „Boston“, an, sodass Sie das Problem priorisieren und beheben können.
