---
permalink: health-checker/reference_volume_compliance_categories.html 
sidebar: sidebar 
keywords: volume, encryption, compliance, categories 
summary: Diese Tabelle beschreibt die Volume-Verschlüsselungsparameter, die Unified Manager auswertet, um zu bestimmen, ob die Daten auf Ihren Volumes ausreichend vor dem Zugriff durch nicht autorisierte Benutzer geschützt sind. 
---
= Volumen-Compliance-Kategorien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Tabelle beschreibt die Volume-Verschlüsselungsparameter, die Unified Manager auswertet, um zu bestimmen, ob die Daten auf Ihren Volumes ausreichend vor dem Zugriff durch nicht autorisierte Benutzer geschützt sind.

Beachten Sie, dass die Volume-Verschlüsselungsparameter keinen Einfluss darauf haben, ob der Cluster oder die Speicher-VM als konform gilt.

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
Softwareverschlüsselt
 a| 
Zeigt die Anzahl der Volumes an, die mit den Softwareverschlüsselungslösungen NetApp Volume Encryption (NVE) oder NetApp Aggregate Encryption (NAE) geschützt sind.



 a| 
Hardwareverschlüsselt
 a| 
Zeigt die Anzahl der Volumes an, die mit der Hardwareverschlüsselung NetApp Storage Encryption (NSE) geschützt sind.



 a| 
Software- und Hardwareverschlüsselung
 a| 
Zeigt die Anzahl der Volumes an, die sowohl durch Software- als auch durch Hardwareverschlüsselung geschützt sind.



 a| 
Nicht verschlüsselt
 a| 
Zeigt die Anzahl der nicht verschlüsselten Volumes an.

|===