---
permalink: health-checker/reference_cluster_compliance_categories.html 
sidebar: sidebar 
keywords: cluster compliance, categories 
summary: Diese Tabelle beschreibt die von Unified Manager ausgewerteten Parameter zur Cluster-Sicherheitskonformität, die NetApp -Empfehlung und ob der Parameter die Gesamtfeststellung beeinflusst, ob der Cluster den Anforderungen entspricht oder nicht. 
---
= Cluster-Compliance-Kategorien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Tabelle beschreibt die von Unified Manager ausgewerteten Parameter zur Cluster-Sicherheitskonformität, die NetApp -Empfehlung und ob der Parameter die Gesamtfeststellung beeinflusst, ob der Cluster den Anforderungen entspricht oder nicht.

Wenn sich in einem Cluster nicht konforme SVMs befinden, wirkt sich dies auf den Konformitätswert des Clusters aus.  Daher müssen Sie in einigen Fällen möglicherweise ein Sicherheitsproblem mit einem SVM beheben, bevor die Sicherheit Ihres Clusters als konform angesehen wird.

Beachten Sie, dass nicht jeder der unten aufgeführten Parameter bei allen Installationen angezeigt wird.  Wenn Sie beispielsweise keine Peering-Cluster haben oder AutoSupport auf einem Cluster deaktiviert haben, werden die Elemente „Cluster-Peering“ oder „AutoSupport HTTPS-Transport“ auf der UI-Seite nicht angezeigt.

[cols="4*"]
|===
| Parameter | Beschreibung | Empfehlung | Beeinflusst die Cluster-Compliance 


 a| 
Globales FIPS
 a| 
Gibt an, ob der Konformitätsmodus Global FIPS (Federal Information Processing Standard) 140-2 aktiviert oder deaktiviert ist.  Wenn FIPS aktiviert ist, sind TLSv1 und SSLv3 deaktiviert und nur TLSv1.1 und TLSv1.2 sind zulässig.
 a| 
Ermöglicht
 a| 
Ja



 a| 
Telnet
 a| 
Gibt an, ob der Telnet-Zugriff auf das System aktiviert oder deaktiviert ist. NetApp empfiehlt Secure Shell (SSH) für sicheren Fernzugriff.
 a| 
Deaktiviert
 a| 
Ja



 a| 
Unsichere SSH-Einstellungen
 a| 
Gibt an, ob SSH unsichere Chiffren verwendet, beispielsweise Chiffren, die mit *cbc beginnen.
 a| 
Nein
 a| 
Ja



 a| 
Login-Banner
 a| 
Gibt an, ob das Anmeldebanner für Benutzer, die auf das System zugreifen, aktiviert oder deaktiviert ist.
 a| 
Ermöglicht
 a| 
Ja



 a| 
Cluster-Peering
 a| 
Gibt an, ob die Kommunikation zwischen Peering-Clustern verschlüsselt oder unverschlüsselt ist.  Damit dieser Parameter als konform gilt, muss die Verschlüsselung sowohl auf dem Quell- als auch auf dem Zielcluster konfiguriert sein.
 a| 
Verschlüsselt
 a| 
Ja



 a| 
Netzwerkzeitprotokoll
 a| 
Gibt an, ob der Cluster über einen oder mehrere konfigurierte NTP-Server verfügt.  Aus Redundanzgründen und für einen optimalen Service empfiehlt NetApp , dem Cluster mindestens drei NTP-Server zuzuordnen.
 a| 
Konfiguriert
 a| 
Ja



 a| 
OCSP
 a| 
Ab Version 9.14.1 bietet Active IQ Unified Manager Statusinformationen zum Online Certificate Status Protocol (OCSP) auf der Ebene der Storage Virtual Machine (SVM, früher als Vserver bezeichnet).  Dies bedeutet, dass die OCSP-Validierung auf alle SSL/TLS-Verbindungen zum SVM angewendet wird und die Integrität und Gültigkeit der in diesen Verbindungen verwendeten Zertifikate gewährleistet.
 a| 
Ermöglicht
 a| 
Nein



 a| 
Remote-Audit-Protokollierung
 a| 
Gibt an, ob die Protokollweiterleitung (Syslog) verschlüsselt oder unverschlüsselt ist.
 a| 
Verschlüsselt
 a| 
Ja



 a| 
AutoSupport HTTPS-Transport
 a| 
Gibt an, ob HTTPS als Standardtransportprotokoll zum Senden von AutoSupport -Nachrichten an den NetApp Support verwendet wird.
 a| 
Ermöglicht
 a| 
Ja



 a| 
Standard-Administratorbenutzer
 a| 
Gibt an, ob der Standardadministratorbenutzer (integriert) aktiviert oder deaktiviert ist.  NetApp empfiehlt, alle nicht benötigten integrierten Konten zu sperren (deaktivieren).
 a| 
Deaktiviert
 a| 
Ja



 a| 
SAML-Benutzer
 a| 
Gibt an, ob SAML konfiguriert ist.  SAML ermöglicht Ihnen die Konfiguration der Multi-Faktor-Authentifizierung (MFA) als Anmeldemethode für Single Sign-On.
 a| 
Nein
 a| 
Nein



 a| 
Active Directory-Benutzer
 a| 
Gibt an, ob Active Directory konfiguriert ist.  Active Directory und LDAP sind die bevorzugten Authentifizierungsmechanismen für Benutzer, die auf Cluster zugreifen.
 a| 
Nein
 a| 
Nein



 a| 
LDAP-Benutzer
 a| 
Gibt an, ob LDAP konfiguriert ist.  Active Directory und LDAP sind die bevorzugten Authentifizierungsmechanismen für Benutzer, die Cluster gegenüber lokalen Benutzern verwalten.
 a| 
Nein
 a| 
Nein



 a| 
Zertifikatsbenutzer
 a| 
Gibt an, ob ein Zertifikatsbenutzer für die Anmeldung beim Cluster konfiguriert ist.
 a| 
Nein
 a| 
Nein



 a| 
Lokale Benutzer
 a| 
Gibt an, ob lokale Benutzer für die Anmeldung beim Cluster konfiguriert sind.
 a| 
Nein
 a| 
Nein



 a| 
Remote-Shell
 a| 
Gibt an, ob RSH aktiviert ist.  Aus Sicherheitsgründen sollte RSH deaktiviert werden.  Für den sicheren Fernzugriff wird die Secure Shell (SSH) bevorzugt.
 a| 
Deaktiviert
 a| 
Ja



 a| 
MD5 im Einsatz
 a| 
Gibt an, ob ONTAP Benutzerkonten die weniger sichere MD5-Hash-Funktion verwenden.  Die Migration von MD5-gehashten Benutzerkonten zur sichereren kryptografischen Hashfunktion wie SHA-512 wird bevorzugt.
 a| 
Nein
 a| 
Ja



 a| 
Zertifikatsausstellertyp
 a| 
Gibt den Typ des verwendeten digitalen Zertifikats an.
 a| 
CA-signiert
 a| 
Nein

|===