---
permalink: health-checker/reference_description_of_cluster_object_windows_and_dialog_boxes.html 
sidebar: sidebar 
keywords: description, cluster, object, windows, dialog boxes 
summary: Sie können alle Ihre Cluster und Clusterobjekte auf der jeweiligen Speicherobjektseite anzeigen.  Sie können die Details auch auf der entsprechenden Detailseite des Speicherobjekts anzeigen.  Sie können die Benutzeroberfläche des System Managers jetzt aus den folgenden Abschnitten SPEICHER und SCHUTZ des INVENTARS starten. 
---
= Beschreibung der Clusterobjektfenster und Dialogfelder
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können alle Ihre Cluster und Clusterobjekte auf der jeweiligen Speicherobjektseite anzeigen.  Sie können die Details auch auf der entsprechenden Detailseite des Speicherobjekts anzeigen.  Sie können die Benutzeroberfläche des System Managers jetzt aus den folgenden Abschnitten SPEICHER und SCHUTZ des INVENTARS starten.

* Seiten „Cluster-Inventar“, „Cluster-Integrität“ und „Cluster-Leistung“
* Seiten „Aggregatinventar“, „Aggregatzustand“ und „Aggregatleistung“
* Seiten „Volume-Inventar“, „Volume-Zustand“ und „Volume-Leistung“
* Seiten „Knoteninventar“ und „Knotenleistung“
* Seiten „StorageVM-Inventar“, „StorageVM-Integrität“ und „StorageVM-Leistung“
* Schutzbeziehungsseiten

