---
permalink: health-checker/task_migrate_um_virtual_appliance_to_rhel_system.html 
sidebar: sidebar 
keywords: unified manager, migrate, virtual, appliance, linux system 
summary: Sie können ein Dump-Backup der MySQL-Datenbank von Unified Manager von einer virtuellen Appliance auf einem Red Hat Enterprise Linux-System wiederherstellen, wenn Sie das Host-Betriebssystem ändern möchten, auf dem Unified Manager ausgeführt wird. 
---
= Migrieren einer virtuellen Unified Manager-Appliance auf ein Linux-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Dump-Backup der MySQL-Datenbank von Unified Manager von einer virtuellen Appliance auf einem Red Hat Enterprise Linux-System wiederherstellen, wenn Sie das Host-Betriebssystem ändern möchten, auf dem Unified Manager ausgeführt wird.

.Bevor Sie beginnen
* Auf der virtuellen Appliance:
+
** Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
** Für den Wiederherstellungsvorgang müssen Sie den Namen des Unified Manager-Wartungsbenutzers kennen.


* Auf dem Linux-System:
+
** Sie müssen Unified Manager auf einem Linux-Server installiert haben, indem Sie die Anweisungen inlink:../install-linux/concept_install_unified_manager_on_rhel.html["Installieren von Unified Manager auf Linux-Systemen"] .
** Die Version von Unified Manager auf diesem Server muss mit der Version auf der virtuellen Appliance übereinstimmen, von der Sie die Sicherungsdatei verwenden.
** Starten Sie nach der Installation nicht die Benutzeroberfläche und konfigurieren Sie keine Cluster, Benutzer oder Authentifizierungseinstellungen auf dem Linux-System.  Die Sicherungsdatei füllt diese Informationen während des Wiederherstellungsvorgangs.
** Sie müssen über die Root-Benutzeranmeldeinformationen für den Linux-Host verfügen.




Diese Schritte beschreiben, wie Sie eine Sicherungsdatei auf der virtuellen Appliance erstellen, die Sicherungsdateien auf Red Hat Enterprise Linux kopieren und dann die Datenbanksicherung auf dem neuen System wiederherstellen.

.Schritte
. Klicken Sie auf der virtuellen Appliance auf *Verwaltung* > *Datenbanksicherung*.
. Klicken Sie auf der Seite *Datenbanksicherung* auf *Sicherungseinstellungen*.
. Ändern Sie den Sicherungspfad in /jail/support.
. Wählen Sie im Abschnitt „Zeitplan“ die Option „Täglich geplant“ aus und geben Sie eine Zeit ein, die einige Minuten nach der aktuellen Zeit liegt, damit die Sicherung in Kürze erstellt wird.
. Klicken Sie auf *Übernehmen*.
. Warten Sie einige Stunden, bis die Sicherung erstellt wurde.
+
Eine vollständige Sicherung kann über 1 GB groß sein und drei bis vier Stunden dauern.

. Melden Sie sich als Root-Benutzer beim Linux-Host an, auf dem Unified Manager installiert ist, und kopieren Sie die Sicherungsdateien mithilfe von SCP von /support auf die virtuelle Appliance.`root@<rhel_server>:/# scp -r admin@<vapp_server_ip_address>:/support/* .`
+
`root@ocum_rhel-21:/# scp -r admin@10.10.10.10:/support/* .`

+
Stellen Sie sicher, dass Sie die .7z-Sicherungsdatei und alle .7z-Repository-Dateien in das Unterverzeichnis /database-dumps-repo kopiert haben.

. Stellen Sie die Sicherung in der Eingabeaufforderung wieder her: `um backup restore -f /<backup_file_path>/<backup_file_name>`
+
`um backup restore -f /UM_9.7.N151113.1348_backup_unix_02-12-2019-04-16.7z`

. Melden Sie sich nach Abschluss des Wiederherstellungsvorgangs bei der Unified Manager-Web-Benutzeroberfläche an.


Sie sollten die folgenden Aufgaben ausführen:

* Generieren Sie ein neues HTTPS-Sicherheitszertifikat und starten Sie den Unified Manager-Server neu.
* Ändern Sie den Sicherungspfad auf die Standardeinstellung für Ihr Linux-System (/data/ocum-backup) oder auf einen neuen Pfad Ihrer Wahl, da auf dem Linux-System kein Pfad /jail/support vorhanden ist.
* Konfigurieren Sie beide Seiten Ihrer Workflow Automation-Verbindung neu, wenn WFA verwendet wird.
* Konfigurieren Sie die SAML-Authentifizierungseinstellungen neu, wenn Sie SAML verwenden.


Nachdem Sie überprüft haben, dass auf Ihrem Linux-System alles wie erwartet läuft, können Sie die virtuelle Unified Manager-Appliance herunterfahren und entfernen.
