---
permalink: health-checker/task_configure_conditions_for_annotation_rules.html 
sidebar: sidebar 
keywords: unified manager, configure, conditions, annotation rules 
summary: Sie können eine oder mehrere Bedingungen konfigurieren, um Anmerkungsregeln zu erstellen, die Unified Manager auf die Speicherobjekte anwendet.  Die Speicherobjekte, die die Annotationsregel erfüllen, werden mit dem in der Regel angegebenen Wert annotiert. 
---
= Konfigurieren von Bedingungen für Anmerkungsregeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine oder mehrere Bedingungen konfigurieren, um Anmerkungsregeln zu erstellen, die Unified Manager auf die Speicherobjekte anwendet.  Die Speicherobjekte, die die Annotationsregel erfüllen, werden mit dem in der Regel angegebenen Wert annotiert.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Anmerkungen*.
. Klicken Sie auf der Registerkarte *Annotationsregeln* auf *Hinzufügen*.
. Geben Sie im Dialogfeld *Anmerkungsregel hinzufügen* einen Namen für die Regel ein.
. Wählen Sie einen Objekttyp aus der Liste „Zielobjekttyp“ und wählen Sie dann einen Anmerkungsnamen und -wert aus der Liste aus.
. Wählen Sie im Abschnitt *Bedingungen* des Dialogfelds einen Operanden und einen Operator aus der Liste aus und geben Sie einen Bedingungswert ein oder klicken Sie auf *Bedingung hinzufügen*, um eine neue Bedingung zu erstellen.
. Klicken Sie auf *Speichern und hinzufügen*.




== Beispiel für die Konfiguration einer Bedingung für eine Anmerkungsregel

Betrachten Sie eine Bedingung für den Objekttyp SVM, bei der der Objektname „`svm_data`“ enthält.

Führen Sie im Dialogfeld „Anmerkungsregel hinzufügen“ die folgenden Schritte aus, um die Bedingung zu konfigurieren:

.Schritte
. Geben Sie einen Namen für die Anmerkungsregel ein.
. Wählen Sie als Zielobjekttyp SVM aus.
. Wählen Sie eine Anmerkung aus der Liste der Anmerkungen und einen Wert aus.
. Wählen Sie im Feld *Bedingungen* als Operanden *Objektname* aus.
. Wählen Sie als Operator *Enthält* aus.
. Geben Sie den Wert als `svm_data` .
. Klicken Sie auf *Hinzufügen*.

