---
permalink: health-checker/task_restore_mysql_db_on_linux.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: Bei Datenverlust oder Datenbeschädigung können Sie Unified Manager mit minimalem Datenverlust in den vorherigen stabilen Zustand zurückversetzen.  Sie können die Unified Manager-Datenbank mithilfe der Unified Manager-Wartungskonsole auf einem lokalen oder Remote-Red Hat Enterprise Linux-System wiederherstellen. 
---
= Wiederherstellen einer MySQL-Datenbanksicherung auf einem Linux-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Datenverlust oder Datenbeschädigung können Sie Unified Manager mit minimalem Datenverlust in den vorherigen stabilen Zustand zurückversetzen.  Sie können die Unified Manager-Datenbank mithilfe der Unified Manager-Wartungskonsole auf einem lokalen oder Remote-Red Hat Enterprise Linux-System wiederherstellen.

.Bevor Sie beginnen
* Sie müssen über die Root-Benutzeranmeldeinformationen für den Linux-Host verfügen, auf dem Unified Manager installiert ist.
* Sie müssen über eine Benutzer-ID und ein Kennwort verfügen, die Sie zum Anmelden bei der Wartungskonsole des Unified Manager-Servers berechtigen.
* Sie müssen die Unified Manager-Sicherungsdatei und den Inhalt des Datenbank-Repository-Verzeichnisses auf das System kopiert haben, auf dem Sie den Wiederherstellungsvorgang durchführen.
+
Es wird empfohlen, die Sicherungsdatei in das Standardverzeichnis zu kopieren/`data/ocum` -Sicherung.  Die Datenbank-Repository-Dateien müssen in das/`database-dumps-repo` Unterverzeichnis unter dem/`ocum-backup` Verzeichnis.

* Die Sicherungsdateien müssen `.7z` Typ.


Die Wiederherstellungsfunktion ist plattform- und versionsspezifisch.  Sie können eine Unified Manager-Sicherung nur auf derselben Version von Unified Manager wiederherstellen.  Sie können eine Linux-Sicherungsdatei oder eine Sicherungsdatei einer virtuellen Appliance auf einem Red Hat Enterprise Linux-System wiederherstellen.

[TIP]
====
Wenn der Name des Sicherungsordners ein Leerzeichen enthält, müssen Sie den absoluten oder relativen Pfad in doppelte Anführungszeichen setzen.

====
.Schritte
. Wenn Sie eine Wiederherstellung auf einem neuen Server durchführen, starten Sie nach der Installation von Unified Manager nicht die Benutzeroberfläche und konfigurieren Sie keine Cluster, Benutzer oder Authentifizierungseinstellungen, wenn die Installation abgeschlossen ist.  Die Sicherungsdatei füllt diese Informationen während des Wiederherstellungsvorgangs.
. Stellen Sie mithilfe von Secure Shell eine Verbindung zur IP-Adresse oder zum vollqualifizierten Domänennamen des Unified Manager-Systems her.
. Melden Sie sich mit dem Namen und Kennwort des Wartungsbenutzers (umadmin) beim System an.
. Geben Sie den Befehl ein `maintenance_console` und drücken Sie die Eingabetaste.
. Geben Sie im *Hauptmenü* der Wartungskonsole die Nummer für die Option *Backup-Wiederherstellung* ein.
. Geben Sie die Nummer für die *Wiederherstellung des MySQL-Backups* ein.
. Geben Sie bei der entsprechenden Aufforderung den absoluten Pfad der Sicherungsdatei ein.
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
Nachdem der Wiederherstellungsvorgang abgeschlossen ist, können Sie sich bei Unified Manager anmelden.



Wenn der OnCommand Workflow Automation -Server nach der Wiederherstellung der Sicherung nicht funktioniert, führen Sie die folgenden Schritte aus:

. Ändern Sie auf dem Workflow Automation-Server die IP-Adresse des Unified Manager-Servers, sodass sie auf die neueste Maschine verweist.
. Setzen Sie auf dem Unified Manager-Server das Datenbankkennwort zurück, wenn die Erfassung in Schritt 1 fehlschlägt.

