---
permalink: health-checker/task_add_values_to_annotations.html 
sidebar: sidebar 
keywords: add, values, annotations 
summary: Sie können Anmerkungen Werte hinzufügen und dann Speicherobjekte mit einem bestimmten Name-Wert-Paar aus Anmerkungen verknüpfen.  Durch das Hinzufügen von Werten zu Anmerkungen können Sie Speicherobjekte effektiver verwalten. 
---
= Hinzufügen von Werten zu Anmerkungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Anmerkungen Werte hinzufügen und dann Speicherobjekte mit einem bestimmten Name-Wert-Paar aus Anmerkungen verknüpfen.  Durch das Hinzufügen von Werten zu Anmerkungen können Sie Speicherobjekte effektiver verwalten.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Sie können vordefinierten Anmerkungen keine Werte hinzufügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Anmerkungen*.
. Wählen Sie auf der Seite *Anmerkungen* die Anmerkung aus, der Sie einen Wert hinzufügen möchten, und klicken Sie dann im Abschnitt *Werte* auf *Hinzufügen*.
. Geben Sie im Dialogfeld *Anmerkungswert hinzufügen* einen Wert für die Anmerkung an.
+
Der von Ihnen angegebene Wert muss für die ausgewählte Anmerkung eindeutig sein.

. Klicken Sie auf *Hinzufügen*.

