---
permalink: health-checker/task_view_details_about_cifs_shares.html 
sidebar: sidebar 
keywords: smb, cifs, view, shares, details 
summary: 'Sie können Details zu allen SMB/CIFS-Freigaben anzeigen, z. B. Freigabename, Verbindungspfad, enthaltene Objekte, Sicherheitseinstellungen und für die Freigabe definierte Exportrichtlinien.  Verwenden Sie die Ansicht „Integrität: Alle SMB-Freigaben“, um alle SMB-Freigaben auf allen überwachten Clustern anzuzeigen, und verwenden Sie die Seite „Speicher-VM/Integritätsdetails“, um alle SMB-Freigaben auf einer bestimmten virtuellen Speichermaschine (SVM) anzuzeigen.' 
---
= Details zu SMB/CIFS-Freigaben anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Details zu allen SMB/CIFS-Freigaben anzeigen, z. B. Freigabename, Verbindungspfad, enthaltene Objekte, Sicherheitseinstellungen und für die Freigabe definierte Exportrichtlinien.  Verwenden Sie die Ansicht „Integrität: Alle SMB-Freigaben“, um alle SMB-Freigaben auf allen überwachten Clustern anzuzeigen, und verwenden Sie die Seite „Speicher-VM/Integritätsdetails“, um alle SMB-Freigaben auf einer bestimmten virtuellen Speichermaschine (SVM) anzuzeigen.

.Bevor Sie beginnen
* Die CIFS-Lizenz muss auf dem Cluster aktiviert sein.
* Netzwerkschnittstellen, die die SMB/CIFS-Freigaben bedienen, müssen konfiguriert werden.
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.


[NOTE]
====
Freigaben in Ordnern werden nicht angezeigt.

====
.Schritt
. Führen Sie im linken Navigationsbereich die folgenden Schritte aus, je nachdem, ob Sie alle SMB/CIFS-Freigaben oder nur die Freigaben für eine bestimmte SVM anzeigen möchten.
+
[cols="2*"]
|===
| Zu... | Befolgen Sie diese Schritte... 


 a| 
Alle SMB/CIFS-Freigaben anzeigen
 a| 
Klicken Sie auf *Speicher* > *SMB-Freigaben*



 a| 
SMB/CIFS-Freigaben für einzelne SVM anzeigen
 a| 
.. Klicken Sie auf *Speicher* > *Speicher-VMs*
.. Klicken Sie auf die SVM, für die Sie die SMB/CIFS-Freigabedetails anzeigen möchten.
.. Klicken Sie auf der Seite „Storage VM / Health Details“ auf die Registerkarte *SMB Shares*.


|===


Weitere Informationen finden Sie unter link:../api-automation/concept_provision_file_share.html["Bereitstellung von CIFS- und NFS-Dateifreigaben mithilfe von APIs"].
