---
permalink: health-checker/task_add_annotations_dynamically.html 
sidebar: sidebar 
keywords: add, annotations, dynamically 
summary: 'Wenn Sie benutzerdefinierte Anmerkungen erstellen, verknüpft Unified Manager mithilfe von Regeln dynamisch Cluster, virtuelle Speichermaschinen (SVMs) und Volumes mit den Anmerkungen.  Diese Regeln ordnen die Anmerkungen automatisch Speicherobjekten zu.' 
---
= Anmerkungen dynamisch hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie benutzerdefinierte Anmerkungen erstellen, verknüpft Unified Manager mithilfe von Regeln dynamisch Cluster, virtuelle Speichermaschinen (SVMs) und Volumes mit den Anmerkungen.  Diese Regeln ordnen die Anmerkungen automatisch Speicherobjekten zu.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Anmerkungen*.
. Klicken Sie auf der Seite *Anmerkungen* auf *Anmerkung hinzufügen*.
. Geben Sie im Dialogfeld *Anmerkung hinzufügen* einen Namen und eine Beschreibung für die Anmerkung ein.
. Optional: Klicken Sie im Abschnitt *Annotationswerte* auf *Hinzufügen*, um der Annotation Werte hinzuzufügen.
. Klicken Sie auf *Speichern*.

