---
permalink: health-checker/task_configure_lag_threshold_settings_for_unmanaged_protection.html 
sidebar: sidebar 
keywords: configure, lag, threshold settings, unmanaged, protection, relationships 
summary: Sie können die globalen Standardeinstellungen für Verzögerungswarnungen und Fehlerzustandsschwellenwerte für nicht verwaltete Schutzbeziehungen bearbeiten, sodass Ereignisse in Intervallen generiert werden, die Ihren Anforderungen entsprechen. 
---
= Konfigurieren von Verzögerungsschwellenwerten für nicht verwaltete Schutzbeziehungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die globalen Standardeinstellungen für Verzögerungswarnungen und Fehlerzustandsschwellenwerte für nicht verwaltete Schutzbeziehungen bearbeiten, sodass Ereignisse in Intervallen generiert werden, die Ihren Anforderungen entsprechen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Die Verzögerungszeit darf nicht länger sein als das definierte Übertragungsintervall.  Wenn beispielsweise stündlich verkehrt, darf die Verzögerungszeit nicht mehr als eine Stunde betragen.  Der Verzögerungsschwellenwert gibt einen Prozentsatz an, den die Verzögerungszeit nicht überschreiten darf.  Wenn im Beispiel einer Stunde der Verzögerungsschwellenwert auf 150 % festgelegt ist, erhalten Sie ein Ereignis, wenn die Verzögerungszeit mehr als 1,5 Stunden beträgt.

Die in dieser Aufgabe beschriebenen Einstellungen werden global auf alle nicht verwalteten Schutzbeziehungen angewendet.  Die Einstellungen können nicht ausschließlich für eine nicht verwaltete Schutzbeziehung festgelegt und angewendet werden.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Ereignisschwellenwerte* > *Beziehung*.
. Erhöhen oder verringern Sie den Prozentsatz der globalen Standardwarnungs- oder Fehlerverzögerungszeit nach Bedarf.
. Um zu verhindern, dass bei einem beliebigen Verzögerungsschwellenwert ein Warn- oder Fehlerereignis ausgelöst wird, deaktivieren Sie das Kontrollkästchen neben *Aktiviert*.
. Klicken Sie auf *Speichern*.


*Verwandte Informationen*

link:../config/task_add_users.html["Benutzer hinzufügen"]
