---
permalink: health-checker/task_view_health_and_capacity_status_of_all_san_array_clusters.html 
sidebar: sidebar 
keywords: view, all san array, health and capacity, clusters 
summary: Sie können die Cluster-Inventarseiten verwenden, um den Integritäts- und Kapazitätsstatus Ihrer All-SAN-Array-Cluster anzuzeigen. 
---
= Anzeigen des Integritäts- und Kapazitätsstatus aller SAN-Array-Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Cluster-Inventarseiten verwenden, um den Integritäts- und Kapazitätsstatus Ihrer All-SAN-Array-Cluster anzuzeigen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Sie können Übersichtsinformationen für alle SAN-Array-Cluster in der Ansicht „Integrität: Alle Cluster“ und in der Ansicht „Kapazität: Alle Cluster“ anzeigen.  Darüber hinaus können Sie Details auf der Seite „Cluster-/Integritätsdetails“ anzeigen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Cluster*.
. Stellen Sie sicher, dass die Spalte „Persönlichkeit“ in der Ansicht *Gesundheit: Alle Cluster* angezeigt wird, oder fügen Sie sie mithilfe des Steuerelements *Einblenden/Ausblenden* hinzu.
+
In dieser Spalte wird „All SAN Array“ für Ihre All SAN Array-Cluster angezeigt.

. Überprüfen Sie die Informationen.
. Um Informationen zur Speicherkapazität in diesen Clustern anzuzeigen, wählen Sie die Ansicht „Kapazität: Alle Cluster“ aus.
. Um detaillierte Informationen zum Zustand und zur Speicherkapazität dieser Cluster anzuzeigen, klicken Sie auf den Namen eines All-SAN-Array-Clusters.
+
Zeigen Sie die Details auf den Registerkarten „Integrität“, „Kapazität“ und „Knoten“ auf der Seite „Cluster-/Integritätsdetails“ an.


