---
permalink: health-checker/task_disable_specific_security_events.html 
sidebar: sidebar 
keywords: disable, specific, security events 
summary: Alle Ereignisse sind standardmäßig aktiviert.  Sie können bestimmte Ereignisse deaktivieren, um die Generierung von Benachrichtigungen für Ereignisse zu verhindern, die in Ihrer Umgebung nicht wichtig sind.  Sie können deaktivierte Ereignisse aktivieren, wenn Sie weiterhin Benachrichtigungen dafür erhalten möchten. 
---
= Deaktivieren bestimmter Sicherheitsereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alle Ereignisse sind standardmäßig aktiviert.  Sie können bestimmte Ereignisse deaktivieren, um die Generierung von Benachrichtigungen für Ereignisse zu verhindern, die in Ihrer Umgebung nicht wichtig sind.  Sie können deaktivierte Ereignisse aktivieren, wenn Sie weiterhin Benachrichtigungen dafür erhalten möchten.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Wenn Sie Ereignisse deaktivieren, werden die zuvor generierten Ereignisse im System als veraltet markiert und die für diese Ereignisse konfigurierten Warnungen werden nicht ausgelöst.  Wenn Sie deaktivierte Ereignisse aktivieren, werden die Benachrichtigungen für diese Ereignisse ab dem nächsten Überwachungszyklus generiert.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Ereigniseinrichtung*.
. Deaktivieren oder aktivieren Sie Ereignisse auf der Seite „Ereignis-Setup“, indem Sie eine der folgenden Optionen auswählen:
+
[cols="2*"]
|===
| Wenn Sie wollen... | Dann tun Sie Folgendes ... 


 a| 
Ereignisse deaktivieren
 a| 
.. Klicken Sie auf *Deaktivieren*.
.. Wählen Sie im Dialogfeld „Ereignisse deaktivieren“ den Schweregrad *Warnung* aus.  Dies ist die Kategorie für alle Sicherheitsereignisse.
.. Wählen Sie in der Spalte „Übereinstimmende Ereignisse“ die Sicherheitsereignisse aus, die Sie deaktivieren möchten, und klicken Sie dann auf den Rechtspfeil, um diese Ereignisse in die Spalte „Ereignisse deaktivieren“ zu verschieben.
.. Klicken Sie auf *Speichern und schließen*.
.. Überprüfen Sie, ob die von Ihnen deaktivierten Ereignisse in der Listenansicht der Seite „Ereigniseinrichtung“ angezeigt werden.




 a| 
Ereignisse aktivieren
 a| 
.. Aktivieren Sie in der Liste der deaktivierten Ereignisse das Kontrollkästchen für das bzw. die Ereignisse, die Sie wieder aktivieren möchten.
.. Klicken Sie auf *Aktivieren*.


|===

