---
permalink: health-checker/task_configure_global_aggregate_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, aggregate, health, threshold values 
summary: Sie können globale Integritätsschwellenwerte für alle Aggregate konfigurieren, um alle Schwellenwertüberschreitungen zu verfolgen.  Bei Grenzwertüberschreitungen werden entsprechende Ereignisse generiert und Sie können auf Basis dieser Ereignisse vorbeugende Maßnahmen ergreifen.  Sie können die globalen Werte basierend auf den Best Practice-Einstellungen für Schwellenwerte konfigurieren, die für alle überwachten Aggregate gelten. 
---
= Konfigurieren globaler Schwellenwerte für die Gesamtintegrität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können globale Integritätsschwellenwerte für alle Aggregate konfigurieren, um alle Schwellenwertüberschreitungen zu verfolgen.  Bei Grenzwertüberschreitungen werden entsprechende Ereignisse generiert und Sie können auf Basis dieser Ereignisse vorbeugende Maßnahmen ergreifen.  Sie können die globalen Werte basierend auf den Best Practice-Einstellungen für Schwellenwerte konfigurieren, die für alle überwachten Aggregate gelten.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Wenn Sie die Optionen global konfigurieren, werden die Standardwerte der Objekte geändert.  Wenn die Standardwerte jedoch auf Objektebene geändert wurden, werden die globalen Werte nicht geändert.

Die Schwellenwertoptionen verfügen über Standardwerte zur besseren Überwachung. Sie können die Werte jedoch ändern, um sie an die Anforderungen Ihrer Umgebung anzupassen.

Wenn Autogrow auf Volumes aktiviert ist, die sich auf dem Aggregat befinden, gelten die Schwellenwerte für die Aggregatkapazität als überschritten, und zwar basierend auf der durch Autogrow festgelegten maximalen Volumegröße, nicht basierend auf der ursprünglichen Volumegröße.

[NOTE]
====
Integritätsschwellenwerte sind auf das Stammaggregat des Knotens nicht anwendbar.

====
.Schritte
. Klicken Sie im linken Navigationsbereich auf *Ereignisschwellenwerte* > *Aggregat*.
. Konfigurieren Sie die entsprechenden Schwellenwerte für Kapazität, Wachstum und Snapshot-Kopien.
. Klicken Sie auf *Speichern*.


*Verwandte Informationen*

link:../config/task_add_users.html["Benutzer hinzufügen"]
