---
permalink: health-checker/task_view_list_of_snapshot_copies.html 
sidebar: sidebar 
keywords: view, list, Snapshot copies 
summary: Sie können die Liste der Snapshot-Kopien für ein ausgewähltes Volume anzeigen.  Mithilfe der Liste der Snapshot-Kopien können Sie die Menge an Speicherplatz berechnen, die zurückgewonnen werden kann, wenn eine oder mehrere Snapshot-Kopien gelöscht werden, und Sie können die Snapshot-Kopien bei Bedarf löschen. 
---
= Liste der Snapshot-Kopien anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Liste der Snapshot-Kopien für ein ausgewähltes Volume anzeigen.  Mithilfe der Liste der Snapshot-Kopien können Sie die Menge an Speicherplatz berechnen, die zurückgewonnen werden kann, wenn eine oder mehrere Snapshot-Kopien gelöscht werden, und Sie können die Snapshot-Kopien bei Bedarf löschen.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Das Volume mit den Snapshot-Kopien muss online sein.


.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Volumes*.
. Wählen Sie in der Ansicht *Health: All Volumes* das Volume aus, das die Snapshot-Kopien enthält, die Sie anzeigen möchten.
. Klicken Sie auf der Detailseite *Volume/Integrität* auf die Registerkarte *Kapazität*.
. Klicken Sie im Bereich *Details* der Registerkarte *Kapazität* im Abschnitt „Weitere Details“ auf den Link neben *Snapshot-Kopien*.
+
Die Anzahl der Snapshot-Kopien ist ein Link, der die Liste der Snapshot-Kopien anzeigt.



*Verwandte Informationen*

link:../health-checker/reference_health_volume_details_page.html["Seite „Zustand/Volumes“"]
