---
permalink: health-checker/task_view_security_events_that_require_software_or_firmware_updates.html 
sidebar: sidebar 
keywords: upgrade events, view, security events, software, firmware updates 
summary: 'Es gibt bestimmte Sicherheitsereignisse, die den Auswirkungsbereich „Upgrade“ haben.  Diese Ereignisse werden von der Active IQ Plattform gemeldet und identifizieren Probleme, für deren Lösung Sie ein Upgrade der ONTAP -Software, der Knoten-Firmware oder der Betriebssystemsoftware (für Sicherheitshinweise) durchführen müssen.' 
---
= Zeigen Sie Sicherheitsereignisse an, die möglicherweise Software- oder Firmware-Updates erfordern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte Sicherheitsereignisse, die den Auswirkungsbereich „Upgrade“ haben.  Diese Ereignisse werden von der Active IQ Plattform gemeldet und identifizieren Probleme, für deren Lösung Sie ein Upgrade der ONTAP -Software, der Knoten-Firmware oder der Betriebssystemsoftware (für Sicherheitshinweise) durchführen müssen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Bei einigen dieser Probleme möchten Sie möglicherweise sofort Abhilfemaßnahmen ergreifen, während andere Probleme möglicherweise bis zu Ihrer nächsten planmäßigen Wartung warten können.  Sie können alle diese Ereignisse anzeigen und sie Benutzern zuweisen, die die Probleme lösen können.  Wenn es außerdem bestimmte Sicherheitsupgrade-Ereignisse gibt, über die Sie nicht benachrichtigt werden möchten, kann Ihnen diese Liste dabei helfen, diese Ereignisse zu identifizieren, sodass Sie sie deaktivieren können.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Event Management*.
+
Standardmäßig werden alle aktiven (neuen und bestätigten) Ereignisse auf der Inventarseite der Ereignisverwaltung angezeigt.

. Wählen Sie im Menü „Ansicht“ die Option „Upgrade-Ereignisse“ aus.
+
Auf der Seite werden alle aktiven Upgrade-Sicherheitsereignisse angezeigt.


