---
permalink: health-checker/task_restore_mysql_database_backup_on_windows.html 
sidebar: sidebar 
keywords: restore, windows, mysql, database, backup 
summary: Im Falle eines Datenverlusts oder einer Datenbeschädigung können Sie die Wiederherstellungsfunktion verwenden, um Unified Manager mit minimalem Verlust in den vorherigen stabilen Zustand zurückzusetzen.  Sie können die Unified Manager MySQL-Datenbank mithilfe der Unified Manager-Wartungskonsole auf einem lokalen Windows-System oder einem Remote-Windows-System wiederherstellen. 
---
= Wiederherstellen einer MySQL-Datenbanksicherung unter Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Falle eines Datenverlusts oder einer Datenbeschädigung können Sie die Wiederherstellungsfunktion verwenden, um Unified Manager mit minimalem Verlust in den vorherigen stabilen Zustand zurückzusetzen.  Sie können die Unified Manager MySQL-Datenbank mithilfe der Unified Manager-Wartungskonsole auf einem lokalen Windows-System oder einem Remote-Windows-System wiederherstellen.

.Bevor Sie beginnen
* Sie müssen über Windows-Administratorrechte verfügen.
* Sie müssen die Unified Manager-Sicherungsdatei und den Inhalt des Datenbank-Repository-Verzeichnisses auf das System kopiert haben, auf dem Sie den Wiederherstellungsvorgang durchführen.
+
Es wird empfohlen, die Sicherungsdatei in das Standardverzeichnis zu kopieren `\ProgramData\NetApp\OnCommandAppData\ocum\backup` .  Die Datenbank-Repository-Dateien müssen in das `\database_dumps_repo` Unterverzeichnis unter dem `\backup` Verzeichnis.

* Die Sicherungsdateien müssen `.7z` Typ.


Die Wiederherstellungsfunktion ist plattform- und versionsspezifisch.  Sie können ein Unified Manager MySQL-Backup nur auf derselben Version von Unified Manager wiederherstellen, und ein Windows-Backup kann nur auf einer Windows-Plattform wiederhergestellt werden.

[TIP]
====
Wenn die Ordnernamen ein Leerzeichen enthalten, müssen Sie den absoluten Pfad oder den relativen Pfad der Sicherungsdatei in doppelte Anführungszeichen setzen.

====
.Schritte
. Wenn Sie eine Wiederherstellung auf einem neuen Server durchführen, starten Sie nach der Installation von Unified Manager nicht die Benutzeroberfläche und konfigurieren Sie keine Cluster, Benutzer oder Authentifizierungseinstellungen, wenn die Installation abgeschlossen ist.  Die Sicherungsdatei füllt diese Informationen während des Wiederherstellungsvorgangs.
. Melden Sie sich mit Administratoranmeldeinformationen beim Unified Manager-System an.
. Starten Sie PowerShell oder die Eingabeaufforderung als Windows-Administrator.
. Geben Sie den Befehl ein `maintenance_console` und drücken Sie die Eingabetaste.
. Geben Sie im *Hauptmenü* der Wartungskonsole die Nummer für die Option *Backup-Wiederherstellung* ein.
. Geben Sie die Nummer für die *Wiederherstellung des MySQL-Backups* ein.
. Geben Sie bei der entsprechenden Aufforderung den absoluten Pfad der Sicherungsdatei ein.
+
[listing]
----
Bundle to restore from: \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.8.N151118.2300_backup_windows_02-20-2020-02-51.7z
----
+
Nachdem der Wiederherstellungsvorgang abgeschlossen ist, können Sie sich bei Unified Manager anmelden.



Wenn der OnCommand Workflow Automation -Server nach der Wiederherstellung der Sicherung nicht funktioniert, führen Sie die folgenden Schritte aus:

. Ändern Sie auf dem Workflow Automation-Server die IP-Adresse des Unified Manager-Servers, sodass sie auf die neueste Maschine verweist.
. Setzen Sie auf dem Unified Manager-Server das Datenbankkennwort zurück, wenn die Erfassung in Schritt 1 fehlschlägt.

