---
permalink: health-checker/task_edit_individual_aggregate_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, aggregate, health, threshold, settings 
summary: Sie können die Integritätsschwellenwerteinstellungen für die Aggregatkapazität, das Wachstum und die Snapshot-Kopien eines oder mehrerer Aggregate bearbeiten.  Wenn ein Schwellenwert überschritten wird, werden Warnungen generiert und Sie erhalten Benachrichtigungen.  Diese Benachrichtigungen helfen Ihnen, basierend auf dem generierten Ereignis vorbeugende Maßnahmen zu ergreifen. 
---
= Bearbeiten Sie die einzelnen Schwellenwerteinstellungen für die Gesamtintegrität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Integritätsschwellenwerteinstellungen für die Aggregatkapazität, das Wachstum und die Snapshot-Kopien eines oder mehrerer Aggregate bearbeiten.  Wenn ein Schwellenwert überschritten wird, werden Warnungen generiert und Sie erhalten Benachrichtigungen.  Diese Benachrichtigungen helfen Ihnen, basierend auf dem generierten Ereignis vorbeugende Maßnahmen zu ergreifen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Basierend auf Änderungen der Schwellenwerte werden im nächsten Überwachungszyklus Ereignisse generiert oder verworfen.

Wenn Autogrow auf Volumes aktiviert ist, die sich auf dem Aggregat befinden, gelten die Schwellenwerte für die Aggregatkapazität als überschritten, und zwar basierend auf der durch Autogrow festgelegten maximalen Volumegröße, nicht basierend auf der ursprünglichen Volumegröße.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Aggregate*.
. Wählen Sie in der Ansicht *Health: Alle Aggregate* ein oder mehrere Aggregate aus und klicken Sie dann auf *Schwellenwerte bearbeiten*.
. Bearbeiten Sie im Dialogfeld *Aggregatschwellenwerte bearbeiten* die Schwellenwerteinstellungen für eine der folgenden Optionen: Kapazität, Wachstum oder Snapshot-Kopien, indem Sie das entsprechende Kontrollkästchen aktivieren und dann die Einstellungen ändern.
. Klicken Sie auf *Speichern*.


*Verwandte Informationen*

link:../config/task_add_users.html["Benutzer hinzufügen"]
