---
permalink: health-checker/task_delete_snapshot_copies.html 
sidebar: sidebar 
keywords: delete, snapshot copies 
summary: Sie können eine Snapshot-Kopie löschen, um Speicherplatz zu sparen oder freizugeben, oder Sie können die Snapshot-Kopie löschen, wenn sie nicht mehr benötigt wird. 
---
= Löschen von Snapshot-Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Snapshot-Kopie löschen, um Speicherplatz zu sparen oder freizugeben, oder Sie können die Snapshot-Kopie löschen, wenn sie nicht mehr benötigt wird.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Das Volume muss online sein.

Um eine Snapshot-Kopie zu löschen, die belegt oder gesperrt ist, müssen Sie die Snapshot-Kopie aus der Anwendung freigegeben haben, die sie verwendet hat.

* Sie können die Basis-Snapshot-Kopie in einem übergeordneten Volume nicht löschen, wenn ein FlexClone -Volume diese Snapshot-Kopie verwendet.
+
Die Basis-Snapshot-Kopie ist die Snapshot-Kopie, die zum Erstellen des FlexClone -Volumes verwendet wird und den Status anzeigt `Busy` und Anwendungsabhängigkeit als `Busy, Vclone` im übergeordneten Volume.

* Sie können keine gesperrte Snapshot-Kopie löschen, die in einer SnapMirror -Beziehung verwendet wird.
+
Die Snapshot-Kopie ist gesperrt und wird für das nächste Update benötigt.



.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Volumes*.
. Wählen Sie in der Ansicht *Health: All Volumes* das Volume aus, das die Snapshot-Kopien enthält, die Sie anzeigen möchten.
+
Die Liste der Snapshot-Kopien wird angezeigt.

. Klicken Sie auf der Detailseite *Volume/Integrität* auf die Registerkarte *Kapazität*.
. Klicken Sie im Bereich *Details* der Registerkarte *Kapazität* im Abschnitt „Weitere Details“ auf den Link neben *Snapshot-Kopien*.
+
Die Anzahl der Snapshot-Kopien ist ein Link, der die Liste der Snapshot-Kopien anzeigt.

. Wählen Sie in der Ansicht *Snapshot-Kopien* die Snapshot-Kopien aus, die Sie löschen möchten, und klicken Sie dann auf *Ausgewählte löschen*.

