---
permalink: health-checker/task_edit_group_rules.html 
sidebar: sidebar 
keywords: edit, group rules 
summary: Sie können Gruppenregeln bearbeiten, um die Bedingungsgruppen und die Bedingungen innerhalb einer Bedingungsgruppe zu ändern und so Speicherobjekte zu einer bestimmten Gruppe hinzuzufügen oder daraus zu entfernen. 
---
= Gruppenregeln bearbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Gruppenregeln bearbeiten, um die Bedingungsgruppen und die Bedingungen innerhalb einer Bedingungsgruppe zu ändern und so Speicherobjekte zu einer bestimmten Gruppe hinzuzufügen oder daraus zu entfernen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Gruppen*.
. Wählen Sie auf der Registerkarte *Gruppenregeln* die Gruppenregel aus, die Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Ändern Sie im Dialogfeld *Gruppenregel bearbeiten* den Gruppenregelnamen, den zugehörigen Gruppennamen, die Bedingungsgruppen und die Bedingungen nach Bedarf.
+
[NOTE]
====
Sie können den Zielobjekttyp für eine Gruppenregel nicht ändern.

====
. Klicken Sie auf *Speichern*.

