---
permalink: health-checker/task_create_annotation_rules.html 
sidebar: sidebar 
keywords: create, annotation rules 
summary: 'Sie können Anmerkungsregeln erstellen, die Unified Manager verwendet, um Speicherobjekte wie Volumes, Cluster oder Storage Virtual Machines (SVMs) dynamisch zu annotieren.' 
---
= Erstellen von Anmerkungsregeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Anmerkungsregeln erstellen, die Unified Manager verwendet, um Speicherobjekte wie Volumes, Cluster oder Storage Virtual Machines (SVMs) dynamisch zu annotieren.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Speicherobjekte, die derzeit überwacht werden, werden mit Anmerkungen versehen, sobald die Anmerkungsregel erstellt wird.  Neue Objekte werden erst nach Abschluss des Überwachungszyklus annotiert.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Anmerkungen*.
. Klicken Sie auf der Registerkarte *Annotationsregeln* auf *Hinzufügen*.
. Geben Sie im Dialogfeld *Anmerkungsregel hinzufügen* einen Namen für die Anmerkungsregel an.
. Wählen Sie im Feld *Zielobjekttyp* den Typ des Speicherobjekts aus, das Sie mit Anmerkungen versehen möchten.
. Wählen Sie in den Feldern *Anmerkung anwenden* die Anmerkung und den Anmerkungswert aus, die Sie verwenden möchten.
. Führen Sie im Abschnitt „Bedingungen“ die entsprechende Aktion aus, um eine Bedingung, eine Bedingungsgruppe oder beides zu erstellen:
+
[cols="2*"]
|===
| Erstellen... | Machen Sie Folgendes... 


 a| 
Eine Bedingung
 a| 
.. Wählen Sie einen Operanden aus der Operandenliste aus.
.. Wählen Sie als Operator entweder *Enthält* oder *Ist* aus.
.. Geben Sie einen Wert ein oder wählen Sie einen Wert aus der verfügbaren Liste aus.




 a| 
Eine Bedingungsgruppe
 a| 
.. Klicken Sie auf *Bedingungsgruppe hinzufügen*.
.. Wählen Sie einen Operanden aus der Operandenliste aus.
.. Wählen Sie als Operator entweder *Enthält* oder *Ist* aus.
.. Geben Sie einen Wert ein oder wählen Sie einen Wert aus der verfügbaren Liste aus.
.. Klicken Sie auf *Bedingung hinzufügen*, um bei Bedarf weitere Bedingungen zu erstellen, und wiederholen Sie die Schritte a bis d für jede Bedingung.


|===
. Klicken Sie auf *Hinzufügen*.




== Beispiel für das Erstellen einer Anmerkungsregel

Führen Sie im Dialogfeld „Anmerkungsregel hinzufügen“ die folgenden Schritte aus, um eine Anmerkungsregel zu erstellen, einschließlich der Konfiguration einer Bedingung und des Hinzufügens einer Bedingungsgruppe:

.Schritte
. Geben Sie einen Namen für die Anmerkungsregel an.
. Wählen Sie als Zielobjekttyp „Storage Virtual Machine“ (SVM) aus.
. Wählen Sie eine Anmerkung aus der Anmerkungsliste aus und geben Sie einen Wert an.
. Wählen Sie im Abschnitt „Bedingungen“ als Operanden „*Objektname*“ aus.
. Wählen Sie als Operator *Enthält* aus.
. Geben Sie den Wert als `svm_data` .
. Klicken Sie auf *Bedingungsgruppe hinzufügen*.
. Wählen Sie als Operand *Objektname*.
. Wählen Sie als Operator *Enthält* aus.
. Geben Sie den Wert als `vol` .
. Klicken Sie auf *Bedingung hinzufügen*.
. Wiederholen Sie die Schritte 8 bis 10, indem Sie in Schritt 8 *data-priority* als Operanden, in Schritt 9 *Is* als Operator und in Schritt 10 *mission-critical* als Wert auswählen.
. Klicken Sie auf *Hinzufügen*.

