---
permalink: install-vapp/task_upgrade_unified_manager_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Sie können auf Unified Manager auf VMware vSphere aktualisieren 
---
= Upgrade von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Active IQ Unified Manager nur von Version 9.13 oder 9.14 auf Version 9.16 aktualisieren.

Während des Upgrade-Vorgangs ist Unified Manager nicht verfügbar.  Sie sollten alle laufenden Vorgänge abschließen, bevor Sie Unified Manager aktualisieren.

Wenn Unified Manager mit einer Instanz von OnCommand Workflow Automation gekoppelt ist und für beide Produkte neue Softwareversionen verfügbar sind, müssen Sie die beiden Produkte trennen und nach der Durchführung der Upgrades eine neue Workflow Automation-Verbindung einrichten.  Wenn Sie ein Upgrade nur für eines der Produkte durchführen, sollten Sie sich nach dem Upgrade bei Workflow Automation anmelden und überprüfen, ob weiterhin Daten vom Unified Manager abgerufen werden.

.Schritte
. Befolgen Sie die Schritte inlink:task_download_unified_manager_iso_image_vapp.html["Laden Sie das ISO-Image von Unified Manager herunter"] .
. Befolgen Sie außerdem die Schritte inlink:task_upgrade_unified_manager_virtual_appliance_vapp.html["Upgrade von Unified Manager"] .

