---
permalink: install-windows/task_install_unified_manager_on_windows.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: Sie können Unified Manager installieren, um Probleme hinsichtlich der Datenspeicherkapazität, Verfügbarkeit, Leistung und Sicherheit zu überwachen und zu beheben. 
---
= Unified Manager installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager installieren, um Probleme hinsichtlich der Datenspeicherkapazität, Verfügbarkeit, Leistung und Sicherheit zu überwachen und zu beheben.

.Bevor Sie beginnen
* Das System, auf dem Sie Unified Manager installieren möchten, sollte die System- und Softwareanforderungen erfüllen.
+
Sehenlink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Hardware-Systemanforderungen"] .

+
Sehenlink:reference_windows_software_and_installation_requirements.html["Windows-Software- und Installationsanforderungen"] .

+
[NOTE]
====
Ab Unified Manager 9.5 ist OpenJDK im Installationspaket enthalten und wird automatisch installiert.  Oracle Java wird ab Unified Manager 9.5 nicht mehr unterstützt.

====
* Sie sollten über Windows-Administratorrechte verfügen.  Stellen Sie sicher, dass Ihr Benutzername nicht mit einem Ausrufezeichen beginnt.!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "` !`".
* Alle Cluster werden unterstützt, mit Ausnahme von ASA R2-Systemen.
* Sie sollten über einen unterstützten Webbrowser verfügen.
* Das Wartungsbenutzerkennwort für Unified Manager sollte zwischen 8 und 20 Zeichen lang sein und Groß- oder Kleinbuchstaben, Ziffern und Sonderzeichen enthalten.
* Die folgenden Sonderzeichen sind in der Kennwortzeichenfolge für den Wartungsbenutzer oder für den MySQL-Root-Benutzer nicht zulässig: " ' ` % , = & < > | ^ \ / ( ) [ ] ;:
+
Folgende Sonderzeichen sind erlaubt: ~ !  @ # $ * - ? .  + { }



.Schritte
. Melden Sie sich mit dem standardmäßigen lokalen Administratorkonto bei Windows an.
. Melden Sie sich bei der NetApp Support-Site an und navigieren Sie zur Download-Seite für Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp Support Site"^]

. Wählen Sie die erforderliche Version von Unified Manager aus und akzeptieren Sie die Endbenutzer-Lizenzvereinbarung (EULA).
. Laden Sie die Windows-Installationsdatei oder ZIP-Datei von Unified Manager in ein Zielverzeichnis auf dem Windows-System herunter.
. Extrahieren Sie bei Bedarf die ZIP-Datei und navigieren Sie zu dem Verzeichnis, in dem sich die Installationsdatei befindet.
. Klicken Sie mit der rechten Maustaste und führen Sie die ausführbare Datei (.exe) des Unified Manager-Installationsprogramms als Administrator aus.
+
Unified Manager erkennt fehlende oder vorinstallierte Pakete von Drittanbietern und listet sie auf.  Wenn die erforderlichen Pakete von Drittanbietern nicht im System installiert sind, installiert Unified Manager sie als Teil der Installation.

. Klicken Sie auf *Weiter*.
. Geben Sie den Benutzernamen und das Kennwort ein, um den Wartungsbenutzer zu erstellen.
. Geben Sie im Datenbankverbindungsassistenten das MySQL-Root-Passwort ein.
. Klicken Sie auf *Ändern*, um einen neuen Speicherort für das Unified Manager-Installationsverzeichnis und das MySQL-Datenverzeichnis anzugeben.
+
Wenn Sie das Installationsverzeichnis nicht ändern, wird Unified Manager im Standardinstallationsverzeichnis installiert.

. Klicken Sie auf *Weiter*.
. Klicken Sie im Assistenten „Bereit zur Installation von Shield“ auf *Installieren*.
. Klicken Sie nach Abschluss der Installation auf *Fertig*.
. Wenn auf Ihrem Windows-System eine aktive Antivirensoftware installiert ist, schließen Sie nach Abschluss der Installation die folgenden Pfade manuell vom Antivirenscan aus:
+
** Unified Manager-Datenverzeichnis
** Unified Manager-Installationsverzeichnis
** MySQL-Datenverzeichnis




Bei der Installation werden mehrere Verzeichnisse erstellt:

* Installationsverzeichnis
+
Dies ist das Stammverzeichnis für Unified Manager, das Sie während der Installation angegeben haben.  Beispiel: `C:\Program Files\NetApp\`

* MySQL-Datenverzeichnis
+
Dies ist das Verzeichnis, in dem die MySQL-Datenbanken gespeichert sind, die Sie während der Installation angegeben haben.  Beispiel: `C:\ProgramData\MySQL\MySQLServerData\`

* Java-Verzeichnis
+
Dies ist das Verzeichnis, in dem OpenJDK installiert ist.  Beispiel: `C:\Program Files\NetApp\JDK\`

* Unified Manager-Anwendungsdatenverzeichnis (appDataDir)
+
Dies ist das Verzeichnis, in dem alle von der Anwendung generierten Daten gespeichert werden.  Dazu gehören Protokolle, Support-Pakete, Backups und alle anderen zusätzlichen Daten.  Beispiel: `C:\ProgramData\NetApp\OnCommandAppData\`



Sie können auf die Web-Benutzeroberfläche zugreifen, um die Ersteinrichtung von Unified Manager durchzuführen, wie im Abschnittlink:../config/concept_configure_unified_manager.html["Konfigurieren von Active IQ Unified Manager"] .
