---
permalink: install-windows/task_uninstall_unified_manager_win.html 
sidebar: sidebar 
keywords: uninstall, unified manager 
summary: Sie können Unified Manager mithilfe des Assistenten „Programme und Funktionen“ deinstallieren oder eine unbeaufsichtigte Deinstallation über die Befehlszeilenschnittstelle durchführen. 
---
= Deinstallieren Sie Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Sie können Unified Manager mithilfe des Assistenten „Programme und Funktionen“ deinstallieren oder eine unbeaufsichtigte Deinstallation über die Befehlszeilenschnittstelle durchführen.

.Bevor Sie beginnen
* Sie müssen über Windows-Administratorrechte verfügen.
* Alle Cluster (Datenquellen) müssen vom Unified Manager-Server entfernt werden, bevor die Software deinstalliert wird.
* Sie sollten die Firewall-Regeln, die zum Zulassen oder Blockieren des MySQL-Ports 3306 erstellt wurden, manuell löschen.  Die Firewall-Regeln werden nicht automatisch gelöscht.


.Schritte
. Deinstallieren Sie Unified Manager, indem Sie eine der folgenden Optionen auswählen:
+
** Wenn Sie Unified Manager über den Assistenten *Programme und Funktionen* deinstallieren, führen Sie die folgenden Schritte aus:
+
... Navigieren Sie zu *Systemsteuerung* > *Programme und Funktionen*.
... Wählen Sie Active IQ Unified Manager und klicken Sie auf *Deinstallieren*.


** Wenn Sie Unified Manager über die Befehlszeile deinstallieren, führen Sie die folgenden Schritte aus:
+
... Melden Sie sich mit Administratorrechten bei der Windows-Befehlszeile an.
... Navigieren Sie zum Active IQ Unified Manager -Verzeichnis und führen Sie den folgenden Befehl aus:
+
`+msiexec /x {A78760DB-7EC0-4305-97DB-E4A89CDFF4E1} /qn /l*v %systemdrive%\UmUnInstall.log+`

+
Wenn die Benutzerkontensteuerung (UAC) auf dem Server aktiviert ist und Sie als Domänenbenutzer angemeldet sind, müssen Sie die Deinstallationsmethode über die Befehlszeile verwenden.

+
Unified Manager wird von Ihrem System deinstalliert.





. Deinstallieren Sie die folgenden Pakete und Daten von Drittanbietern, die bei der Deinstallation von Unified Manager nicht entfernt werden:
+
** Pakete von Drittanbietern: JRE, MySQL, Microsoft Visual C 2015 Redistributable, Python und 7zip
** Von Unified Manager generierte MySQL-Anwendungsdaten
** Anwendungsprotokolle und Inhalte des Anwendungsdatenverzeichnisses



