---
permalink: install-windows/task_unattended_installation_of_unified_manager.html 
sidebar: sidebar 
keywords: perform, unattended, installation, unified manager 
summary: Sie können Unified Manager ohne Benutzereingriff über die Befehlszeilenschnittstelle installieren.  Sie können die unbeaufsichtigte Installation abschließen, indem Sie die Parameter in Schlüssel-Wert-Paaren übergeben. 
---
= Führen Sie eine unbeaufsichtigte Installation von Unified Manager durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager ohne Benutzereingriff über die Befehlszeilenschnittstelle installieren.  Sie können die unbeaufsichtigte Installation abschließen, indem Sie die Parameter in Schlüssel-Wert-Paaren übergeben.

.Schritte
. Melden Sie sich mit dem standardmäßigen lokalen Administratorkonto bei der Windows-Befehlszeilenschnittstelle an.
. Navigieren Sie zu dem Speicherort, an dem Sie Unified Manager installieren möchten, und wählen Sie eine der folgenden Optionen:
+
[cols="4a,4a"]
|===
| Option | Anweisungen 


 a| 
Wenn Pakete von Drittanbietern vorinstalliert sind
 a| 
`ActiveIQUnifiedManager-x.y.exe /V"MYSQL_PASSWORD=mysql_password INSTALLDIR=\"Installation directory\" MYSQL_DATA_DIR=\"MySQL data directory\" MAINTENANCE_PASSWORD=maintenance_password MAINTENANCE_USERNAME=maintenance_username /qn /l*v CompletePathForLogFile"`

*Beispiel:*

`ActiveIQUnifiedManager.exe /s /v"MYSQL_PASSWORD=netapp21! INSTALLDIR=\"C:\Program Files\NetApp\" MYSQL_DATA_DIR=\"C:\ProgramData\MYSQL\MySQLServer\" MAINTENANCE_PASSWORD=******* MAINTENANCE_USERNAME=admin /qn /l*v C:\install.log"`



 a| 
Wenn keine Pakete von Drittanbietern installiert sind
 a| 
`ActiveIQUnifiedManager-x.y.exe /V"MYSQL_PASSWORD=mysql_password INSTALLDIR=\"Installation directory\" MYSQL_DATA_DIR=\"MySQL data directory\" MAINTENANCE_PASSWORD=maintenance_password MAINTENANCE_USERNAME=maintenance_username /qr /l*v CompletePathForLogFile"`

*Beispiel:*

`ActiveIQUnifiedManager.exe /s /v"MYSQL_PASSWORD=netapp21! INSTALLDIR=\"C:\Program Files\NetApp\" MYSQL_DATA_DIR=\"C:\ProgramData\MYSQL\MySQLServer\" MAINTENANCE_PASSWORD=******* MAINTENANCE_USERNAME=admin /qr /l*v C:\install.log"`

|===
+
Der `/qr` Option aktiviert den Ruhemodus mit einer reduzierten Benutzeroberfläche.  Es wird eine einfache Benutzeroberfläche angezeigt, die den Installationsfortschritt anzeigt.  Sie werden nicht zu Eingaben aufgefordert.  Wenn Drittanbieterpakete wie JRE, MySQL und 7zip nicht vorinstalliert sind, sollten Sie die `/qr` Option.  Die Installation schlägt fehl, wenn `/qn` Option wird auf einem Server verwendet, auf dem keine Pakete von Drittanbietern installiert sind.

+
Der `/qn` Option aktiviert den Ruhemodus ohne Benutzeroberfläche.  Während der Installation werden keine Benutzeroberfläche oder Details angezeigt.  Sie sollten nicht verwenden die `/qn` Option, wenn keine Pakete von Drittanbietern installiert sind.

. Melden Sie sich mit der folgenden URL bei der Web-Benutzeroberfläche von Unified Manager an:
+
`\https://IP address`


