---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: Sie können das instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde.  Sie können das Kennwort optional zurücksetzen, falls Ihre Site diese Sicherheitsfunktion benötigt, um die Installationseinstellung des Unified Managers zu überschreiben.  Dieser Vorgang ändert auch das Kennwort, das JBoss für den Zugriff auf MySQL verwendet. 
---
= Ändern des JBoss-Passworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde.  Sie können das Kennwort optional zurücksetzen, falls Ihre Site diese Sicherheitsfunktion benötigt, um die Installationseinstellung des Unified Managers zu überschreiben.  Dieser Vorgang ändert auch das Kennwort, das JBoss für den Zugriff auf MySQL verwendet.

.Bevor Sie beginnen
* Sie sollten über Windows-Administratorrechte für das System verfügen, auf dem Unified Manager installiert ist.
* Sie sollten das Passwort für den MySQL-Root-Benutzer haben.
* Sie sollten auf die von NetApp bereitgestellte `password.bat` Skript im Verzeichnis
+
`C:\Program Files\NetApp\essentials\bin`.



.Schritte
. Melden Sie sich als Administratorbenutzer auf dem Unified Manager-Hostcomputer an.
. Verwenden Sie die Windows-Dienstekonsole, um die folgenden Unified Manager-Dienste zu stoppen:
+
** NetApp Active IQ Acquisition Service (Ocie-au)
** NetApp Active IQ Management Server-Dienst (Oncommandsvc)


. Starten Sie die `password.bat` Skript zum Starten des Kennwortänderungsprozesses:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Geben Sie bei der entsprechenden Aufforderung das MySQL-Root-Benutzerkennwort ein.
. Geben Sie bei entsprechender Aufforderung das neue JBoss-Benutzerkennwort ein und geben Sie es zur Bestätigung erneut ein.
+
Beachten Sie, dass das Passwort zwischen 8 und 16 Zeichen lang sein sollte und mindestens eine Ziffer, einen Großbuchstaben, einen Kleinbuchstaben und mindestens eines dieser Sonderzeichen enthalten muss:

+
`+!@%^*-_+=[]:<>.?/~+`

. Wenn das Skript abgeschlossen ist, starten Sie die Unified Manager-Dienste mithilfe der Windows-Dienstekonsole:
+
** NetApp Active IQ Management Server-Dienst (Oncommandsvc)
** NetApp Active IQ Acquisition Service (Ocie-au)


. Nachdem alle Dienste gestartet wurden, können Sie sich bei der Unified Manager-Benutzeroberfläche anmelden.

