---
permalink: config/concept_install_https_certificate_generated_using_external_tools.html 
sidebar: sidebar 
keywords: install, HTTPS, certificate, generated from external tools 
summary: Sie können selbstsignierte oder von einer Zertifizierungsstelle signierte Zertifikate installieren, die mit einem externen Tool wie OpenSSL, BoringSSL oder LetsEncrypt generiert wurden. 
---
= Installieren Sie ein mit externen Tools generiertes HTTPS-Zertifikat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können selbstsignierte oder von einer Zertifizierungsstelle signierte Zertifikate installieren, die mit einem externen Tool wie OpenSSL, BoringSSL oder LetsEncrypt generiert wurden.

Sie sollten den privaten Schlüssel zusammen mit der Zertifikatskette laden, da es sich bei diesen Zertifikaten um extern generierte öffentlich-private Schlüsselpaare handelt.  Die zulässigen Schlüsselpaar-Algorithmen sind „`RSA`“ und „`EC`“.  Die Option *HTTPS-Zertifikat installieren* ist auf der Seite „HTTPS-Zertifikate“ im Abschnitt „Allgemein“ verfügbar.  Die Datei, die Sie hochladen, sollte das folgende Eingabeformat haben.

. Privater Schlüssel des Servers, der zum Active IQ Unified Manager Host gehört
. Zertifikat des Servers, das zum privaten Schlüssel passt
. Zertifikat der CAs in umgekehrter Reihenfolge bis zur Wurzel, die zum Signieren des obigen Zertifikats verwendet werden




== Format zum Laden eines Zertifikats mit einem EC-Schlüsselpaar

Die zulässigen Kurven sind „prime256v1“ und „secp384r1“.  Musterzertifikat mit extern generiertem EC-Paar:

[listing]
----
 -----BEGIN EC PRIVATE KEY-----
<EC private key of Server>
-----END EC PRIVATE KEY-----
----
[listing]
----
 -----BEGIN CERTIFICATE-----
 <Server certificate>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #1 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #2 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Root signing certificate>
 -----END CERTIFICATE-----
----


== Format zum Laden eines Zertifikats mit einem RSA-Schlüsselpaar

Die zulässigen Schlüsselgrößen für das zum Host-Zertifikat gehörende RSA-Schlüsselpaar sind 2048, 3072 und 4096. Zertifikat mit einem extern generierten *RSA-Schlüsselpaar*:

[listing]
----
-----BEGIN RSA PRIVATE KEY-----
 <RSA private key of Server>
 -----END RSA PRIVATE KEY-----
 -----BEGIN CERTIFICATE-----
 <Server certificate>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #1 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #2 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Root signing certificate>
 -----END CERTIFICATE-----
----
Nachdem das Zertifikat hochgeladen wurde, sollten Sie die Active IQ Unified Manager Instanz neu starten, damit die Änderungen wirksam werden.



== Prüfungen beim Hochladen extern erstellter Zertifikate

Das System führt beim Hochladen eines mit externen Tools erstellten Zertifikats Prüfungen durch.  Wenn eine der Prüfungen fehlschlägt, wird das Zertifikat abgelehnt.  Es ist auch eine Validierung für die Zertifikate enthalten, die aus der CSR innerhalb des Produkts generiert werden, und für Zertifikate, die mit externen Tools generiert werden.

* Der private Schlüssel in der Eingabe wird anhand des Host-Zertifikats in der Eingabe validiert.
* Der Common Name (CN) im Host-Zertifikat wird mit dem FQDN des Hosts abgeglichen.
* Der allgemeine Name (CN) des Hostzertifikats darf nicht leer sein und darf nicht auf „localhost“ gesetzt werden.
* Das Gültigkeitsbeginndatum sollte nicht in der Zukunft und das Gültigkeitsablaufdatum des Zertifikats nicht in der Vergangenheit liegen.
* Wenn eine Zwischenzertifizierungsstelle oder Zertifizierungsstelle vorhanden ist, darf das Gültigkeitsbeginndatum des Zertifikats nicht in der Zukunft und das Gültigkeitsablaufdatum nicht in der Vergangenheit liegen.


[NOTE]
====
Der private Schlüssel in der Eingabe sollte nicht verschlüsselt sein.  Wenn verschlüsselte private Schlüssel vorhanden sind, werden diese vom System abgelehnt.

====
Beispiel 1

[listing]
----
----BEGIN ENCRYPTED PRIVATE KEY-----
<Encrypted private key>
-----END ENCRYPTED PRIVATE KEY-----
----
Beispiel 2

[listing]
----
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
<content here>
-----END RSA PRIVATE KEY-----
----
Beispiel 3

[listing]
----
-----BEGIN EC PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
<content here>
-----END EC PRIVATE KEY-----
----
Wenn die Installation des Zertifikats fehlschlägt, lesen Sie den folgenden Knowledge Base-Artikel (KB):https://kb.netapp.com/mgmt/AIQUM/AIQUM_fails_to_install_externally_generated_certificate["ActiveIQ Unified Manager kann ein extern generiertes Zertifikat nicht installieren"^]
