---
permalink: config/concept_what_role_based_access_control_does.html 
sidebar: sidebar 
keywords: role-based, access, control 
summary: 'Die rollenbasierte Zugriffskontrolle (RBAC) ermöglicht Administratoren die Verwaltung von Benutzergruppen durch die Definition von Rollen.  Wenn Sie den Zugriff auf bestimmte Funktionen auf ausgewählte Administratoren beschränken müssen, müssen Sie für diese Administratorkonten einrichten.  Wenn Sie die Informationen, die Administratoren anzeigen können, und die Vorgänge, die sie ausführen können, einschränken möchten, müssen Sie den von Ihnen erstellten Administratorkonten Rollen zuweisen.' 
---
= Was rollenbasierte Zugriffskontrolle bewirkt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die rollenbasierte Zugriffskontrolle (RBAC) ermöglicht Administratoren die Verwaltung von Benutzergruppen durch die Definition von Rollen.  Wenn Sie den Zugriff auf bestimmte Funktionen auf ausgewählte Administratoren beschränken müssen, müssen Sie für diese Administratorkonten einrichten.  Wenn Sie die Informationen, die Administratoren anzeigen können, und die Vorgänge, die sie ausführen können, einschränken möchten, müssen Sie den von Ihnen erstellten Administratorkonten Rollen zuweisen.

Der Verwaltungsserver verwendet RBAC für die Benutzeranmeldung und Rollenberechtigungen.  Wenn Sie die Standardeinstellungen des Verwaltungsservers für den Administratorbenutzerzugriff nicht geändert haben, müssen Sie sich nicht anmelden, um sie anzuzeigen.

Wenn Sie einen Vorgang starten, der bestimmte Berechtigungen erfordert, werden Sie vom Verwaltungsserver aufgefordert, sich anzumelden. Um beispielsweise Administratorkonten zu erstellen, müssen Sie sich mit dem Kontozugriff des Anwendungsadministrators anmelden.
