---
permalink: config/concept_maintenance_console_menu.html 
sidebar: sidebar 
keywords: maintenance, console, menus 
summary: Die Wartungskonsole besteht aus verschiedenen Menüs, mit denen Sie spezielle Funktionen und Konfigurationseinstellungen des Unified Manager-Servers warten und verwalten können. 
---
= Menüs der Wartungskonsole
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Wartungskonsole besteht aus verschiedenen Menüs, mit denen Sie spezielle Funktionen und Konfigurationseinstellungen des Unified Manager-Servers warten und verwalten können.

Abhängig vom Betriebssystem, auf dem Sie Unified Manager installiert haben, besteht die Wartungskonsole aus den folgenden Menüs:

* Upgrade von Unified Manager (nur VMware)
* Netzwerkkonfiguration (nur VMware)
* Systemkonfiguration (nur VMware)
+
.. Support/Diagnose
.. Serverzertifikat zurücksetzen
.. Externer Datenanbieter
.. Backup-Wiederherstellung
.. Konfiguration des Leistungsabfrageintervalls
.. Deaktivieren der SAML-Authentifizierung
.. Anwendungsports anzeigen/ändern
.. Debug-Protokollkonfiguration
.. Steuern Sie den Zugriff auf MySQL-Port 3306
.. Ausfahrt




Sie wählen die Nummer aus der Liste aus, um auf die jeweilige Menüoption zuzugreifen.  Wählen Sie beispielsweise für die Sicherung und Wiederherstellung _4_ aus.
