---
permalink: config/reference_saml_authentication_page_um.html 
sidebar: sidebar 
keywords: saml authentication page 
summary: 'Sie können die Seite „SAML-Authentifizierung“ verwenden, um Unified Manager so zu konfigurieren, dass Remote-Benutzer mithilfe von SAML über einen sicheren Identitätsanbieter (IdP) authentifiziert werden, bevor sie sich bei der Web-Benutzeroberfläche von Unified Manager anmelden können.' 
---
= SAML-Authentifizierungsseite
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Seite „SAML-Authentifizierung“ verwenden, um Unified Manager so zu konfigurieren, dass Remote-Benutzer mithilfe von SAML über einen sicheren Identitätsanbieter (IdP) authentifiziert werden, bevor sie sich bei der Web-Benutzeroberfläche von Unified Manager anmelden können.

* Sie müssen über die Rolle „Anwendungsadministrator“ verfügen, um die SAML-Konfiguration zu erstellen oder zu ändern.
* Sie müssen die Remote-Authentifizierung konfiguriert haben.
* Sie müssen mindestens einen Remote-Benutzer oder eine Remote-Gruppe konfiguriert haben.


Nachdem die Remote-Authentifizierung und die Remote-Benutzer konfiguriert wurden, können Sie das Kontrollkästchen SAML-Authentifizierung aktivieren aktivieren, um die Authentifizierung mithilfe eines sicheren Identitätsanbieters zu aktivieren.

* *IdP-URI*
+
Die URI für den Zugriff auf den IdP vom Unified Manager-Server.  Beispiel-URIs sind unten aufgeführt.

+
ADFS-Beispiel-URI:

+
`+https://win2016-dc.ntap2016.local/federationmetadata/2007-06/federationmetadata.xml+`

+
Shibboleth-Beispiel-URI:

+
`+https://centos7.ntap2016.local/idp/shibboleth+`

* *IdP-Metadaten*
+
Die IdP-Metadaten im XML-Format.

+
Wenn die IdP-URL vom Unified Manager-Server aus zugänglich ist, können Sie auf die Schaltfläche *IdP-Metadaten abrufen* klicken, um dieses Feld auszufüllen.

* *Hostsystem (FQDN)*
+
Der FQDN des Unified Manager-Hostsystems, wie während der Installation definiert.  Sie können diesen Wert bei Bedarf ändern.

* *Host-URI*
+
Die URI für den Zugriff auf das Unified Manager-Hostsystem vom IdP aus.

* *Host-Metadaten*
+
Die Metadaten des Hostsystems im XML-Format.


