---
permalink: config/reference_system_configuration_menu.html 
sidebar: sidebar 
keywords: system, configuration, menu 
summary: Über das Menü „Systemkonfiguration“ können Sie Ihre virtuelle Appliance verwalten. Es bietet verschiedene Optionen, beispielsweise die Anzeige des Serverstatus sowie das Neustarten und Herunterfahren der virtuellen Maschine. 
---
= Menü „Systemkonfiguration“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über das Menü „Systemkonfiguration“ können Sie Ihre virtuelle Appliance verwalten. Es bietet verschiedene Optionen, beispielsweise die Anzeige des Serverstatus sowie das Neustarten und Herunterfahren der virtuellen Maschine.

[NOTE]
====
Wenn Unified Manager auf einem Linux- oder Microsoft Windows-System installiert ist, ist in diesem Menü nur die Option „Aus einer Unified Manager-Sicherung wiederherstellen“ verfügbar.

====
Folgende Menüoptionen stehen zur Verfügung:

* *Serverstatus anzeigen*
+
Zeigt den aktuellen Serverstatus an.  Zu den Statusoptionen gehören „Wird ausgeführt“ und „Wird nicht ausgeführt“.

+
Wenn der Server nicht läuft, müssen Sie sich möglicherweise an den technischen Support wenden.

* *Virtuelle Maschine neu starten*
+
Startet die virtuelle Maschine neu und stoppt alle Dienste.  Nach dem Neustart werden die virtuelle Maschine und die Dienste neu gestartet.

* *Virtuelle Maschine herunterfahren*
+
Fährt die virtuelle Maschine herunter und stoppt alle Dienste.

+
Sie können diese Option nur über die Konsole der virtuellen Maschine auswählen.

* *Benutzerkennwort <angemeldeter Benutzer> ändern*
+
Ändert das Passwort des aktuell angemeldeten Benutzers, was nur der Wartungsbenutzer sein kann.

* *Datenträgergröße erhöhen*
+
Erhöht die Größe der Datenfestplatte (Festplatte 3) in der virtuellen Maschine.

* *Größe der Swap-Disk erhöhen*
+
Erhöht die Größe der Auslagerungsfestplatte (Festplatte 2) in der virtuellen Maschine.

* *Zeitzone ändern*
+
Ändert die Zeitzone auf Ihren Standort.

* *NTP-Server ändern*
+
Ändert die NTP-Servereinstellungen, z. B. IP-Adresse oder vollqualifizierter Domänenname (FQDN).

* *NTP-Dienst ändern*
+
Schaltet um zwischen `ntp` Und `systemd-timesyncd` Dienstleistungen.

* *Wiederherstellung aus einem Unified Manager-Backup*
+
Stellt die Unified Manager-Datenbank und Konfigurationseinstellungen aus einer zuvor gesicherten Version wieder her.

* *Serverzertifikat zurücksetzen*
+
Setzt das Sicherheitszertifikat des Servers zurück.

* *Hostnamen ändern*
+
Ändert den Namen des Hosts, auf dem die virtuelle Appliance installiert ist.

* *Zurück*
+
Verlässt das Systemkonfigurationsmenü und kehrt zum Hauptmenü zurück.

* *Ausfahrt*
+
Beendet das Wartungskonsolenmenü.


