---
permalink: config/reference_support_and_diagnostics_menu.html 
sidebar: sidebar 
keywords: support and diagnostics, menu 
summary: Über das Menü „Support und Diagnose“ können Sie ein Supportpaket erstellen, das Sie zur Unterstützung bei der Fehlerbehebung an den technischen Support senden können. 
---
= Menü „Support und Diagnose“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über das Menü „Support und Diagnose“ können Sie ein Supportpaket erstellen, das Sie zur Unterstützung bei der Fehlerbehebung an den technischen Support senden können.

Folgende Menüpunkte stehen zur Verfügung:

* *Light Support Bundle erstellen*
+
Ermöglicht Ihnen die Erstellung eines schlanken Support-Pakets, das lediglich 30 Tage Protokolle und Konfigurationsdatenbankaufzeichnungen enthält – Leistungsdaten, Erfassungsaufzeichnungsdateien und Server-Heap-Dumps sind nicht enthalten.

* *Support-Paket erstellen*
+
Ermöglicht Ihnen die Erstellung eines vollständigen Support-Pakets (7-Zip-Datei) mit Diagnoseinformationen im Home-Verzeichnis des Diagnosebenutzers.  Wenn Ihr System mit dem Internet verbunden ist, können Sie das Support-Paket auch auf NetApp hochladen.

+
Die Datei enthält von einer AutoSupport Nachricht generierte Informationen, den Inhalt der Unified Manager-Datenbank, detaillierte Daten zu den internen Komponenten des Unified Manager-Servers und ausführliche Protokolle, die normalerweise nicht in AutoSupport -Nachrichten oder im Lightweight-Support-Paket enthalten sind.


