---
permalink: config/task_update_saml_authentication_after_um_certificate_change.html 
sidebar: sidebar 
keywords: update, saml, authentication, settings, unified manager, security, certificate, change 
summary: Jede Änderung am auf dem Unified Manager-Server installierten HTTPS-Sicherheitszertifikat erfordert eine Aktualisierung der Konfigurationseinstellungen der SAML-Authentifizierung.  Das Zertifikat wird aktualisiert, wenn Sie das Hostsystem umbenennen, dem Hostsystem eine neue IP-Adresse zuweisen oder das Sicherheitszertifikat für das System manuell ändern. 
---
= Aktualisieren Sie die SAML-Authentifizierungseinstellungen nach der Änderung des Unified Manager-Sicherheitszertifikats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jede Änderung am auf dem Unified Manager-Server installierten HTTPS-Sicherheitszertifikat erfordert eine Aktualisierung der Konfigurationseinstellungen der SAML-Authentifizierung.  Das Zertifikat wird aktualisiert, wenn Sie das Hostsystem umbenennen, dem Hostsystem eine neue IP-Adresse zuweisen oder das Sicherheitszertifikat für das System manuell ändern.

Nachdem das Sicherheitszertifikat geändert und der Unified Manager-Server neu gestartet wurde, funktioniert die SAML-Authentifizierung nicht und Benutzer können nicht auf die grafische Benutzeroberfläche von Unified Manager zugreifen.  Sie müssen die SAML-Authentifizierungseinstellungen sowohl auf dem IdP-Server als auch auf dem Unified Manager-Server aktualisieren, um den Zugriff auf die Benutzeroberfläche wieder zu aktivieren.

.Schritte
. Melden Sie sich bei der Wartungskonsole an.
. Geben Sie im *Hauptmenü* die Nummer für die Option *SAML-Authentifizierung deaktivieren* ein.
+
Es wird eine Meldung angezeigt, in der Sie bestätigen müssen, dass Sie die SAML-Authentifizierung deaktivieren und Unified Manager neu starten möchten.

. Starten Sie die Unified Manager-Benutzeroberfläche mit dem aktualisierten FQDN oder der aktualisierten IP-Adresse, akzeptieren Sie das aktualisierte Serverzertifikat in Ihrem Browser und melden Sie sich mit den Anmeldeinformationen des Wartungsbenutzers an.
. Wählen Sie auf der Seite *Setup/Authentifizierung* die Registerkarte *SAML-Authentifizierung* und konfigurieren Sie die IdP-Verbindung.
. Kopieren Sie die URI der Hostmetadaten von Unified Manager oder speichern Sie die Hostmetadaten in einer XML-Textdatei.
. Klicken Sie auf *Speichern*.
+
In einem Meldungsfeld können Sie bestätigen, dass Sie die Konfiguration abschließen und Unified Manager neu starten möchten.

. Klicken Sie auf *Bestätigen und Abmelden* und Unified Manager wird neu gestartet.
. Greifen Sie auf Ihren IdP-Server zu und geben Sie die URI und Metadaten des Unified Manager-Servers ein, um die Konfiguration abzuschließen.
+
[cols="2*"]
|===
| Identitätsanbieter | Konfigurationsschritte 


 a| 
ADFS
 a| 
.. Löschen Sie den vorhandenen Vertrauenseintrag der vertrauenden Seite in der ADFS-Verwaltungs-GUI.
.. Fügen Sie einen neuen Vertrauenseintrag der vertrauenden Partei hinzu, indem Sie `saml_sp_metadata.xml` vom aktualisierten Unified Manager-Server.
.. Definieren Sie die drei Anspruchsregeln, die Unified Manager benötigt, um ADFS-SAML-Antworten für diesen Vertrauenseintrag der vertrauenden Seite zu analysieren.
.. Starten Sie den ADFS-Windows-Dienst neu.




 a| 
Shibboleth
 a| 
.. Aktualisieren Sie den neuen FQDN des Unified Manager-Servers in `attribute-filter.xml` Und `relying-party.xml` Dateien.
.. Starten Sie den Apache Tomcat-Webserver neu und warten Sie, bis Port 8005 online ist.


|===
. Melden Sie sich bei Unified Manager an und überprüfen Sie, ob die SAML-Authentifizierung über Ihren IdP wie erwartet funktioniert.

