---
permalink: config/task_enable_remote_logging_of_audit_logs.html 
sidebar: sidebar 
keywords: enable, remote, logging, audit, logs 
summary: Sie können das Kontrollkästchen „Remote-Protokollierung aktivieren“ im Dialogfeld „Überwachungsprotokolle konfigurieren“ aktivieren, um die Remote-Überwachungsprotokollierung zu aktivieren.  Mit dieser Funktion können Sie Überwachungsprotokolle auf einen Remote-Syslog-Server übertragen.  Auf diese Weise können Sie Ihre Prüfprotokolle verwalten, wenn der Speicherplatz begrenzt ist. 
---
= Aktivieren der Remote-Protokollierung von Überwachungsprotokollen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Kontrollkästchen *Remote-Protokollierung aktivieren* im Dialogfeld „Audit-Protokolle konfigurieren“ aktivieren, um die Remote-Audit-Protokollierung zu aktivieren.  Mit dieser Funktion können Sie Überwachungsprotokolle auf einen Remote-Syslog-Server übertragen.  Auf diese Weise können Sie Ihre Prüfprotokolle verwalten, wenn der Speicherplatz begrenzt ist.

Die Remote-Protokollierung von Prüfprotokollen bietet eine manipulationssichere Sicherung für den Fall, dass die Prüfprotokolldateien auf dem Active IQ Unified Manager Server manipuliert werden.

.Schritte
. Aktivieren Sie im Dialogfeld *Auditprotokolle konfigurieren* das Kontrollkästchen *Remoteprotokollierung aktivieren*.
+
Es werden zusätzliche Felder zum Konfigurieren der Remote-Protokollierung angezeigt.

. Geben Sie den *HOSTNAME* und *PORT* des Remote-Servers ein, zu dem Sie eine Verbindung herstellen möchten.
. Klicken Sie im Feld *SERVER CA CERTIFICATE* auf *BROWSE*, um ein öffentliches Zertifikat des Zielservers auszuwählen.
+
Das Zertifikat sollte hochgeladen werden in `.pem` Format.  Dieses Zertifikat sollte vom Ziel-Syslog-Server bezogen werden und nicht abgelaufen sein.  Das Zertifikat sollte den ausgewählten „Hostnamen“ als Teil des `SubjectAltName` (SAN)-Attribut.

. Geben Sie die Werte für die folgenden Felder ein: *CHARSET*, *CONNECTION TIMEOUT*, *RECONNECTION DELAY*.
+
Die Werte für diese Felder sollten in Millisekunden angegeben werden.

. Wählen Sie in den Feldern *FORMAT* und *PROTOKOLL* das gewünschte Syslog-Format und die TLS-Protokollversion aus.
. Aktivieren Sie das Kontrollkästchen *Client-Authentifizierung aktivieren*, wenn der Ziel-Syslog-Server eine zertifikatbasierte Authentifizierung erfordert.
+
Sie müssen das Client-Authentifizierungszertifikat herunterladen und auf den Syslog-Server hochladen, bevor Sie die Audit-Log-Konfiguration speichern, da sonst die Verbindung fehlschlägt.  Je nach Typ des Syslog-Servers müssen Sie möglicherweise einen Hash des Client-Authentifizierungszertifikats erstellen.

+
Beispiel: syslog-ng erfordert einen <hash> des Zertifikats, das mit dem Befehl erstellt werden soll `openssl x509 -noout -hash -in cert.pem` , und dann sollten Sie das Client-Authentifizierungszertifikat symbolisch mit einer Datei verknüpfen, die nach dem <Hash> .0 benannt ist.

. Klicken Sie auf *Speichern*, um die Verbindung mit Ihrem Server zu konfigurieren und die Remote-Protokollierung zu aktivieren.
+
Sie werden zur Seite „Audit-Protokolle“ weitergeleitet.

+
[NOTE]
====
Der Wert *Verbindungs-Timeout* kann die Konfiguration beeinflussen.  Wenn die Konfiguration länger als der definierte Wert zum Antworten benötigt, kann dies aufgrund eines Verbindungsfehlers zu einem Konfigurationsfehler führen.  Um eine erfolgreiche Verbindung herzustellen, erhöhen Sie den Wert *Verbindungs-Timeout* und versuchen Sie die Konfiguration erneut.

====

