---
permalink: config/task_change_maintenance_user_password_on_windows.html 
sidebar: sidebar 
keywords: change, maintenance, user, password, windows 
summary: Sie können das Wartungsbenutzerkennwort von Unified Manager bei Bedarf ändern. 
---
= Ändern des Wartungsbenutzerkennworts unter Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Wartungsbenutzerkennwort von Unified Manager bei Bedarf ändern.

.Schritte
. Klicken Sie auf der Anmeldeseite der Unified Manager-Webbenutzeroberfläche auf *Passwort vergessen*.
+
Es wird eine Seite angezeigt, auf der Sie nach dem Namen des Benutzers gefragt werden, dessen Kennwort Sie zurücksetzen möchten.

. Geben Sie den Benutzernamen ein und klicken Sie auf *Senden*.
+
Eine E-Mail mit einem Link zum Zurücksetzen des Kennworts wird an die für diesen Benutzernamen definierte E-Mail-Adresse gesendet.

. Klicken Sie in der E-Mail auf den Link *Passwort zurücksetzen* und legen Sie das neue Passwort fest.
. Kehren Sie zur Web-Benutzeroberfläche zurück und melden Sie sich mit dem neuen Kennwort bei Unified Manager an.

