---
permalink: config/task_install_ca_signed_and_returned_https_certificate.html 
sidebar: sidebar 
keywords: install, ca signed, returned, https, certificate 
summary: Sie können ein Sicherheitszertifikat hochladen und installieren, nachdem es von einer Zertifizierungsstelle signiert und zurückgegeben wurde.  Die Datei, die Sie hochladen und installieren, muss eine signierte Version des vorhandenen selbstsignierten Zertifikats sein.  Ein von einer Zertifizierungsstelle signiertes Zertifikat trägt dazu bei, Man-in-the-Middle-Angriffe zu verhindern und bietet einen besseren Sicherheitsschutz als ein selbstsigniertes Zertifikat. 
---
= Installieren Sie ein von einer CA signiertes und zurückgegebenes HTTPS-Zertifikat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Sicherheitszertifikat hochladen und installieren, nachdem es von einer Zertifizierungsstelle signiert und zurückgegeben wurde.  Die Datei, die Sie hochladen und installieren, muss eine signierte Version des vorhandenen selbstsignierten Zertifikats sein.  Ein von einer Zertifizierungsstelle signiertes Zertifikat trägt dazu bei, Man-in-the-Middle-Angriffe zu verhindern und bietet einen besseren Sicherheitsschutz als ein selbstsigniertes Zertifikat.

*Was .Bevor Sie beginnen

Sie müssen die folgenden Aktionen abgeschlossen haben:

* Die Certificate Signing Request-Datei heruntergeladen und von einer Zertifizierungsstelle signieren lassen
* Die Zertifikatskette wurde im PEM-Format gespeichert
* Alle Zertifikate in der Kette eingeschlossen, vom Unified Manager-Serverzertifikat bis zum Stammsignaturzertifikat, einschließlich aller vorhandenen Zwischenzertifikate


Sie müssen über die Rolle „Anwendungsadministrator“ verfügen.

[NOTE]
====
Wenn die Gültigkeit des Zertifikats, für das ein CSR erstellt wurde, mehr als 397 Tage beträgt, wird die Gültigkeit von der Zertifizierungsstelle vor der Unterzeichnung und Rücksendung des Zertifikats auf 397 Tage verkürzt.

====
.Schritte
. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *HTTPS-Zertifikat*.
. Klicken Sie auf *HTTPS-Zertifikat installieren*.
. Klicken Sie im angezeigten Dialogfeld auf *Datei auswählen...*, um die hochzuladende Datei zu suchen.
. Wählen Sie die Datei aus und klicken Sie dann auf *Installieren*, um die Datei zu installieren.
+
Weitere Informationen finden Sie unterlink:concept_install_https_certificate_generated_using_external_tools.html["Installieren eines mit externen Tools generierten HTTPS-Zertifikats"] .





[[example-certificate-chain]]
== Beispiel einer Zertifikatskette

Das folgende Beispiel zeigt, wie die Zertifikatskettendatei aussehen könnte:

[listing]
----
-----BEGIN CERTIFICATE-----
<*Server certificate*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#1 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#2 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Root signing certificate*>
-----END CERTIFICATE-----
----