---
permalink: config/task_change_umadmin_password_on_rhel.html 
sidebar: sidebar 
keywords: change, umadmin, password, linux systems 
summary: Aus Sicherheitsgründen müssen Sie das Standardkennwort für den Unified Manager-Benutzer umadmin unmittelbar nach Abschluss des Installationsvorgangs ändern.  Bei Bedarf können Sie das Passwort später jederzeit wieder ändern. 
---
= Ändern des Umadmin-Passworts auf Linux-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aus Sicherheitsgründen müssen Sie das Standardkennwort für den Unified Manager-Benutzer umadmin unmittelbar nach Abschluss des Installationsvorgangs ändern.  Bei Bedarf können Sie das Passwort später jederzeit wieder ändern.

.Bevor Sie beginnen
* Unified Manager muss auf einem Red Hat Enterprise Linux-Linux-System installiert sein.
* Sie müssen über die Root-Benutzeranmeldeinformationen für das Linux-System verfügen, auf dem Unified Manager installiert ist.


.Schritte
. Melden Sie sich als Root-Benutzer beim Linux-System an, auf dem Unified Manager ausgeführt wird.
. Ändern Sie das Umadmin-Passwort:
+
`passwd umadmin`

+
Das System fordert Sie auf, ein neues Passwort für den Benutzer umadmin einzugeben.


