---
permalink: config/task_configure_unified_manager_to_send_alert_notifications.html 
sidebar: sidebar 
keywords: configure, unified manager, send, alert, notifications 
summary: Sie können Unified Manager so konfigurieren, dass Benachrichtigungen gesendet werden, die Sie über Ereignisse in Ihrer Umgebung informieren.  Bevor Benachrichtigungen gesendet werden können, müssen Sie mehrere andere Unified Manager-Optionen konfigurieren. 
---
= Konfigurieren Sie Unified Manager zum Senden von Warnbenachrichtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager so konfigurieren, dass Benachrichtigungen gesendet werden, die Sie über Ereignisse in Ihrer Umgebung informieren.  Bevor Benachrichtigungen gesendet werden können, müssen Sie mehrere andere Unified Manager-Optionen konfigurieren.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ verfügen.

Nachdem Sie Unified Manager bereitgestellt und die Erstkonfiguration abgeschlossen haben, sollten Sie Ihre Umgebung so konfigurieren, dass basierend auf dem Empfang von Ereignissen Warnungen ausgelöst und Benachrichtigungs-E-Mails oder SNMP-Traps generiert werden.

.Schritte
. link:task_configure_event_notification_settings.html["Konfigurieren der Ereignisbenachrichtigungseinstellungen"].
+
Wenn Sie beim Auftreten bestimmter Ereignisse in Ihrer Umgebung Warnbenachrichtigungen erhalten möchten, müssen Sie einen SMTP-Server konfigurieren und eine E-Mail-Adresse angeben, von der die Warnbenachrichtigung gesendet wird.  Wenn Sie SNMP-Traps verwenden möchten, können Sie diese Option auswählen und die erforderlichen Informationen angeben.

. link:task_enable_remote_authentication.html["Remote-Authentifizierung aktivieren"].
+
Wenn Remote-LDAP- oder Active Directory-Benutzer auf die Unified Manager-Instanz zugreifen und Warnbenachrichtigungen erhalten sollen, müssen Sie die Remote-Authentifizierung aktivieren.

. link:task_add_authentication_servers.html["Authentifizierungsserver hinzufügen"].
+
Sie können Authentifizierungsserver hinzufügen, sodass Remotebenutzer innerhalb des Authentifizierungsservers auf Unified Manager zugreifen können.

. link:task_add_users.html["Benutzer hinzufügen"].
+
Sie können verschiedene Arten von lokalen oder Remote-Benutzern hinzufügen und bestimmte Rollen zuweisen.  Wenn Sie eine Warnung erstellen, weisen Sie einen Benutzer zu, der die Warnbenachrichtigungen erhalten soll.

. link:task_add_alerts.html["Benachrichtigungen hinzufügen"].
+
Nachdem Sie die E-Mail-Adresse zum Senden von Benachrichtigungen hinzugefügt, Benutzer zum Empfangen der Benachrichtigungen hinzugefügt, Ihre Netzwerkeinstellungen konfiguriert und die für Ihre Umgebung erforderlichen SMTP- und SNMP-Optionen konfiguriert haben, können Sie Warnungen zuweisen.


