---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: Bei der ersten Installation von Active IQ Unified Manager wird ein Standard-HTTPS-Zertifikat installiert.  Sie können ein neues HTTPS-Sicherheitszertifikat generieren, das das vorhandene Zertifikat ersetzt. 
---
= Generieren Sie ein HTTPS-Sicherheitszertifikat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der ersten Installation von Active IQ Unified Manager wird ein Standard-HTTPS-Zertifikat installiert.  Sie können ein neues HTTPS-Sicherheitszertifikat generieren, das das vorhandene Zertifikat ersetzt.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ verfügen.

Es kann mehrere Gründe geben, das Zertifikat neu zu generieren, beispielsweise wenn Sie bessere Werte für den Distinguished Name (DN) wünschen, eine höhere Schlüsselgröße oder eine längere Ablaufdauer wünschen oder wenn das aktuelle Zertifikat abgelaufen ist.

Wenn Sie keinen Zugriff auf die Unified Manager-Web-Benutzeroberfläche haben, können Sie das HTTPS-Zertifikat mithilfe der Wartungskonsole mit denselben Werten neu generieren.  Beim Neugenerieren von Zertifikaten können Sie die Schlüsselgröße und die Gültigkeitsdauer des Schlüssels festlegen.  Wenn Sie die `Reset Server Certificate` Option aus der Wartungskonsole, dann wird ein neues HTTPS-Zertifikat erstellt, das 397 Tage gültig ist.  Dieses Zertifikat verfügt über einen RSA-Schlüssel mit einer Größe von 2048 Bit.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *HTTPS-Zertifikat*.
. Klicken Sie auf *HTTPS-Zertifikat neu generieren*.
+
Das Dialogfeld „HTTPS-Zertifikat neu generieren“ wird angezeigt.

. Wählen Sie eine der folgenden Optionen, je nachdem, wie Sie das Zertifikat generieren möchten:
+
[cols="2*"]
|===
| Wenn Sie wollen... | Machen Sie Folgendes... 


 a| 
Zertifikat mit den aktuellen Werten neu generieren
 a| 
Klicken Sie auf die Option *Mit aktuellen Zertifikatattributen neu generieren*.



 a| 
Generieren Sie das Zertifikat mit unterschiedlichen Werten
 a| 
Klicken Sie auf die Option *Aktuelle Zertifikatattribute aktualisieren*.

Wenn Sie keine neuen Werte eingeben, werden in den Feldern „Allgemeiner Name“ und „Alternative Namen“ die Werte aus dem vorhandenen Zertifikat verwendet.  Der „Common Name“ sollte auf den FQDN des Hosts eingestellt werden.  Für die anderen Felder sind keine Werte erforderlich, Sie können jedoch beispielsweise Werte für E-MAIL, FIRMA, ABTEILUNG, Stadt, Bundesland und Land eingeben, wenn diese Werte im Zertifikat eingetragen werden sollen.  Sie können auch aus der verfügbaren SCHLÜSSELGRÖSSE (der Schlüsselalgorithmus ist „RSA“) und der GÜLTIGKEITSDAUER auswählen.

[NOTE]
====
** Die zulässigen Werte für die Schlüsselgröße sind `2048` , `3072` Und `4096` .
** Die Gültigkeitsdauer beträgt mindestens 1 Tag und höchstens 36500 Tage.
+
Obwohl eine Gültigkeitsdauer von 36.500 Tagen zulässig ist, wird empfohlen, eine Gültigkeitsdauer von nicht mehr als 397 Tagen oder 13 Monaten zu verwenden.  Denn wenn Sie eine Gültigkeitsdauer von mehr als 397 Tagen auswählen und planen, eine CSR für dieses Zertifikat zu exportieren und von einer bekannten Zertifizierungsstelle signieren zu lassen, wird die Gültigkeit des signierten Zertifikats, das Ihnen von der Zertifizierungsstelle zurückgegeben wird, auf 397 Tage reduziert.

** Sie können das Kontrollkästchen „Lokale Identifizierungsinformationen ausschließen (z. B. localhost)“ aktivieren, wenn Sie die lokalen Identifizierungsinformationen aus dem Feld „Alternative Namen“ im Zertifikat entfernen möchten.  Wenn dieses Kontrollkästchen aktiviert ist, wird im Feld „Alternative Namen“ nur das verwendet, was Sie in das Feld eingeben.  Wenn dieses Feld leer gelassen wird, enthält das resultierende Zertifikat überhaupt kein Feld für alternative Namen.


====
|===
. Klicken Sie auf *Ja*, um das Zertifikat neu zu generieren.
. Starten Sie den Unified Manager-Server neu, damit das neue Zertifikat wirksam wird.
. Überprüfen Sie die neuen Zertifikatsinformationen, indem Sie das HTTPS-Zertifikat anzeigen.

