---
permalink: config/task_change_unified_manager_host_name_on_vmware.html 
sidebar: sidebar 
keywords: change, unified manager, virtual, appliance, host name 
summary: Dem Netzwerkhost wird bei der ersten Bereitstellung der virtuellen Unified Manager-Appliance ein Name zugewiesen.  Sie können den Hostnamen nach der Bereitstellung ändern.  Wenn Sie den Hostnamen ändern, müssen Sie auch das HTTPS-Zertifikat neu generieren. 
---
= Ändern des Hostnamens der virtuellen Unified Manager-Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dem Netzwerkhost wird bei der ersten Bereitstellung der virtuellen Unified Manager-Appliance ein Name zugewiesen.  Sie können den Hostnamen nach der Bereitstellung ändern.  Wenn Sie den Hostnamen ändern, müssen Sie auch das HTTPS-Zertifikat neu generieren.

.Bevor Sie beginnen
Um diese Aufgaben ausführen zu können, müssen Sie bei Unified Manager als Wartungsbenutzer angemeldet sein oder Ihnen die Rolle des Anwendungsadministrators zugewiesen sein.

Sie können den Hostnamen (oder die Host-IP-Adresse) verwenden, um auf die Unified Manager-Web-Benutzeroberfläche zuzugreifen.  Wenn Sie während der Bereitstellung eine statische IP-Adresse für Ihr Netzwerk konfiguriert haben, haben Sie einen Namen für den Netzwerkhost festgelegt.  Wenn Sie das Netzwerk mit DHCP konfiguriert haben, sollte der Hostname aus dem DNS übernommen werden.  Wenn DHCP oder DNS nicht richtig konfiguriert sind, wird der Hostname „Unified Manager“ automatisch zugewiesen und mit dem Sicherheitszertifikat verknüpft.

Unabhängig davon, wie der Hostname zugewiesen wurde, müssen Sie ein neues Sicherheitszertifikat generieren, wenn Sie den Hostnamen ändern und den neuen Hostnamen für den Zugriff auf die Unified Manager-Web-Benutzeroberfläche verwenden möchten.

Wenn Sie auf die Web-Benutzeroberfläche zugreifen, indem Sie die IP-Adresse des Servers anstelle des Hostnamens verwenden, müssen Sie kein neues Zertifikat generieren, wenn Sie den Hostnamen ändern.  Es empfiehlt sich jedoch, das Zertifikat zu aktualisieren, sodass der Hostname im Zertifikat mit dem tatsächlichen Hostnamen übereinstimmt.

Wenn Sie den Hostnamen in Unified Manager ändern, müssen Sie den Hostnamen in OnCommand Workflow Automation (WFA) manuell aktualisieren.  Der Hostname wird in WFA nicht automatisch aktualisiert.

Das neue Zertifikat wird erst wirksam, wenn die virtuelle Unified Manager-Maschine neu gestartet wird.

.Schritte
. xref:task_generate_an_https_security_certificate_ocf.adoc[Generieren Sie ein HTTPS-Sicherheitszertifikat]
+
Wenn Sie den neuen Hostnamen für den Zugriff auf die Unified Manager-Web-Benutzeroberfläche verwenden möchten, müssen Sie das HTTPS-Zertifikat neu generieren, um es mit dem neuen Hostnamen zu verknüpfen.

. xref:task_restart_unified_manager_virtual_machine.adoc[Starten Sie die virtuelle Unified Manager-Maschine neu]
+
Nachdem Sie das HTTPS-Zertifikat neu generiert haben, müssen Sie die virtuelle Unified Manager-Maschine neu starten.


