---
permalink: config/task_test_configuration_of_authentication_servers_um_6_0.html 
sidebar: sidebar 
keywords: test, configuration, authentication servers 
summary: Sie können die Konfiguration Ihrer Authentifizierungsserver validieren, um sicherzustellen, dass der Verwaltungsserver mit ihnen kommunizieren kann.  Sie können die Konfiguration validieren, indem Sie auf Ihren Authentifizierungsservern nach einem Remotebenutzer oder einer Remotegruppe suchen und diese mithilfe der konfigurierten Einstellungen authentifizieren. 
---
= Testen Sie die Konfiguration der Authentifizierungsserver
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Konfiguration Ihrer Authentifizierungsserver validieren, um sicherzustellen, dass der Verwaltungsserver mit ihnen kommunizieren kann.  Sie können die Konfiguration validieren, indem Sie auf Ihren Authentifizierungsservern nach einem Remotebenutzer oder einer Remotegruppe suchen und diese mithilfe der konfigurierten Einstellungen authentifizieren.

.Bevor Sie beginnen
* Sie müssen die Remote-Authentifizierung aktiviert und Ihren Authentifizierungsdienst konfiguriert haben, damit der Unified Manager-Server den Remote-Benutzer oder die Remote-Gruppe authentifizieren kann.
* Sie müssen Ihre Authentifizierungsserver hinzugefügt haben, damit der Verwaltungsserver von diesen Servern aus nach dem Remotebenutzer oder der Remotegruppe suchen und sie authentifizieren kann.
* Sie müssen über die Rolle „Anwendungsadministrator“ verfügen.


Wenn der Authentifizierungsdienst auf Active Directory eingestellt ist und Sie die Authentifizierung von Remotebenutzern validieren, die zur primären Gruppe des Authentifizierungsservers gehören, werden in den Authentifizierungsergebnissen keine Informationen zur primären Gruppe angezeigt.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *Remote-Authentifizierung*.
. Klicken Sie auf *Authentifizierung testen*.
. Geben Sie im Dialogfeld „Testbenutzer“ den Benutzernamen und das Kennwort des Remotebenutzers oder den Benutzernamen der Remotegruppe an und klicken Sie dann auf *Test*.
+
Wenn Sie eine Remote-Gruppe authentifizieren, dürfen Sie das Kennwort nicht eingeben.


