---
permalink: config/task_change_um_host_name_on_rhel.html 
sidebar: sidebar 
keywords: change, unified manager, host name, linux systems 
summary: Irgendwann möchten Sie möglicherweise den Hostnamen der Red Hat Enterprise Linux-Maschine ändern, auf der Sie Unified Manager installiert haben.  Beispielsweise möchten Sie möglicherweise den Host umbenennen, um Ihre Unified Manager-Server beim Auflisten Ihrer Linux-Computer einfacher nach Typ, Arbeitsgruppe oder überwachter Clustergruppe zu identifizieren. 
---
= Ändern des Unified Manager-Hostnamens auf Linux-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Irgendwann möchten Sie möglicherweise den Hostnamen der Red Hat Enterprise Linux-Maschine ändern, auf der Sie Unified Manager installiert haben.  Beispielsweise möchten Sie möglicherweise den Host umbenennen, um Ihre Unified Manager-Server beim Auflisten Ihrer Linux-Computer einfacher nach Typ, Arbeitsgruppe oder überwachter Clustergruppe zu identifizieren.

.Bevor Sie beginnen
Sie müssen über Root-Benutzerzugriff auf das Linux-System verfügen, auf dem Unified Manager installiert ist.

Sie können den Hostnamen (oder die Host-IP-Adresse) verwenden, um auf die Unified Manager-Web-Benutzeroberfläche zuzugreifen.  Wenn Sie während der Bereitstellung eine statische IP-Adresse für Ihr Netzwerk konfiguriert haben, haben Sie einen Namen für den Netzwerkhost festgelegt.  Wenn Sie das Netzwerk mit DHCP konfiguriert haben, sollte der Hostname vom DNS-Server übernommen werden.

Unabhängig davon, wie der Hostname zugewiesen wurde, müssen Sie ein neues Sicherheitszertifikat generieren, wenn Sie den Hostnamen ändern und den neuen Hostnamen für den Zugriff auf die Unified Manager-Web-Benutzeroberfläche verwenden möchten.

Wenn Sie auf die Web-Benutzeroberfläche zugreifen, indem Sie die IP-Adresse des Servers anstelle des Hostnamens verwenden, müssen Sie kein neues Zertifikat generieren, wenn Sie den Hostnamen ändern.  Es empfiehlt sich jedoch, das Zertifikat zu aktualisieren, sodass der Hostname im Zertifikat mit dem tatsächlichen Hostnamen übereinstimmt.  Das neue Zertifikat wird erst nach einem Neustart der Linux-Maschine wirksam.

Wenn Sie den Hostnamen in Unified Manager ändern, müssen Sie den Hostnamen in OnCommand Workflow Automation (WFA) manuell aktualisieren.  Der Hostname wird in WFA nicht automatisch aktualisiert.

.Schritte
. Melden Sie sich als Root-Benutzer beim Unified Manager-System an, das Sie ändern möchten.
. Stoppen Sie die Unified Manager-Software und die zugehörige MySQL-Software, indem Sie den folgenden Befehl eingeben:
+
`systemctl stop ocieau ocie mysqld`

. Ändern Sie den Hostnamen mit dem Linux `hostnamectl` Befehl:
+
`hostnamectl set-hostname new_FQDN`

+
`hostnamectl set-hostname nuhost.corp.widget.com`

. Generieren Sie das HTTPS-Zertifikat für den Server neu:
+
`/opt/netapp/essentials/bin/cert.sh create`

. Starten Sie den Netzwerkdienst neu:
+
`systemctl restart NetworkManager.service`

. Überprüfen Sie nach dem Neustart des Dienstes, ob der neue Hostname in der Lage ist, sich selbst anzupingen:
+
`ping new_hostname`

+
`ping nuhost`

+
Dieser Befehl sollte dieselbe IP-Adresse zurückgeben, die zuvor für den ursprünglichen Hostnamen festgelegt wurde.

. Nachdem Sie die Änderung Ihres Hostnamens abgeschlossen und überprüft haben, starten Sie Unified Manager neu, indem Sie den folgenden Befehl eingeben:
+
`systemctl start mysqld ocie ocieau`


