---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: Sie können Ihr lokales Benutzeranmeldekennwort ändern, um potenziellen Sicherheitsrisiken vorzubeugen. 
---
= Ändern des lokalen Benutzerkennworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihr lokales Benutzeranmeldekennwort ändern, um potenziellen Sicherheitsrisiken vorzubeugen.

.Bevor Sie beginnen
Sie müssen als lokaler Benutzer angemeldet sein.

Die Passwörter für den Wartungsbenutzer und für Remote-Benutzer können mit diesen Schritten nicht geändert werden.  Um das Kennwort eines Remote-Benutzers zu ändern, wenden Sie sich an Ihren Kennwortadministrator.  Informationen zum Ändern des Wartungsbenutzerkennworts finden Sie unterlink:task_use_maintenance_console.html["Verwenden der Wartungskonsole"] .

.Schritte
. Melden Sie sich bei Unified Manager an.
. Klicken Sie in der oberen Menüleiste auf das Benutzersymbol und dann auf *Passwort ändern*.
+
Die Option *Passwort ändern* wird nicht angezeigt, wenn Sie ein Remote-Benutzer sind.

. Geben Sie im Dialogfeld „Passwort ändern“ das aktuelle und das neue Passwort ein.
. Klicken Sie auf *Speichern*.


Wenn Unified Manager in einer Hochverfügbarkeitskonfiguration konfiguriert ist, müssen Sie das Kennwort auf dem zweiten Knoten des Setups ändern.  Beide Instanzen müssen dasselbe Passwort haben.
