---
permalink: install-linux/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, host, connectivity 
summary: Die Installation von Unified Manager auf einer virtuellen Infrastruktur oder einem physischen System sollte die Mindestanforderungen an Arbeitsspeicher, CPU und Festplattenspeicher erfüllen. 
---
= Anforderungen an die virtuelle Infrastruktur und das Hardwaresystem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation von Unified Manager auf einer virtuellen Infrastruktur oder einem physischen System sollte die Mindestanforderungen an Arbeitsspeicher, CPU und Festplattenspeicher erfüllen.

In der folgenden Tabelle sind die empfohlenen Werte für Arbeitsspeicher-, CPU- und Festplattenspeicherressourcen aufgeführt.  Diese Werte wurden qualifiziert, sodass Unified Manager akzeptable Leistungsniveaus erreicht.

[cols="2*"]
|===
| Hardwarekonfiguration | Empfohlene Einstellungen 


 a| 
RAM
 a| 
12 GB (Mindestanforderung 8 GB)



 a| 
Prozessoren
 a| 
4 CPUs



 a| 
CPU-Zykluskapazität
 a| 
9572 MHz gesamt (Mindestanforderung 9572 MHz)



 a| 
Freier Speicherplatz
 a| 
150 GB, wobei die Kapazität wie folgt aufgeteilt ist:

* 50 GB für die Root-Partition
* 100 GB freier Speicherplatz für die `/opt/netapp/data` Verzeichnis, das auf einem LVM-Laufwerk oder einer separaten lokalen Festplatte gemountet ist, die an das Zielsystem angeschlossen ist


[NOTE]
====
Für separat montierte `/opt` Und `/var/log` Verzeichnisse, stellen Sie sicher, dass `/opt` verfügt über 15 GB und `/var/log` hat 16 GB freien Speicherplatz.  Der `/tmp` Das Verzeichnis sollte mindestens 10 GB freien Speicherplatz haben.

====
|===
Unified Manager kann auf Systemen mit wenig Arbeitsspeicher installiert werden, die empfohlenen 12 GB RAM stellen jedoch sicher, dass genügend Arbeitsspeicher für eine optimale Leistung zur Verfügung steht und dass das System bei wachsender Konfiguration zusätzliche Cluster und Speicherobjekte aufnehmen kann.  Sie sollten auf der VM, auf der Unified Manager bereitgestellt wird, keine Speicherbeschränkungen festlegen und keine Funktionen (z. B. Ballooning) aktivieren, die die Software daran hindern, den zugewiesenen Speicher auf dem System zu nutzen.

Darüber hinaus gibt es eine Begrenzung für die Anzahl der Knoten, die eine einzelne Instanz von Unified Manager überwachen kann, bevor Sie eine zweite Instanz von Unified Manager installieren.  Weitere Informationen finden Sie im _Best Practices Guide_.

https://www.netapp.com/pdf.html?item=/media/13504-tr4621.pdf["Technischer Bericht 4621: Leitfaden zu Best Practices für Unified Manager"^]

Das Auslagern von Speicherseiten wirkt sich negativ auf die Leistung des Systems und der Verwaltungsanwendung aus.  Der Wettbewerb um CPU-Ressourcen, die aufgrund der Gesamtauslastung des Hosts nicht verfügbar sind, kann die Leistung beeinträchtigen.



[[requirement-for-dedicated-use]]
== Voraussetzung für die dedizierte Nutzung

Das physische oder virtuelle System, auf dem Sie Unified Manager installieren, sollte ausschließlich für Unified Manager verwendet und nicht mit anderen Anwendungen geteilt werden.  Andere Anwendungen verbrauchen möglicherweise Systemressourcen und können die Leistung von Unified Manager drastisch reduzieren.



[[space-requirements-for-backups]]
== Speicherplatzbedarf für Backups

Wenn Sie die Sicherungs- und Wiederherstellungsfunktion von Unified Manager verwenden möchten, weisen Sie zusätzliche Kapazität zu, sodass das Verzeichnis oder die Festplatte „`data`“ über 150 GB Speicherplatz verfügt.  Eine Sicherung kann an ein lokales oder ein Remote-Ziel geschrieben werden.  Die beste Vorgehensweise besteht darin, einen Remote-Standort außerhalb des Unified Manager-Hostsystems zu identifizieren, der über mindestens 150 GB Speicherplatz verfügt.



[[requirements-for-host-connectivity]]
== Anforderungen für die Hostkonnektivität

Das physische oder virtuelle System, auf dem Sie Unified Manager installieren, sollte so konfiguriert sein, dass Sie erfolgreich `ping` der Hostname vom Host selbst.  Bei einer IPv6-Konfiguration sollten Sie überprüfen, ob `ping6` zum Hostnamen erfolgreich ist, um sicherzustellen, dass die Installation von Unified Manager erfolgreich ist.

Sie können den Hostnamen (oder die Host-IP-Adresse) verwenden, um auf die Web-Benutzeroberfläche des Produkts zuzugreifen.  Wenn Sie während der Bereitstellung eine statische IP-Adresse für Ihr Netzwerk konfiguriert haben, haben Sie einen Namen für den Netzwerkhost festgelegt.  Wenn Sie das Netzwerk mit DHCP konfiguriert haben, sollten Sie den Hostnamen vom DNS beziehen.

Wenn Sie Benutzern den Zugriff auf Unified Manager über den Kurznamen statt über den vollqualifizierten Domänennamen (FQDN) oder die IP-Adresse ermöglichen möchten, muss Ihre Netzwerkkonfiguration diesen Kurznamen in einen gültigen FQDN auflösen.
