---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: Sie können das instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde.  Sie können das Kennwort optional zurücksetzen, falls Ihre Site diese Sicherheitsfunktion benötigt, um die Installationseinstellung des Unified Managers zu überschreiben.  Dieser Vorgang ändert auch das Kennwort, das JBoss für den Zugriff auf MySQL verwendet. 
---
= Ändern des JBoss-Passworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde.  Sie können das Kennwort optional zurücksetzen, falls Ihre Site diese Sicherheitsfunktion benötigt, um die Installationseinstellung des Unified Managers zu überschreiben.  Dieser Vorgang ändert auch das Kennwort, das JBoss für den Zugriff auf MySQL verwendet.

* Sie müssen über Root-Benutzerzugriff auf das Red Hat Enterprise Linux-System verfügen, auf dem Unified Manager installiert ist.
* Sie müssen auf die von NetApp bereitgestellte `password.sh` Skript im Verzeichnis `/opt/netapp/essentials/bin` .


.Schritte
. Melden Sie sich als Root-Benutzer am System an.
. Stoppen Sie die Unified Manager-Dienste, indem Sie die folgenden Befehle in der angezeigten Reihenfolge eingeben:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
Beenden Sie die zugehörige MySQL-Software nicht.

. Geben Sie den folgenden Befehl ein, um den Vorgang zur Kennwortänderung zu starten:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Geben Sie bei entsprechender Aufforderung das neue JBoss-Passwort ein und geben Sie es zur Bestätigung ein zweites Mal ein.
+
Beachten Sie, dass das Passwort zwischen 8 und 16 Zeichen lang sein sollte und mindestens eine Ziffer, einen Großbuchstaben, einen Kleinbuchstaben und mindestens eines dieser Sonderzeichen enthalten muss:

+
`+!@%^*-_+=[]:<>.?/~+`

. Wenn das Skript abgeschlossen ist, starten Sie die Unified Manager-Dienste, indem Sie die folgenden Befehle in der angezeigten Reihenfolge eingeben:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Nachdem alle Dienste gestartet wurden, können Sie sich bei der Unified Manager-Benutzeroberfläche anmelden.

