---
permalink: install-linux/task_create_custom_user_home_directory_and_umadmin.html 
sidebar: sidebar 
keywords: create, custom, user, home, directory, umadmin, password, prior, installation 
summary: Sie können vor der Installation von Unified Manager ein benutzerdefiniertes Home-Verzeichnis erstellen und Ihr eigenes Umadmin-Benutzerkennwort festlegen.  Diese Aufgabe ist optional, einige Sites benötigen jedoch möglicherweise die Flexibilität, die Standardeinstellungen der Unified Manager-Installation zu überschreiben. 
---
= Erstellen Sie vor der Installation ein benutzerdefiniertes Benutzer-Home-Verzeichnis und ein Umadmin-Passwort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können vor der Installation von Unified Manager ein benutzerdefiniertes Home-Verzeichnis erstellen und Ihr eigenes Umadmin-Benutzerkennwort festlegen.  Diese Aufgabe ist optional, einige Sites benötigen jedoch möglicherweise die Flexibilität, die Standardeinstellungen der Unified Manager-Installation zu überschreiben.

.Bevor Sie beginnen
* Das System muss die inlink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Hardware-Systemanforderungen"] .
* Sie müssen sich als Root-Benutzer beim Red Hat Enterprise Linux-System anmelden können.


Die Standardinstallation von Unified Manager führt die folgenden Aufgaben aus:

* Erstellt den Benutzer umadmin mit `/home/umadmin` als Home-Verzeichnis.
* Weist dem umadmin-Benutzer das Standardkennwort „`admin`“ zu.


Da einige Installationsumgebungen den Zugriff auf `/home` , schlägt die Installation fehl.  Sie müssen das Home-Verzeichnis an einem anderen Ort erstellen.  Darüber hinaus können auf manchen Websites Regeln zur Kennwortkomplexität gelten oder es kann erforderlich sein, dass Kennwörter von lokalen Administratoren und nicht vom Installationsprogramm festgelegt werden.

Wenn Ihre Installationsumgebung erfordert, dass Sie diese Standardinstallationseinstellungen überschreiben, führen Sie diese Schritte aus, um ein benutzerdefiniertes Home-Verzeichnis zu erstellen und das Kennwort des Umadmin-Benutzers festzulegen.

Wenn diese Informationen vor der Installation definiert werden, erkennt das Installationsskript diese Einstellungen und verwendet die definierten Werte anstelle der Standardeinstellungen der Installation.

Darüber hinaus enthält die Standardinstallation von Unified Manager den Benutzer umadmin in den sudoers-Dateien(`ocum_sudoers` Und `ocie_sudoers` ) im `/etc/sudoers.d/` Verzeichnis.  Wenn Sie diesen Inhalt aufgrund von Sicherheitsrichtlinien oder aufgrund eines Sicherheitsüberwachungstools aus Ihrer Umgebung entfernen, müssen Sie ihn wieder hinzufügen.  Sie müssen die Sudoers-Konfiguration beibehalten, da einige Unified Manager-Vorgänge diese Sudo-Berechtigungen erfordern.

Die Sicherheitsrichtlinien in Ihrer Umgebung dürfen die Sudo-Berechtigungen für den Unified Manager-Wartungsbenutzer nicht einschränken.  Einige Unified Manager-Vorgänge können fehlschlagen, wenn die Berechtigungen eingeschränkt sind.  Überprüfen Sie, ob Sie nach erfolgreicher Installation den folgenden Sudo-Befehl ausführen können, wenn Sie als Umadmin-Benutzer angemeldet sind.

`sudo systemctl  status ocie`

Dieser Befehl sollte den entsprechenden Status des Ocie-Dienstes ohne Fehler zurückgeben.

.Schritte
. Melden Sie sich als Root-Benutzer beim Server an.
. Erstellen Sie das umadmin-Gruppenkonto mit dem Namen „maintenance“:
+
`groupadd maintenance`

. Erstellen Sie das Benutzerkonto „`umadmin`“ in der Wartungsgruppe unter einem Home-Verzeichnis Ihrer Wahl:
+
`adduser --home <home_directory\> -g maintenance umadmin`

. Definieren Sie das Umadmin-Passwort:
+
`passwd umadmin`

+
Das System fordert Sie auf, eine neue Kennwortzeichenfolge für den Benutzer „umadmin“ einzugeben.



Nachdem Sie Unified Manager installiert haben, müssen Sie die Benutzeranmeldeshell umadmin angeben.
