---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: Wenn Sie planen, /opt/netapp oder /opt/netapp/data auf einem NAS- oder SAN-Gerät zu mounten und SELinux aktiviert haben, müssen Sie die folgenden Überlegungen beachten. 
---
= SELinux-Anforderungen an NFS- und CIFS-Freigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie planen, `/opt/netapp` oder `/opt/netapp/data` auf einem NAS- oder SAN-Gerät und wenn Sie SELinux aktiviert haben, müssen Sie einige Überlegungen beachten.

Wenn Sie planen, `/opt/netapp` oder `/opt/netapp/data` von einem anderen Ort als dem Root-Dateisystem aus und wenn Sie SELinux in Ihrer Umgebung aktiviert haben, sollten Sie den richtigen Kontext für die gemounteten Verzeichnisse festlegen.  Befolgen Sie für das entsprechende Szenario in Ihrer Umgebung diese Schritte zum Einrichten und Bestätigen des richtigen SELinux-Kontexts.



[[configure-the-selinux-context-when-optnetappdata-is-mounted]]
== Konfigurieren Sie den SELinux-Kontext, wenn `/opt/netapp/data` ist montiert

Wenn Sie montiert haben `/opt/netapp/data` in Ihrem System und SELinux ist eingestellt auf `Enforcing` , stellen Sie sicher, dass der SELinux-Kontexttyp für `/opt/netapp/data` ist eingestellt auf `mysqld_db_t` , das Standardkontextelement für den Speicherort der Datenbankdateien.

. Führen Sie diesen Befehl aus, um den Kontext zu überprüfen:
+
`ls -dZ /opt/netapp/data`

+
Eine Beispielausgabe:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: In dieser Ausgabe ist der Kontext `default_t` .  Sie sollten diesen Kontext ändern in `mysqld_db_t` .

. Führen Sie diese Schritte aus, um den Kontext basierend auf der Art und Weise festzulegen, wie Sie `/opt/netapp/data` .
+
.. Führen Sie die folgenden Befehle aus, um den Kontext auf `mysqld_db_t` :
`semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
`restorecon -R -v /opt/netapp/data`
.. Wenn Sie konfiguriert haben `/opt/netapp/data` In `/etc/fstab` , sollten Sie die `/etc/fstab` Datei.  Für die `/opt/netapp/data/` Fügen Sie bei der Mount-Option das MySQL-Label wie folgt hinzu:
+
`context=system_u:object_r:mysqld_db_t:s0`

.. Aushängen und erneutes Einhängen `/opt/netapp/data/` zum Aktivieren des Kontexts.
.. Wenn Sie über eine direkte NFS-Einbindung verfügen, führen Sie den folgenden Befehl aus, um den Kontext auf `mysqld_db_t` :
+
`mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysqld_db_t:s0`



. Überprüfen Sie, ob der Kontext richtig eingestellt ist:


`ls -dZ /opt/netapp/data/`

Eine Beispielausgabe:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


[[configure-the-selinux-context-when-optnetapp-is-mounted-and-optnetappdata-is-also-mounted-separately]]
== Konfigurieren Sie den SELinux-Kontext, wenn `/opt/netapp` montiert ist und `/opt/netapp/data/` wird auch separat montiert

In diesem Szenario sollten Sie zunächst den Kontext für `/opt/netapp/data/` wie im vorherigen Abschnitt beschrieben.  Nachdem Sie den richtigen Kontext für `/opt/netapp/data/` , stellen Sie sicher, dass das übergeordnete Verzeichnis `/opt/netapp` hat den SELinux-Kontext nicht auf `file_t` .

.Schritte
. Führen Sie diesen Befehl aus, um den Kontext zu überprüfen:
+
`ls -dZ /opt/netapp`

+
Eine Beispielausgabe:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
In dieser Ausgabe ist der Kontext `file_t` sollte geändert werden.  Die folgenden Befehle setzen den Kontext auf `usr_t` .  Sie können den Kontext auf einen beliebigen Wert außer `file_t` basierend auf Ihren Sicherheitsanforderungen.

. Führen Sie diese Schritte aus, um den Kontext basierend auf der Art und Weise festzulegen, wie Sie `/opt/netapp` .
+
.. Führen Sie die folgenden Befehle aus, um den Kontext festzulegen:




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. Wenn Sie konfiguriert haben `/opt/netapp` In `/etc/fstab` , sollten Sie die `/etc/fstab` Datei.  Für die `/opt/netapp` Fügen Sie bei der Mount-Option das MySQL-Label wie folgt hinzu:
+
`context=system_u:object_r:usr_t:s0`

. Aushängen und dann wieder einhängen `/opt/netapp` zum Aktivieren des Kontexts.
. Wenn Sie über eine direkte NFS-Einbindung verfügen, führen Sie den folgenden Befehl aus, um den Kontext festzulegen:
+
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`

+
.. Überprüfen Sie, ob der Kontext richtig eingestellt ist:
+
`ls -dZ /opt/netapp`

+
Eine Beispielausgabe





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


[[configure-the-selinux-context-when-optnetapp-is-mounted-and-optnetappdata-is-not-mounted-separately]]
== Konfigurieren Sie den SELinux-Kontext, wenn `/opt/netapp` montiert ist und `/opt/netapp/data/` wird nicht separat montiert

Wenn Sie montiert haben `/opt/netapp` in Ihrem System und SELinux ist eingestellt auf `Enforcing` , stellen Sie sicher, dass der SELinux-Kontexttyp für `/opt/netapp` ist eingestellt auf `mysqld_db_t` , das Standardkontextelement für den Speicherort der Datenbankdateien.

.Schritte
. Führen Sie diesen Befehl aus, um den Kontext zu überprüfen:
+
`ls -dZ /opt/netapp`

+
Eine Beispielausgabe:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----
+

NOTE: In dieser Ausgabe ist der Kontext `default_t` .  Sie sollten diesen Kontext ändern in `mysqld_db_t` .

. Führen Sie die folgenden Schritte aus, um den Kontext basierend auf der Art und Weise festzulegen, wie Sie ihn gemountet haben `/opt/netapp` .
+
.. Führen Sie die folgenden Befehle aus, um den Kontext auf `mysqld_db_t` :
`semanage fcontext -a -t mysqld_db_t "/opt/netapp"
`restorecon -R -v /opt/netapp`
.. Wenn Sie konfiguriert haben `/opt/netapp` In `/etc/fstab` , bearbeiten Sie die `/etc/fstab` Datei.  Für die `/opt/netapp/` Fügen Sie bei der Mount-Option das MySQL-Label wie folgt hinzu:
`context=system_u:object_r:mysqld_db_t:s0`
.. Aushängen und dann wieder einhängen `/opt/netapp/` zum Aktivieren des Kontexts.
.. Wenn Sie über eine direkte NFS-Einbindung verfügen, führen Sie den folgenden Befehl aus, um den Kontext auf `mysqld_db_t` :
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0`


. Überprüfen Sie, ob der Kontext richtig eingestellt ist:


`ls -dZ /opt/netapp/`

Eine Beispielausgabe:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''