---
permalink: events/reference_logical_interface_events.html 
sidebar: sidebar 
keywords: 'network, interface, (lif) events, impact area, availability, configuration, performance' 
summary: 'Netzwerkschnittstellenereignisse liefern Informationen zum Status Ihrer Netzwerkschnittstelle (LIFs), sodass Sie diese auf potenzielle Probleme überwachen können.  Ereignisse werden nach Auswirkungsbereich gruppiert und enthalten den Ereignis- und Trap-Namen, die Auswirkungsstufe, den Quellentyp und den Schweregrad.' 
---
= Netzwerkschnittstellenereignisse (LIF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Netzwerkschnittstellenereignisse liefern Informationen zum Status Ihrer Netzwerkschnittstelle (LIFs), sodass Sie diese auf potenzielle Probleme überwachen können.  Ereignisse werden nach Auswirkungsbereich gruppiert und enthalten den Ereignis- und Trap-Namen, die Auswirkungsstufe, den Quellentyp und den Schweregrad.



[[impact-area-availability]]
== Wirkungsbereich: Verfügbarkeit

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
Netzwerkschnittstellenstatus „Down“ (ocumEvtLifStatusDown)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Fehler



 a| 
FC/FCoE-Netzwerkschnittstellenstatus „Down“ (ocumEvtFCLifStatusDown)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Fehler



 a| 
Failover der Netzwerkschnittstelle nicht möglich (ocumEvtLifFailoverNotPossible)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Warnung



 a| 
Netzwerkschnittstelle nicht am Home-Port (ocumEvtLifNotAtHomePort)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Warnung

|===


[[impact-area-configuration]]
== Wirkungsbereich: Konfiguration

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
Netzwerkschnittstellenroute nicht konfiguriert (Nicht zutreffend)
 a| 
Ereignis
 a| 
Schnittstelle
 a| 
Information

|===


[[impact-area-performance]]
== Wirkungsbereich: Leistung

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
Kritischer Schwellenwert für Netzwerkschnittstelle MB/s überschritten (ocumNetworkLifMbpsIncident)
 a| 
Vorfall
 a| 
Schnittstelle
 a| 
Kritisch



 a| 
Warnschwelle für Netzwerkschnittstelle in MB/s überschritten (ocumNetworkLifMbpsWarning)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Warnung



 a| 
Kritischer Schwellenwert für FC-Netzwerkschnittstelle MB/s überschritten (ocumFcpLifMbpsIncident)
 a| 
Vorfall
 a| 
Schnittstelle
 a| 
Kritisch



 a| 
Warnschwelle für FC-Netzwerkschnittstelle (MB/s) überschritten (ocumFcpLifMbpsWarning)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Warnung



 a| 
NVMf FC-Netzwerkschnittstelle MB/s kritischer Schwellenwert überschritten (ocumNvmfFcLifMbpsIncident)
 a| 
Vorfall
 a| 
Schnittstelle
 a| 
Kritisch



 a| 
NVMf FC-Netzwerkschnittstelle MB/s-Warnschwelle überschritten (ocumNvmfFcLifMbpsWarning)
 a| 
Risiko
 a| 
Schnittstelle
 a| 
Warnung

|===