---
permalink: events/reference_disk_events.html 
sidebar: sidebar 
keywords: disks, events, impact area, availability 
summary: Datenträgerereignisse liefern Ihnen Informationen zum Status von Datenträgern, sodass Sie diese auf potenzielle Probleme überwachen können.  Ereignisse werden nach Auswirkungsbereich gruppiert und enthalten den Ereignis- und Trap-Namen, die Auswirkungsstufe, den Quellentyp und den Schweregrad. 
---
= Datenträgerereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Datenträgerereignisse liefern Ihnen Informationen zum Status von Datenträgern, sodass Sie diese auf potenzielle Probleme überwachen können.  Ereignisse werden nach Auswirkungsbereich gruppiert und enthalten den Ereignis- und Trap-Namen, die Auswirkungsstufe, den Quellentyp und den Schweregrad.



== Wirkungsbereich: Verfügbarkeit

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
Flash-Festplatten – Ersatzblöcke fast aufgebraucht (ocumEvtClusterFlashDiskFewerSpareBlockError)
 a| 
Risiko
 a| 
Cluster
 a| 
Fehler



 a| 
Flash-Disks – Keine Ersatzblöcke (ocumEvtClusterFlashDiskNoSpareBlockCritical)
 a| 
Vorfall
 a| 
Cluster
 a| 
Kritisch



 a| 
Einige nicht zugewiesene Datenträger (ocumEvtClusterUnassignedDisksSome)
 a| 
Risiko
 a| 
Cluster
 a| 
Warnung



 a| 
Einige ausgefallene Datenträger (ocumEvtDisksSomeFailed)
 a| 
Vorfall
 a| 
Cluster
 a| 
Kritisch

|===