---
permalink: events/reference_storage_vm_events.html 
sidebar: sidebar 
keywords: storage, vm events, impact area, availability, configuration, performance, security 
summary: 'Storage-VM-Ereignisse liefern Ihnen Informationen zum Status Ihrer Storage-VMs (SVMs), sodass Sie diese auf potenzielle Probleme überwachen können.  Ereignisse werden nach Auswirkungsbereich gruppiert und enthalten den Ereignis- und Trap-Namen, die Auswirkungsstufe, den Quellentyp und den Schweregrad.' 
---
= Speicher-VM-Ereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-VM-Ereignisse (Storage Virtual Machine, auch als SVM bezeichnet) liefern Ihnen Informationen zum Status Ihrer Storage-VMs (SVMs), sodass Sie diese auf potenzielle Probleme überwachen können.  Ereignisse werden nach Auswirkungsbereich gruppiert und enthalten den Ereignis- und Trap-Namen, die Auswirkungsstufe, den Quellentyp und den Schweregrad.

Ein Sternchen (*) kennzeichnet EMS-Ereignisse, die in Unified Manager-Ereignisse konvertiert wurden.



[[impact-area-availability]]
== Wirkungsbereich: Verfügbarkeit

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
CIFS-Dienst der Speicher-VM ausgefallen (ocumEvtVserverCifsServiceStatusDown)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
SVM CIFS-Dienst nicht konfiguriert (Nicht zutreffend)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
Versuche, eine Verbindung zu einer nicht vorhandenen CIFS-Freigabe herzustellen *(nbladeCifsNoPrivShare)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
CIFS-NetBIOS-Namenskonflikt *(nbladeCifsNbNameConflict)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
CIFS-Schattenkopie-Vorgang fehlgeschlagen *(cifsShadowCopyFailure)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
Viele CIFS-Verbindungen *(nbladeCifsManyAuths)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
Maximale CIFS-Verbindung überschritten *(nbladeCifsMaxOpenSameFile)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
Maximale Anzahl von CIFS-Verbindungen pro Benutzer überschritten *(nbladeCifsMaxSessPerUsrConn)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
SVM FC/FCoE-Dienst ausgefallen (ocumEvtVserverFcServiceStatusDown)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
SVM-iSCSI-Dienst ausgefallen (ocumEvtVserverIscsiServiceStatusDown)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
NFS-Dienst der Speicher-VM ausgefallen (ocumEvtVserverNfsServiceStatusDown)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
SVM FC/FCoE-Dienst nicht konfiguriert (Nicht zutreffend)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
SVM-iSCSI-Dienst nicht konfiguriert (Nicht zutreffend)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
SVM NFS-Dienst nicht konfiguriert (Nicht zutreffend)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
Speicher-VM gestoppt (ocumEvtVserverDown)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
AV-Server zu beschäftigt, um neue Scan-Anforderung anzunehmen *(nbladeVscanConnBackPressure)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
Keine AV-Serververbindung für Virenscan *(nbladeVscanNoScannerConn)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
Kein AV-Server registriert *(nbladeVscanNoRegdScanner)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
Keine reagierende AV-Serververbindung *(nbladeVscanConnInactive)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
Versuch eines nicht autorisierten Benutzers, den AV-Server zu beschädigen *(nbladeVscanBadUserPrivAccess)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler



 a| 
Virus vom AV-Server gefunden *(nbladeVscanVirusDetected)
 a| 
Risiko
 a| 
SVM
 a| 
Fehler

|===


[[impact-area-configuration]]
== Wirkungsbereich: Konfiguration

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
SVM erkannt (Nicht zutreffend)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
SVM gelöscht (Nicht zutreffend)
 a| 
Ereignis
 a| 
Cluster
 a| 
Information



 a| 
SVM umbenannt (Nicht zutreffend)
 a| 
Ereignis
 a| 
SVM
 a| 
Information

|===


[[impact-area-performance]]
== Wirkungsbereich: Leistung

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
Kritischer SVM-IOPS-Schwellenwert überschritten (ocumSvmIopsIncident)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
SVM-IOPS-Warnschwelle überschritten (ocumSvmIopsWarning)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
Kritischer Schwellenwert für SVM MB/s überschritten (ocumSvmMbpsIncident)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
SVM MB/s-Warnschwelle überschritten (ocumSvmMbpsWarning)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
Kritischer Schwellenwert für SVM-Latenz überschritten (ocumSvmLatencyIncident)
 a| 
Vorfall
 a| 
SVM
 a| 
Kritisch



 a| 
SVM-Latenzwarnschwelle überschritten (ocumSvmLatencyWarning)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung

|===


[[impact-area-security]]
== Wirkungsbereich: Sicherheit

|===
| Ereignisname (Trap-Name) | Auswirkungsstufe | Quellentyp | Schwere 


 a| 
Überwachungsprotokoll deaktiviert (ocumVserverAuditLogDisabled)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
Anmeldebanner deaktiviert (ocumVserverLoginBannerDisabled)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
SSH verwendet unsichere Chiffren (ocumVserverSSHInsecure)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
Anmeldebanner geändert (ocumVserverLoginBannerChanged)
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
Die Anti-Ransomware-Überwachung der Storage-VM ist deaktiviert (antiRansomwareSvmStateDisabled).
 a| 
Risiko
 a| 
SVM
 a| 
Warnung



 a| 
Die Anti-Ransomware-Überwachung der Storage-VM ist aktiviert (Lernmodus) (antiRansomwareSvmStateDryrun)
 a| 
Ereignis
 a| 
SVM
 a| 
Information



 a| 
Für die Anti-Ransomware-Überwachung geeignete Speicher-VM (Lernmodus) (ocumEvtSvmArwCandidate)
 a| 
Ereignis
 a| 
SVM
 a| 
Information

|===