---
permalink: events/reference_what_suggested_actions_section_displays.html 
sidebar: sidebar 
keywords: suggest, actions, section, displays 
summary: Der Abschnitt „Vorgeschlagene Maßnahmen“ auf der Seite mit den Ereignisdetails enthält mögliche Gründe für das Ereignis und schlägt einige Maßnahmen vor, damit Sie versuchen können, das Ereignis selbst zu beheben.  Die vorgeschlagenen Maßnahmen werden je nach Art des Ereignisses oder der Art des überschrittenen Schwellenwerts individuell angepasst. 
---
= Was im Abschnitt „Vorgeschlagene Aktionen“ angezeigt wird
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Abschnitt „Vorgeschlagene Maßnahmen“ auf der Seite mit den Ereignisdetails enthält mögliche Gründe für das Ereignis und schlägt einige Maßnahmen vor, damit Sie versuchen können, das Ereignis selbst zu beheben.  Die vorgeschlagenen Maßnahmen werden je nach Art des Ereignisses oder der Art des überschrittenen Schwellenwerts individuell angepasst.

Dieser Bereich wird nur für bestimmte Ereignistypen angezeigt.

In einigen Fällen werden auf der Seite *Hilfe*-Links bereitgestellt, die auf zusätzliche Informationen zu vielen vorgeschlagenen Aktionen verweisen, einschließlich Anweisungen zum Ausführen einer bestimmten Aktion.  Einige der Aktionen können die Verwendung von Unified Manager, ONTAP System Manager, OnCommand Workflow Automation, ONTAP CLI-Befehlen oder einer Kombination dieser Tools beinhalten.

Sie sollten die hier vorgeschlagenen Maßnahmen lediglich als Anleitung zur Lösung dieses Ereignisses betrachten.  Die Maßnahmen, die Sie zur Lösung dieses Ereignisses ergreifen, sollten auf dem Kontext Ihrer Umgebung basieren.

Wenn Sie das Objekt und das Ereignis detaillierter analysieren möchten, klicken Sie auf die Schaltfläche *Arbeitslast analysieren*, um die Seite „Arbeitslastanalyse“ anzuzeigen.

Es gibt bestimmte Ereignisse, die Unified Manager gründlich diagnostizieren und eine einzige Lösung bereitstellen kann.  Sofern verfügbar, werden diese Lösungen mit der Schaltfläche *Fix It* angezeigt.  Klicken Sie auf diese Schaltfläche, damit Unified Manager das Problem behebt, das das Ereignis verursacht.

Bei Active IQ -Plattformereignissen kann dieser Abschnitt einen Link zu einem NetApp Knowledgebase-Artikel enthalten, sofern verfügbar, der das Problem und mögliche Lösungen beschreibt.  An Standorten ohne externen Netzwerkzugriff wird lokal eine PDF-Datei des Knowledgebase-Artikels geöffnet. Die PDF-Datei ist Teil der Regeldatei, die Sie manuell auf die Unified Manager-Instanz herunterladen.
