---
permalink: events/task_change_or_cancel_scheduled_maintenance_window.html 
sidebar: sidebar 
keywords: change, cancel, scheduled, maintenance, window 
summary: Wenn Sie ein zukünftiges Wartungsfenster für Unified Manager konfiguriert haben, können Sie die Start- und Endzeiten ändern oder das Wartungsfenster abbrechen. 
---
= Ändern oder Abbrechen eines geplanten Wartungsfensters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein zukünftiges Wartungsfenster für Unified Manager konfiguriert haben, können Sie die Start- und Endzeiten ändern oder das Wartungsfenster abbrechen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Das Abbrechen eines aktuell laufenden Wartungsfensters ist nützlich, wenn Sie die Clusterwartung vor dem geplanten Ende des Wartungsfensters abgeschlossen haben und wieder Ereignisse und Warnungen vom Cluster empfangen möchten.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Cluster-Setup*.
. In der Spalte *Wartungsmodus* für den Cluster:
+
|===
| Wenn Sie wollen... | Führen Sie diesen Schritt aus... 


 a| 
Ändern des Zeitrahmens für ein geplantes Wartungsfenster
 a| 
.. Klicken Sie neben dem Schieberegler auf den Text „Geplant“.
.. Ändern Sie das Start- und/oder Enddatum und die Uhrzeit und klicken Sie auf *Übernehmen*.




 a| 
Verlängern Sie die Länge eines aktiven Wartungsfensters
 a| 
.. Klicken Sie neben dem Schieberegler auf den Text „Aktiv“.
.. Ändern Sie das Enddatum und die Endzeit und klicken Sie auf *Übernehmen*.




 a| 
Abbrechen eines geplanten Wartungsfensters
 a| 
Wählen Sie den Schieberegler aus und verschieben Sie ihn nach links.



 a| 
Abbrechen eines aktiven Wartungsfensters
 a| 
Wählen Sie den Schieberegler aus und verschieben Sie ihn nach links.

|===

