---
permalink: events/task_view_event_details.html 
sidebar: sidebar 
keywords: view, events, details 
summary: Sie können Details zu einem Ereignis anzeigen, das von Unified Manager ausgelöst wird, um Korrekturmaßnahmen zu ergreifen.  Wenn beispielsweise ein Integritätsereignis „Volume offline“ vorliegt, können Sie auf dieses Ereignis klicken, um die Details anzuzeigen und Korrekturmaßnahmen durchzuführen. 
---
= Anzeigen von Ereignissen und Ereignisdetails
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Details zu einem Ereignis anzeigen, das von Unified Manager ausgelöst wird, um Korrekturmaßnahmen zu ergreifen.  Wenn beispielsweise ein Integritätsereignis „Volume offline“ vorliegt, können Sie auf dieses Ereignis klicken, um die Details anzuzeigen und Korrekturmaßnahmen durchzuführen.

.Bevor Sie beginnen
Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Die Ereignisdetails umfassen Informationen wie die Quelle des Ereignisses, die Ursache des Ereignisses und alle Hinweise zum Ereignis.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Event Management*.
+
Standardmäßig werden in der Ansicht „Alle aktiven Ereignisse“ die neuen und bestätigten (aktiven) Ereignisse angezeigt, die in den letzten 7 Tagen generiert wurden und die Auswirkungsstufe „Vorfall“ oder „Risiko“ aufweisen.

. Wenn Sie eine bestimmte Kategorie von Ereignissen anzeigen möchten, beispielsweise Kapazitätsereignisse oder Leistungsereignisse, klicken Sie auf *Anzeigen* und wählen Sie aus dem Menü der Ereignistypen aus.
. Klicken Sie auf den Namen des Ereignisses, dessen Details Sie anzeigen möchten.
+
Die Ereignisdetails werden auf der Seite „Ereignisdetails“ angezeigt.


