---
permalink: events/task_assign_events_to_specific_users.html 
sidebar: sidebar 
keywords: assign, events, specific, users 
summary: Sie können nicht zugewiesene Ereignisse sich selbst oder anderen Benutzern, einschließlich Remotebenutzern, zuweisen.  Sie können zugewiesene Ereignisse bei Bedarf einem anderen Benutzer neu zuweisen.  Wenn beispielsweise bei einem Speicherobjekt häufig Probleme auftreten, können Sie die Ereignisse für diese Probleme dem Benutzer zuweisen, der dieses Objekt verwaltet. 
---
= Zuweisen von Ereignissen zu bestimmten Benutzern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können nicht zugewiesene Ereignisse sich selbst oder anderen Benutzern, einschließlich Remotebenutzern, zuweisen.  Sie können zugewiesene Ereignisse bei Bedarf einem anderen Benutzer neu zuweisen.  Wenn beispielsweise bei einem Speicherobjekt häufig Probleme auftreten, können Sie die Ereignisse für diese Probleme dem Benutzer zuweisen, der dieses Objekt verwaltet.

.Bevor Sie beginnen
* Der Name und die E-Mail-ID des Benutzers müssen korrekt konfiguriert sein.
* Sie müssen über die Rolle „Operator“, „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.


.Schritte
. Klicken Sie im linken Navigationsbereich auf *Event Management*.
. Wählen Sie auf der Inventarseite *Event Management* ein oder mehrere Events aus, die Sie zuweisen möchten.
. Weisen Sie das Ereignis zu, indem Sie eine der folgenden Optionen auswählen:
+
|===
| Wenn Sie das Ereignis zuweisen möchten an... | Dann tun Sie Folgendes ... 


 a| 
Selbst
 a| 
Klicken Sie auf *Zuweisen an* > *Mir*.



 a| 
Ein anderer Benutzer
 a| 
.. Klicken Sie auf *Zuweisen an* > *Anderer Benutzer*.
.. Geben Sie im Dialogfeld „Besitzer zuweisen“ den Benutzernamen ein oder wählen Sie einen Benutzer aus der Dropdownliste aus.
.. Klicken Sie auf *Zuweisen*.
+
Dem Benutzer wird eine E-Mail-Benachrichtigung gesendet.

+
[NOTE]
====
Wenn Sie keinen Benutzernamen eingeben oder keinen Benutzer aus der Dropdown-Liste auswählen und auf *Zuweisen* klicken, bleibt das Ereignis unzugeordnet.

====


|===

