---
permalink: data-protection/task_edit_protection_relationships_from_health_volume.html 
sidebar: sidebar 
keywords: edit, protection, relationships, volume, health details page 
summary: Sie können vorhandene Schutzbeziehungen bearbeiten, um die aktuelle maximale Übertragungsrate, Schutzrichtlinie oder den Schutzzeitplan zu ändern.  Sie können eine Beziehung bearbeiten, um die für Übertragungen verwendete Bandbreite zu verringern oder die Häufigkeit geplanter Übertragungen zu erhöhen, da sich die Daten häufig ändern. 
---
= Bearbeiten Sie Schutzbeziehungen auf der Seite „Volume-/Integritätsdetails“.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können vorhandene Schutzbeziehungen bearbeiten, um die aktuelle maximale Übertragungsrate, Schutzrichtlinie oder den Schutzzeitplan zu ändern.  Sie können eine Beziehung bearbeiten, um die für Übertragungen verwendete Bandbreite zu verringern oder die Häufigkeit geplanter Übertragungen zu erhöhen, da sich die Daten häufig ändern.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation installiert und konfiguriert haben.


Die ausgewählten Volumes müssen Ziele mit Schutzbeziehung sein.  Sie können Beziehungen nicht bearbeiten, wenn Quellvolumes, Load-Sharing-Volumes oder Volumes ausgewählt sind, die nicht das Ziel einer SnapMirror oder SnapVault -Beziehung sind.

.Schritte
. Suchen Sie auf der Registerkarte *Schutz* der Detailseite *Volume/Integrität* in der Topologie die Schutzbeziehung, die Sie bearbeiten möchten, und klicken Sie mit der rechten Maustaste darauf.
. Wählen Sie im Menü *Bearbeiten*.
+
Alternativ können Sie im Menü *Aktionen* die Option *Beziehung* > *Bearbeiten* auswählen, um die Beziehung zu bearbeiten, deren Details Sie gerade anzeigen.

+
Das Dialogfeld *Beziehung bearbeiten* wird angezeigt.

. Bearbeiten Sie im Dialogfeld „Beziehung bearbeiten“ nach Bedarf die maximale Übertragungsrate, die Schutzrichtlinie oder den Schutzzeitplan.
. Klicken Sie auf *Übernehmen*.
+
Die Änderungen werden auf die ausgewählten Beziehungen angewendet.


