---
permalink: data-protection/task_create_snapmirror_policy_to_maximize_transfer_efficiency.html 
sidebar: sidebar 
keywords: create, snapmirror, policy, maximize, transfer, efficiency 
summary: Sie können eine SnapMirror Richtlinie erstellen, um die SnapMirror Übertragungspriorität für Schutzbeziehungen festzulegen.  Mithilfe der SnapMirror -Richtlinien können Sie die Übertragungseffizienz von der Quelle zum Ziel maximieren, indem Sie Prioritäten zuweisen, sodass Übertragungen mit niedrigerer Priorität nach Übertragungen mit normaler Priorität ausgeführt werden. 
---
= Erstellen Sie eine SnapMirror -Richtlinie, um die Übertragungseffizienz zu maximieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine SnapMirror Richtlinie erstellen, um die SnapMirror Übertragungspriorität für Schutzbeziehungen festzulegen.  Mithilfe der SnapMirror -Richtlinien können Sie die Übertragungseffizienz von der Quelle zum Ziel maximieren, indem Sie Prioritäten zuweisen, sodass Übertragungen mit niedrigerer Priorität nach Übertragungen mit normaler Priorität ausgeführt werden.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen die Workflow-Automatisierung eingerichtet haben.
* Diese Aufgabe setzt voraus, dass Sie den Bereich „Zielinformationen“ im Dialogfeld „Schutz konfigurieren“ bereits ausgefüllt haben.


.Schritte
. Klicken Sie auf der Registerkarte * SnapMirror* des Dialogfelds *Schutz konfigurieren* im Bereich *Beziehungseinstellungen* auf den Link *Richtlinie erstellen*.
+
Das Dialogfeld „SnapMirror -Richtlinie erstellen“ wird angezeigt.

. Geben Sie im Feld *Richtlinienname* einen Namen ein, den Sie der Richtlinie geben möchten.
. Wählen Sie im Feld *Übertragungspriorität* die Übertragungspriorität aus, die Sie der Richtlinie zuweisen möchten.
. Geben Sie im Feld *Kommentar* einen optionalen Kommentar zur Richtlinie ein.
. Klicken Sie auf *Erstellen*.
+
Die neue Richtlinie wird in der Dropdown-Liste „SnapMirror -Richtlinie“ angezeigt.


