---
permalink: data-protection/task_create_snapvault_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, volume, health details page 
summary: Sie können mithilfe der Seite „Volume-/Integritätsdetails“ eine SnapVault Beziehung erstellen, sodass Datensicherungen zu Schutzzwecken auf Volumes aktiviert werden. 
---
= Erstellen Sie eine SnapVault -Schutzbeziehung auf der Seite „Volume/Health-Details“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mithilfe der Seite „Volume-/Integritätsdetails“ eine SnapVault Beziehung erstellen, sodass Datensicherungen zu Schutzzwecken auf Volumes aktiviert werden.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen die Workflow-Automatisierung eingerichtet haben, um diese Aufgabe auszuführen.


Das Menü *Schützen* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen: zum Beispiel, wenn Sie nur über Operator-Berechtigungen verfügen
* Wenn die Volume-ID unbekannt ist: beispielsweise, wenn Sie eine Intercluster-Beziehung haben und der Zielcluster noch nicht erkannt wurde


.Schritte
. Klicken Sie auf der Registerkarte *Schutz* der Detailseite *Volume/Integrität* mit der rechten Maustaste auf ein Volume in der Topologieansicht, das Sie schützen möchten.
. Wählen Sie im Menü *Schützen* > * SnapVault*.
+
Das Dialogfeld „Schutz konfigurieren“ wird geöffnet.

. Klicken Sie auf * SnapVault*, um die Registerkarte * SnapVault* anzuzeigen und die Informationen zur sekundären Ressource zu konfigurieren.
. Klicken Sie auf *Erweitert*, um Deduplizierung, Komprimierung, automatische Vergrößerung und Speicherplatzgarantie nach Bedarf einzustellen, und klicken Sie dann auf *Übernehmen*.
. Füllen Sie die Bereiche *Zielinformationen* und *Beziehungseinstellungen* im Dialogfeld *Schutz konfigurieren* aus.
. Klicken Sie auf *Übernehmen*.
+
Sie werden zur Seite mit den Volumen-/Gesundheitsdetails zurückgeleitet.

. Klicken Sie oben auf der Detailseite *Volume/Integrität* auf den Link zum Schutzkonfigurationsauftrag.
+
Die Seite mit den Auftragsdetails wird angezeigt.

. Klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails im Zusammenhang mit dem Schutzkonfigurationsauftrag zu aktualisieren und festzustellen, wann der Auftrag abgeschlossen ist.
+
Wenn die Jobaufgaben abgeschlossen sind, werden die neuen Beziehungen in der Topologieansicht der Seite „Volume-/Integritätsdetails“ angezeigt.


