---
permalink: data-protection/task_quiesce_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: quiesce, protection, relationship, volume, health details page 
summary: Sie können eine Schutzbeziehung stilllegen, um Datenübertragungen vorübergehend zu verhindern.  Sie können eine Beziehung stilllegen, wenn Sie eine Snapshot-Kopie eines SnapMirror Zielvolumes erstellen möchten, das eine Datenbank enthält, und Sie sicherstellen möchten, dass der Inhalt während der Snapshot-Kopie stabil bleibt. 
---
= Beenden Sie eine Schutzbeziehung auf der Seite „Volume-/Integritätsdetails“.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Schutzbeziehung stilllegen, um Datenübertragungen vorübergehend zu verhindern.  Sie können eine Beziehung stilllegen, wenn Sie eine Snapshot-Kopie eines SnapMirror Zielvolumes erstellen möchten, das eine Datenbank enthält, und Sie sicherstellen möchten, dass der Inhalt während der Snapshot-Kopie stabil bleibt.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen die Workflow-Automatisierung eingerichtet haben.


Die Stilllegungsaktion wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operator-Berechtigungen verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn Sie eine Intercluster-Beziehung haben und der Zielcluster noch nicht erkannt wurde
* Wenn Sie Workflow Automation und Unified Manager nicht gekoppelt haben


.Schritte
. Klicken Sie auf der Registerkarte *Schutz* der Detailseite *Volume/Integrität* in der Topologieansicht mit der rechten Maustaste auf die Beziehung für die Schutzbeziehung, die Sie stilllegen möchten.
. Wählen Sie im Menü „Ruhezustand“ aus.
. Klicken Sie auf *Ja*, um fortzufahren.
+
Der Status des Quiesce-Jobs wird oben auf der Seite „Volume-/Integritätsdetails“ zusammen mit einem Link zu den Jobdetails angezeigt.

. Klicken Sie auf den Link *Details anzeigen*, um zur Detailseite des *Auftrags* zu gelangen und dort weitere Einzelheiten und Informationen zum Auftragsfortschritt anzuzeigen.
. *Optional:* Klicken Sie in Ihrem Browser auf den Zurück-Pfeil, um zur Detailseite *Volumen/Gesundheit* zurückzukehren.
+
Der Quiesce-Job ist beendet, wenn alle Job-Aufgaben erfolgreich abgeschlossen wurden.


