---
permalink: data-protection/task_resume_scheduled_transfers_on_quiesced_relationship.html 
sidebar: sidebar 
keywords: resume, schedule, transfers, quiesce, relationship, volume relationships page 
summary: 'Nachdem Sie eine Beziehung stillgelegt haben, um geplante Übertragungen zu verhindern, können Sie mit „Fortsetzen“ geplante Übertragungen wieder aktivieren, sodass die Daten auf dem Quell- oder Primärdatenträger geschützt sind.  Die Übertragungen werden ab einem Prüfpunkt (sofern vorhanden) beim nächsten geplanten Übertragungsintervall fortgesetzt.' 
---
= Fortsetzen geplanter Übertragungen einer stillgelegten Beziehung über die Seite „Volume-Beziehungen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie eine Beziehung stillgelegt haben, um geplante Übertragungen zu verhindern, können Sie mit *Fortsetzen* geplante Übertragungen wieder aktivieren, sodass die Daten auf dem Quell- oder Primärdatenträger geschützt sind.  Die Übertragungen werden ab einem Prüfpunkt (sofern vorhanden) beim nächsten geplanten Übertragungsintervall fortgesetzt.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen die Workflow-Automatisierung eingerichtet haben.


Sie können nicht mehr als 10 stillgelegte Beziehungen auswählen, für die die Übertragungen wieder aufgenommen werden sollen.

.Schritte
. Wählen Sie auf der Seite „Volume-Beziehungen“ ein oder mehrere Volumes mit stillgelegten Beziehungen aus und klicken Sie in der Symbolleiste auf „Fortsetzen“.
. Klicken Sie im Dialogfeld *Fortsetzen* auf *Weiter*.
+
Sie werden zur Seite „Volumenbeziehungen“ zurückgeleitet.

. Um die zugehörigen Jobaufgaben anzuzeigen und ihren Fortschritt zu verfolgen, klicken Sie auf den Joblink, der oben auf der Seite *Volumenbeziehungen* angezeigt wird.
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn nur ein Job angezeigt wird, klicken Sie auf der Seite „Jobdetails“ auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Schutzkonfigurationsjob verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
** Wenn mehr als ein Job angezeigt wird,
+
... Klicken Sie auf der Seite „Jobs“ auf den Job, dessen Details Sie anzeigen möchten.
... Klicken Sie auf der Seite „Auftragsdetails“ auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails im Zusammenhang mit dem Schutzkonfigurationsauftrag zu aktualisieren und festzustellen, wann der Auftrag abgeschlossen ist.  Nach Abschluss der Jobs werden die Datenübertragungen im nächsten geplanten Übertragungsintervall fortgesetzt.





