---
permalink: data-protection/task_create_resource_pools.html 
sidebar: sidebar 
keywords: creating, resource, pools 
summary: Sie können das Dialogfeld „Ressourcenpool erstellen“ verwenden, um Aggregate für Bereitstellungszwecke zu gruppieren. 
---
= Erstellen von Ressourcenpools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Dialogfeld „Ressourcenpool erstellen“ verwenden, um Aggregate für Bereitstellungszwecke zu gruppieren.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
Ressourcenpools können Aggregate aus verschiedenen Clustern enthalten, aber dasselbe Aggregat kann nicht zu verschiedenen Ressourcenpools gehören.

. Klicken Sie im linken Navigationsbereich auf *Schutz* > *Ressourcenpools*.
. Klicken Sie auf der Seite *Ressourcenpools* auf *Erstellen*.
. Befolgen Sie die Anweisungen im Dialogfeld *Ressourcenpool erstellen*, um einen Namen und eine Beschreibung anzugeben und Aggregate als Mitglieder zum Ressourcenpool hinzuzufügen, den Sie erstellen möchten.

