---
permalink: data-protection/task_view_volume_protection_relationships.html 
sidebar: sidebar 
keywords: view, volume, protection relationships 
summary: 'In der Ansicht „Beziehung: Alle Beziehungen“ und auf der Seite „Volume-Beziehungen“ können Sie den Status bestehender Volume- SnapMirror und SnapVault -Beziehungen anzeigen.  Sie können auch Details zu Schutzbeziehungen prüfen, einschließlich Übertragungs- und Verzögerungsstatus, Quell- und Zieldetails, Zeitplan- und Richtlinieninformationen usw.' 
---
= Anzeigen von Volume-Schutzbeziehungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In der Ansicht „Beziehung: Alle Beziehungen“ und auf der Seite „Volume-Beziehungen“ können Sie den Status bestehender Volume- SnapMirror und SnapVault -Beziehungen anzeigen.  Sie können auch Details zu Schutzbeziehungen prüfen, einschließlich Übertragungs- und Verzögerungsstatus, Quell- und Zieldetails, Zeitplan- und Richtlinieninformationen usw.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Sie können von dieser Seite aus auch Beziehungsbefehle initiieren.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicher* > *Volumes*.
. Wählen Sie im Menü „Ansicht“ die Option „Beziehung“ > „Alle Beziehungen“ aus.
+
Die Ansicht „Beziehung: Alle Beziehungen“ wird angezeigt.

. Wählen Sie eine der folgenden Möglichkeiten, um die Details zum Volumeschutz anzuzeigen:
+
** Um aktuelle Informationen zu allen Volumenbeziehungen anzuzeigen, bleiben Sie auf der Standardseite *Alle Beziehungen*.
** Um detaillierte Informationen zu den Volumenübertragungstrends über einen bestimmten Zeitraum anzuzeigen, wählen Sie im Menü „Ansicht“ die Option „Beziehung: Übertragungsstatusansicht des letzten Monats“.
** Um detaillierte Informationen zur täglichen Volumenübertragungsaktivität anzuzeigen, wählen Sie im Menü „Ansicht“ die Option „Beziehung: Übertragungsrate des letzten Monats“ aus.


+
[NOTE]
====
Die Volume-Übertragungsansichten zeigen nur Informationen zu Volumes in asynchronen Beziehungen an – Volumes in synchronen Beziehungen werden nicht angezeigt.

====

