---
permalink: data-protection/task_monitor_storage_vms_using_relationships_page.html 
sidebar: sidebar 
keywords: relationships page, monitor, storage, vm 
summary: Sie können die Disaster-Recovery-Beziehungen Ihrer Storage-VMs auf der Seite „Beziehungen“ im Abschnitt „SCHUTZ“ des Inventars überwachen.  Standardmäßig werden auf der Seite „Beziehungen“ nur die Beziehungen der obersten Ebene aufgelistet, da der Filter für die Beziehungen der Bestandteile angewendet wird. 
---
= Überwachen von Speicher-VMs mithilfe der Seite „Beziehungen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Disaster-Recovery-Beziehungen Ihrer Storage-VMs auf der Seite „Beziehungen“ im Abschnitt „SCHUTZ“ des Inventars überwachen.  Standardmäßig werden auf der Seite „Beziehungen“ nur die Beziehungen der obersten Ebene aufgelistet, da der Filter für die Beziehungen der Bestandteile angewendet wird.

.Bevor Sie beginnen
Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Sie verwenden Filter, um die Disaster-Recovery-Beziehungen der Speicher-VM anzuzeigen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *SCHUTZ* > *Beziehungen*.
+
Auf der Seite werden alle Beziehungstypen angezeigt: Volume-, Konsistenzgruppen- und Speicher-VM-Beziehungen.

. Klicken Sie auf *Filter* und wählen Sie dann *Beziehungsobjekttyp* und *Speicher-VM* aus, um nur die Beziehungen zur Notfallwiederherstellung von Speicher-VMs anzuzeigen.
. Klicken Sie auf *Filter anwenden*.
+
[NOTE]
====
Sie sollten den Filter für die Bestandteilbeziehungen löschen, um alle Schutzbeziehungen anzuzeigen.

====
+
Auf der Seite werden nur Speicher-VM-Notfallwiederherstellungsbeziehungen angezeigt.


