---
permalink: data-protection/task_set_up_protection_relationships_in_unified_manager.html 
sidebar: sidebar 
keywords: set, protection, relationships, unified manager 
summary: Um mit Unified Manager und OnCommand Workflow Automation SnapMirror und SnapVault -Beziehungen zum Schutz Ihrer Daten einzurichten, müssen Sie mehrere Schritte ausführen. 
---
= Einrichten von Schutzbeziehungen im Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um mit Unified Manager und OnCommand Workflow Automation SnapMirror und SnapVault -Beziehungen zum Schutz Ihrer Daten einzurichten, müssen Sie mehrere Schritte ausführen.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Peer-Beziehungen zwischen zwei Clustern oder zwei virtuellen Speichermaschinen (SVMs) eingerichtet haben.
* OnCommand Workflow Automation muss in Unified Manager integriert werden:
+
** link:task_configure_connection_between_workflow_automation_um.html["Einrichten der OnCommand Workflow Automation"].
** link:task_verify_um_data_source_caching_in_workflow_automation.html["Überprüfen des Unified Manager-Datenquellen-Cachings in der Workflow-Automatisierung"].




.Schritte
. Führen Sie je nach Art der Schutzbeziehung, die Sie erstellen möchten, einen der folgenden Schritte aus:
+
** link:task_create_snapmirror_relationship_from_health_volume.html["Erstellen einer SnapMirror Schutzbeziehung"].
** link:task_create_snapvault_protection_relationship_from_health_volume_details.html["Erstellen einer SnapVault -Schutzbeziehung"].


. Wenn Sie eine Richtlinie für die Beziehung erstellen möchten, führen Sie je nach dem von Ihnen erstellten Beziehungstyp einen der folgenden Schritte aus:
+
** link:task_create_snapvault_policy_to_maximize_transfer_efficiency.html["Erstellen einer SnapVault -Richtlinie"].
** link:task_create_snapmirror_policy_to_maximize_transfer_efficiency.html["Erstellen einer SnapMirror -Richtlinie"].


. link:task_create_snapmirror_and_snapvault_schedules.html["Erstellen Sie einen SnapMirror oder SnapVault -Zeitplan"].

