---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: Sie können die Seite mit den Volume-/Integritätsdetails verwenden, um eine SnapMirror -Beziehung zu erstellen, sodass die Datenreplikation zu Schutzzwecken aktiviert wird.  Mit der SnapMirror -Replikation können Sie im Falle eines Datenverlusts auf der Quelle Daten vom Zielvolume wiederherstellen. 
---
= Erstellen Sie eine SnapMirror -Schutzbeziehung auf der Seite „Volume/Health-Details“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Seite mit den Volume-/Integritätsdetails verwenden, um eine SnapMirror -Beziehung zu erstellen, sodass die Datenreplikation zu Schutzzwecken aktiviert wird.  Mit der SnapMirror -Replikation können Sie im Falle eines Datenverlusts auf der Quelle Daten vom Zielvolume wiederherstellen.

.Bevor Sie beginnen
* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen die Workflow-Automatisierung eingerichtet haben.


Das Menü *Schützen* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen: zum Beispiel, wenn Sie nur über Operator-Berechtigungen verfügen
* Wenn die Volume-ID unbekannt ist: beispielsweise, wenn Sie eine Intercluster-Beziehung haben und der Zielcluster noch nicht erkannt wurde


Sie können bis zu 10 Schutzaufträge gleichzeitig ausführen, ohne dass die Leistung darunter leidet.  Wenn Sie zwischen 11 und 30 Jobs gleichzeitig ausführen, kann es zu Leistungseinbußen kommen.  Es wird nicht empfohlen, mehr als 30 Jobs gleichzeitig auszuführen.

.Schritte
. Klicken Sie auf der Registerkarte *Schutz* der Detailseite *Volume/Integrität* in der Topologieansicht mit der rechten Maustaste auf den Namen eines Volumes, das Sie schützen möchten.
. Wählen Sie im Menü *Schützen* > * SnapMirror*.
+
Das Dialogfeld „Schutz konfigurieren“ wird angezeigt.

. Klicken Sie auf * SnapMirror*, um die Registerkarte * SnapMirror* anzuzeigen und die Zielinformationen zu konfigurieren.
. Klicken Sie auf *Erweitert*, um die Speicherplatzgarantie nach Bedarf festzulegen, und klicken Sie dann auf *Übernehmen*.
. Füllen Sie die Bereiche *Zielinformationen* und *Beziehungseinstellungen* im Dialogfeld *Schutz konfigurieren* aus.
. Klicken Sie auf *Übernehmen*.
+
Sie werden zur Seite mit den Volumen-/Gesundheitsdetails zurückgeleitet.

. Klicken Sie oben auf der Detailseite *Volume/Integrität* auf den Link zum Schutzkonfigurationsauftrag.
+
Die Aufgaben und Details des Auftrags werden auf der Seite „Auftragsdetails“ angezeigt.

. Klicken Sie auf der Detailseite des *Auftrags* auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Schutzkonfigurationsauftrag verknüpft sind, und um festzustellen, wann der Auftrag abgeschlossen ist.
. Wenn die Jobaufgaben abgeschlossen sind, klicken Sie in Ihrem Browser auf *Zurück*, um zur Detailseite *Volumen/Zustand* zurückzukehren.
+
Die neue Beziehung wird in der Topologieansicht der Seite „Volume-/Integritätsdetails“ angezeigt.



Abhängig von der Ziel-SVM, die Sie während der Konfiguration angegeben haben, oder von den Optionen, die Sie in Ihren erweiterten Einstellungen aktiviert haben, kann die resultierende SnapMirror Beziehung eine von mehreren möglichen Variationen sein:

* Wenn Sie eine Ziel-SVM angegeben haben, die im Vergleich zum Quellvolume unter derselben oder einer neueren Version von ONTAP ausgeführt wird, ist eine auf Blockreplikation basierende SnapMirror Beziehung das Standardergebnis.
* Wenn Sie eine Ziel-SVM angegeben haben, die unter derselben oder einer neueren Version von ONTAP im Vergleich zum Quellvolume ausgeführt wird, Sie aber in den erweiterten Einstellungen die versionsflexible Replikation aktiviert haben, ist das Ergebnis eine SnapMirror -Beziehung mit versionsflexibler Replikation.
* Wenn Sie eine Ziel-SVM angegeben haben, die unter einer früheren Version von ONTAP oder einer höheren Version als die des Quellvolumes ausgeführt wird und die frühere Version versionsflexible Replikation unterstützt, ist eine SnapMirror -Beziehung mit versionsflexibler Replikation das automatische Ergebnis.

